# Generated by Django 2.2.5 on 2019-10-18 17:43

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import posts.helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0005_auto_20191010_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='uuid')),
                ('comments_enabled', models.BooleanField(default=True, verbose_name='Разрешить комментарии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Изменено')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыто')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('text', models.TextField(max_length=5000, null=True, verbose_name='Текст')),
                ('status', models.CharField(choices=[('D', 'Черновик'), ('PG', 'Обработка'), ('P', 'Опубликовано'), ('A', 'Архивирован')], default='D', max_length=2, verbose_name='Статус записи')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='изображение')),
                ('community', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.Community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Запись',
                'ordering': ['-created'],
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='PostRepost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_repost', to='posts.Post', verbose_name='Запись')),
            ],
        ),
        migrations.CreateModel(
            name='PostMute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muter', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='post_mutes', to=settings.AUTH_USER_MODEL, verbose_name='Кто заглушил')),
                ('post', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='posts.Post', verbose_name='Запись')),
            ],
        ),
        migrations.CreateModel(
            name='PostDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to=posts.helpers.upload_to_post_directory, verbose_name='Документ')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_doc', to='posts.Post', verbose_name='Документ')),
            ],
        ),
        migrations.CreateModel(
            name='PostUserMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_mentions', to='posts.Post', verbose_name='Запись')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='post_mentions', to=settings.AUTH_USER_MODEL, verbose_name='Упоминаемый')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.AddIndex(
            model_name='postrepost',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='posts_postr_created_777331_brin'),
        ),
        migrations.AlterUniqueTogether(
            name='postmute',
            unique_together={('post', 'muter')},
        ),
    ]
