# Generated by Django 2.2.5 on 2020-03-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdoc',
            name='doc',
            field=models.FileField(upload_to='posts/', verbose_name='Документ'),
        ),
    ]
