# Generated by Django 2.2.5 on 2019-09-05 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20190905_1211'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='communities.Community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcommentmute',
            name='muter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_mutes', to=settings.AUTH_USER_MODEL, verbose_name='Кто заглушил'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcommentreaction',
            name='reactor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Кто отреагировал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcommentusermention',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_mentions', to=settings.AUTH_USER_MODEL, verbose_name='Упомянутый в комментарии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmute',
            name='muter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_mutes', to=settings.AUTH_USER_MODEL, verbose_name='Кто заглушил'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postreaction',
            name='reactor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postusermention',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_mentions', to=settings.AUTH_USER_MODEL, verbose_name='Упоминаемый'),
            preserve_default=False,
        ),
    ]
