# Generated by Django 3.2 on 2021-04-30 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20210430_1519'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlist',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='_posts_postlist_communities_+', to='communities.Community'),
        ),
        migrations.AddField(
            model_name='postlist',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_postlist', to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='postlist',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_posts_postlist_users_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postlist',
            name='type',
            field=models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('PRI', 'Приватный'), ('MAN', 'Созданный персоналом'), ('TPRO', 'Обработка'), ('TFIX', 'Закреплённый'), ('DRA', 'Предложка'), ('TDEL', 'Удалённый'), ('TDELP', 'Удалённый приватный'), ('TDELM', 'Удалённый менеджерский'), ('TCLO', 'Закрытый менеджером'), ('TCLOP', 'Закрытый приватный'), ('TCLOM', 'Закрытый основной'), ('TCLOMA', 'Закрытый менеджерский'), ('TCLOF', 'Закрытый закреплённый')], default='TPRO', max_length=6, verbose_name='Тип списка'),
        ),
    ]
