# Generated by Django 2.2.5 on 2019-10-26 22:29

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import posts.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Главное изображение')),
                ('image2', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 2')),
                ('image3', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 3')),
                ('image4', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 4')),
                ('image5', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 5')),
                ('image6', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 6')),
                ('image7', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 7')),
                ('image8', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 8')),
                ('post', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to='posts.Post')),
            ],
        ),
    ]
