# Generated by Django 2.2.5 on 2019-11-02 10:39

from django.db import migrations
import imagekit.models.fields
import posts.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='post',
            name='image5',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 5'),
        ),
        migrations.AddField(
            model_name='post',
            name='image6',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 6'),
        ),
        migrations.AddField(
            model_name='post',
            name='image7',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 7'),
        ),
        migrations.AddField(
            model_name='post',
            name='image8',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 8'),
        ),
    ]
