# Generated by Django 2.2.5 on 2019-11-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191102_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
