# Generated by Django 3.1 on 2020-08-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='community',
        ),
    ]
