# Generated by Django 2.2.5 on 2019-09-05 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190905_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='postcommentreaction',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
