# Generated by Django 2.2.5 on 2019-10-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='object_id',
        ),
    ]
