# Generated by Django 2.2.5 on 2019-09-13 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190913_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='reply',
            field=models.BooleanField(default=False, verbose_name='Это репост?'),
        ),
    ]
