# Generated by Django 2.2.16 on 2020-09-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('D', 'Черновик'), ('PG', 'Обработка'), ('P', 'Опубликована'), ('A', 'Архивирована'), ('C', 'Репост фотографии'), ('PAR', 'Репост фотоальбома'), ('GR', 'Репост товара'), ('MR', 'Репост аудиозаписи'), ('MLR', 'Репост плейлиста аудиозаписей'), ('DR', 'Репост документа'), ('DLR', 'Репост списка документов'), ('VR', 'Репост видеозаписи'), ('VLR', 'Репост списка видеозаписей'), ('UR', 'Репост пользователя'), ('CR', 'Репост сообщества')], default='P', max_length=5, verbose_name='Статус статьи'),
        ),
    ]
