# Generated by Django 2.2.5 on 2019-09-05 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190905_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='hash',
        ),
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='communities.Community', verbose_name='Сообщество'),
        ),
    ]
