# Generated by Django 2.2.5 on 2019-11-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_delete_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image8',
        ),
    ]
