# Generated by Django 3.2 on 2021-05-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210430_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlist',
            name='type',
            field=models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('PRI', 'Приватный'), ('MAN', 'Созданный персоналом'), ('_PRO', 'Обработка'), ('_FIX', 'Закреплённый'), ('_DRA', 'Предложка'), ('_DEL', 'Удалённый'), ('_DELP', 'Удалённый приватный'), ('_DELM', 'Удалённый менеджерский'), ('_CLO', 'Закрытый менеджером'), ('_CLOP', 'Закрытый приватный'), ('_CLOM', 'Закрытый основной'), ('_CLOMA', 'Закрытый менеджерский'), ('_CLOF', 'Закрытый закреплённый')], default='_PRO', max_length=6, verbose_name='Тип списка'),
        ),
    ]
