# Generated by Django 2.2.5 on 2019-10-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_postcomment_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
