# Generated by Django 2.2.5 on 2019-10-04 22:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_postcomment_object_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repost',
            new_name='PostRepost',
        ),
    ]
