# Generated by Django 2.2.5 on 2019-10-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191004_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_hard',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_lite',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_medium',
        ),
    ]
