# Generated by Django 3.2 on 2021-05-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210501_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ad_view',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во рекламных просмотров'),
        ),
    ]
