# Generated by Django 2.2.5 on 2019-09-30 19:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190930_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
