# Generated by Django 2.2.5 on 2019-09-05 21:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190905_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', null=True, verbose_name='Полное содержание'),
        ),
    ]
