# Generated by Django 2.2.5 on 2019-10-06 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20191005_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='postrepost',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='postrepost',
            name='object_id',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='posts.Post'),
            preserve_default=False,
        ),
    ]
