# Generated by Django 2.2.5 on 2019-09-05 22:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190905_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Полное содержание'),
        ),
    ]
