# Generated by Django 2.2.5 on 2019-10-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20191001_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='object_id',
        ),
    ]
