# Generated by Django 2.2.5 on 2019-10-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20191006_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrepost',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_repost', to='posts.Post'),
            preserve_default=False,
        ),
    ]
