# Generated by Django 2.2.5 on 2019-10-06 15:42

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import posts.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_postrepost_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('D', 'Черновик'), ('PG', 'Обработка'), ('P', 'Опубликовано'), ('A', 'Архивирован')], default='D', max_length=2, verbose_name='Статус записи'),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=5000, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='posts.Post', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='postcommentmute',
            name='post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='posts.PostComment', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='postcommentusermention',
            name='post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mentions', to='posts.PostComment', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='postmute',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='posts.Post', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='postrepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_repost', to='posts.Post', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='postusermention',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mentions', to='posts.Post', verbose_name='Запись'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Главное изображение')),
                ('image2', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 2')),
                ('image3', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 3')),
                ('image4', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 4')),
                ('image5', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 5')),
                ('image6', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 6')),
                ('image7', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 7')),
                ('image8', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 8')),
                ('image9', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 9')),
                ('image10', imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='Изображение 10')),
                ('post', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PostDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to=posts.helpers.upload_to_post_directory, verbose_name='Документ')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_doc', to='posts.Post', verbose_name='Документ')),
            ],
        ),
    ]
