# Generated by Django 3.2 on 2021-05-06 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_type'),
        ('posts', '0008_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_community', to='communities.community', verbose_name='Сообщество'),
        ),
    ]
