# Generated by Django 2.2.5 on 2019-10-01 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0008_auto_20191001_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='content_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcomment',
            name='object_id',
            field=models.PositiveIntegerField(default=''),
            preserve_default=False,
        ),
    ]
