# Generated by Django 3.2 on 2021-05-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_community'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='status',
            new_name='type',
        ),
    ]
