# Generated by Django 2.2.5 on 2019-10-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20191001_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='object_id',
        ),
    ]
