# Generated by Django 2.2.5 on 2019-10-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20191006_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
