# Generated by Django 2.2.5 on 2019-10-09 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20191006_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='modified',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
