# Generated by Django 2.2.5 on 2019-10-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20191001_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply',
            field=models.BooleanField(default=False, verbose_name='Это репост?'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='posts.Post', verbose_name='Пост'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
