# Generated by Django 3.2 on 2021-06-13 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210613_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='list',
        ),
        migrations.AddField(
            model_name='post',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_list', to='posts.postlist'),
        ),
    ]
