# Generated by Django 2.2.5 on 2019-10-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20191010_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uuid',
            new_name='post_uuid',
        ),
    ]
