# Generated by Django 3.2 on 2021-06-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlist',
            options={'verbose_name': 'список записей', 'verbose_name_plural': 'списки записей'},
        ),
        migrations.RemoveField(
            model_name='postlist',
            name='order',
        ),
    ]
