# Generated by Django 2.2.5 on 2019-10-10 18:16

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20191010_1716'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postrepost',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='posts_postr_created_777331_brin'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='posts_postc_created_3ec60a_brin'),
        ),
    ]
