# Generated by Django 2.2.5 on 2019-10-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_auto_20191010_1837'),
        ('posts', '0015_auto_20191010_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='communities.Community', verbose_name='Сообщество'),
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together={('community',)},
        ),
    ]
