# Generated by Django 3.2 on 2021-07-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_postcomment_sticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('PRO', 'Обработка'), ('_DRA', 'Черновик'), ('_FIX', 'Закреплен'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('_CLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('_DELM', 'Удалённый менеджерский'), ('_CLOM', 'Закрытый менеджерский'), ('_MES', 'Репост в сообщения')], default='PRO', max_length=5, verbose_name='Статус статьи'),
        ),
        migrations.AlterField(
            model_name='postlist',
            name='type',
            field=models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('MAN', 'Созданный персоналом'), ('_PRO', 'Обработка'), ('_FIX', 'Закреплённый'), ('_DRA', 'Предложка'), ('_DEL', 'Удалённый'), ('_DELM', 'Удалённый менеджерский'), ('_CLO', 'Закрытый менеджером'), ('_CLOM', 'Закрытый основной'), ('_CLOMA', 'Закрытый менеджерский'), ('_CLOF', 'Закрытый закреплённый')], default='_PRO', max_length=6, verbose_name='Тип списка'),
        ),
    ]
