# Generated by Django 2.2.5 on 2019-10-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20191010_1848'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='post',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments_enabled',
        ),
        migrations.RemoveField(
            model_name='post',
            name='community',
        ),
    ]
