# Generated by Django 2.2.5 on 2019-10-10 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0017_auto_20191010_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentmute',
            name='muter',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_mutes', to=settings.AUTH_USER_MODEL, verbose_name='Кто заглушил'),
        ),
        migrations.AlterField(
            model_name='postcommentmute',
            name='post_comment',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='posts.PostComment', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='postcommentusermention',
            name='post_comment',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_mentions', to='posts.PostComment', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='postcommentusermention',
            name='user',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_mentions', to=settings.AUTH_USER_MODEL, verbose_name='Упомянутый в комментарии'),
        ),
        migrations.AlterField(
            model_name='postmute',
            name='muter',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='post_mutes', to=settings.AUTH_USER_MODEL, verbose_name='Кто заглушил'),
        ),
        migrations.AlterField(
            model_name='postmute',
            name='post',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='posts.Post', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='postrepost',
            name='author',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postrepost',
            name='post',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='post_repost', to='posts.Post', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='postusermention',
            name='post',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_mentions', to='posts.Post', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='postusermention',
            name='user',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='post_mentions', to=settings.AUTH_USER_MODEL, verbose_name='Упоминаемый'),
        ),
        migrations.AlterUniqueTogether(
            name='postcommentmute',
            unique_together={('post_comment', 'muter')},
        ),
        migrations.AlterUniqueTogether(
            name='postcommentusermention',
            unique_together={('user', 'post_comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postmute',
            unique_together={('post', 'muter')},
        ),
        migrations.AlterUniqueTogether(
            name='postrepost',
            unique_together={('author', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='postusermention',
            unique_together={('user', 'post')},
        ),
    ]
