# Generated by Django 3.2 on 2021-09-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('PRO', 'Обработка'), ('_COF', 'Предложка сообщества'), ('_UOF', 'Предложка пользователя'), ('_CDR', 'Черновик владельца'), ('_COF', 'Черновик предложки'), ('_FIX', 'Закреплен'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('_CLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('_DCOF', 'Удалённая предложка сообщества'), ('_DELM', 'Удалённая предложка пользователя'), ('_DELM', 'Удалённый менеджерский'), ('_CLOM', 'Закрытый менеджерский'), ('_MES', 'Репост в сообщения')], default='PRO', max_length=5, verbose_name='Статус статьи'),
        ),
    ]
