# Generated by Django 3.2 on 2021-09-22 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0019_alter_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlist',
            name='can_see_comment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья/подписчики'), (3, 'Друзья,друзья друзей/None'), (4, 'Только я/админы'), (5, 'Друзья/подписчики, кроме'), (6, 'Некоторые друзья/подписчики')], default=1, verbose_name='Кто видит комментарии'),
        ),
        migrations.AddField(
            model_name='postlist',
            name='can_see_item',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья/подписчики'), (3, 'Друзья,друзья друзей/None'), (4, 'Только я/админы'), (5, 'Друзья/подписчики, кроме'), (6, 'Некоторые друзья/подписчики')], default=1, verbose_name='Кто видит записи'),
        ),
        migrations.AddField(
            model_name='postlist',
            name='create_comment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья/подписчики'), (3, 'Друзья,друзья друзей/None'), (4, 'Только я/админы'), (5, 'Друзья/подписчики, кроме'), (6, 'Некоторые друзья/подписчики')], default=1, verbose_name='Кто пишет комментарии'),
        ),
        migrations.AddField(
            model_name='postlist',
            name='create_item',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья/подписчики'), (3, 'Друзья,друзья друзей/None'), (4, 'Только я/админы'), (5, 'Друзья/подписчики, кроме'), (6, 'Некоторые друзья/подписчики')], default=4, verbose_name='Кто создает записи и потом с этими документами работает'),
        ),
        migrations.AlterField(
            model_name='postlist',
            name='type',
            field=models.CharField(choices=[('MAI', 'Основной'), ('_T', 'TEST'), ('LIS', 'Пользовательский'), ('MAN', 'Созданный персоналом'), ('_PRO', 'Обработка'), ('_FIX', 'Закреплённый'), ('_DRA', 'Предложка'), ('_DEL', 'Удалённый'), ('_DELM', 'Удалённый менеджерский'), ('_CLO', 'Закрытый менеджером'), ('_CLOM', 'Закрытый основной'), ('_CLOMA', 'Закрытый менеджерский'), ('_CLOF', 'Закрытый закреплённый')], default='_PRO', max_length=6, verbose_name='Тип списка'),
        ),
        migrations.CreateModel(
            name='PostListPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_see_item', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (3, 'TEST')], default=0, verbose_name='Кто видит список/записи')),
                ('can_see_comment', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (3, 'TEST')], default=0, verbose_name='Кто видит комментарии')),
                ('create_item', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (3, 'TEST')], default=0, verbose_name='Кто создает записи')),
                ('create_comment', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (3, 'TEST')], default=0, verbose_name='Кто создает комментарии')),
                ('can_copy', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (3, 'TEST')], default=0, verbose_name='Кто может добавлять список/записи себе')),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.postlist', verbose_name='Список записей')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Исключения/Включения участника беседы',
                'verbose_name_plural': 'Исключения/Включения участников беседы',
            },
        ),
    ]
