# Generated by Django 2.2.5 on 2019-10-11 17:50

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0019_auto_20191011_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, max_length=1500, null=True)),
                ('is_edited', models.BooleanField(default=False, verbose_name='Изменено')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удаено')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_comments', to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.PostComment2', verbose_name='Родительский комментарий')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='posts.Post', verbose_name='Запись')),
            ],
        ),
        migrations.AlterField(
            model_name='postcommentmute',
            name='post_comment',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='posts.PostComment2', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='postcommentusermention',
            name='post_comment',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_mentions', to='posts.PostComment2', verbose_name='Запись'),
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.AddIndex(
            model_name='postcomment2',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='posts_postc_created_9e8287_brin'),
        ),
    ]
