# Generated by Django 3.2 on 2021-09-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20210922_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlist',
            name='create_copy',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья/подписчики'), (3, 'Друзья,друзья друзей/None'), (4, 'Только я/админы'), (5, 'Друзья/подписчики, кроме'), (6, 'Некоторые друзья/подписчики')], default=1, verbose_name='Кто может копировать'),
        ),
    ]
