# Generated by Django 2.2.5 on 2019-10-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20191011_1750'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcommentmute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postcommentmute',
            name='muter',
        ),
        migrations.RemoveField(
            model_name='postcommentmute',
            name='post_comment',
        ),
        migrations.AlterUniqueTogether(
            name='postcommentusermention',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postcommentusermention',
            name='post_comment',
        ),
        migrations.RemoveField(
            model_name='postcommentusermention',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='uuid',
        ),
        migrations.DeleteModel(
            name='PostComment2',
        ),
        migrations.DeleteModel(
            name='PostCommentMute',
        ),
        migrations.DeleteModel(
            name='PostCommentUserMention',
        ),
    ]
