# Generated by Django 2.2.5 on 2019-10-18 12:08

from django.db import migrations
import imagekit.models.fields
import posts.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20191017_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='image9',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='изображение'),
        ),
    ]
