# Generated by Django 2.2.5 on 2019-10-18 13:31

from django.db import migrations
import imagekit.models.fields
import posts.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20191018_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='изображение'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
