# Generated by Django 2.2.5 on 2019-10-18 13:35

from django.db import migrations
import imagekit.models.fields
import posts.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20191018_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='', upload_to=posts.helpers.upload_to_post_image_directory, verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
