# Generated by Django 3.2 on 2021-10-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_alter_postlist_create_el'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('_COF', 'Предложка сообщества'), ('_UOF', 'Предложка пользователя'), ('_CDR', 'Черновик владельца'), ('_COF', 'Черновик предложки'), ('_FIX', 'Закреплен'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('_CLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('_DCOF', 'Удалённая предложка сообщества'), ('_DELM', 'Удалённая предложка пользователя'), ('_DELM', 'Удалённый менеджерский'), ('_CLOM', 'Закрытый менеджерский'), ('_MES', 'Репост в сообщения')], max_length=5, verbose_name='Статус статьи'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='type',
            field=models.CharField(choices=[('PUB', 'Опубликовано'), ('EDI', 'Изменённый'), ('_DRA', 'Черновик'), ('_DEL', 'Удалённый'), ('_DELE', 'Удалённый изменённый'), ('_CLO', 'Закрытый менеджером'), ('_CLOE', 'Закрытый изменённый')], max_length=5, verbose_name='Тип альбома'),
        ),
        migrations.AlterField(
            model_name='postlist',
            name='type',
            field=models.CharField(choices=[('MAI', 'Основной'), ('_T', 'TEST'), ('LIS', 'Пользовательский'), ('MAN', 'Созданный персоналом'), ('_FIX', 'Закреплённый'), ('_DRA', 'Предложка'), ('_DEL', 'Удалённый'), ('_DELM', 'Удалённый менеджерский'), ('_CLO', 'Закрытый менеджером'), ('_CLOM', 'Закрытый основной'), ('_CLOMA', 'Закрытый менеджерский'), ('_CLOF', 'Закрытый закреплённый')], max_length=6, verbose_name='Тип списка'),
        ),
    ]
