# Generated by Django 3.2 on 2021-12-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20211205_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postslistperm',
            options={'verbose_name': 'Исключения/Включения друга', 'verbose_name_plural': 'Исключения/Включения друзей'},
        ),
        migrations.AlterField(
            model_name='postslistperm',
            name='can_copy',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто может добавлять список/записи себе'),
        ),
        migrations.AlterField(
            model_name='postslistperm',
            name='can_see_comment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто видит комментарии'),
        ),
        migrations.AlterField(
            model_name='postslistperm',
            name='can_see_item',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто видит список/записи'),
        ),
        migrations.AlterField(
            model_name='postslistperm',
            name='create_comment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто создает комментарии'),
        ),
        migrations.AlterField(
            model_name='postslistperm',
            name='create_item',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто создает записи'),
        ),
    ]
