# Generated by Django 3.2 on 2022-01-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20211207_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postslist',
            name='type',
            field=models.CharField(choices=[('MAI', 'Основной'), ('_T', 'TEST'), ('LIS', 'Пользовательский'), ('MAN', 'Созданный персоналом'), ('_DRA', 'Предложка'), ('_DEL', 'Удалённый'), ('_DELM', 'Удалённый менеджерский'), ('_CLO', 'Закрытый менеджером'), ('_CLOM', 'Закрытый основной'), ('_CLOMA', 'Закрытый менеджерский')], max_length=6, verbose_name='Тип списка'),
        ),
    ]
