# Generated by Django 3.2 on 2022-01-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_alter_postslist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('_COF', 'Предложка сообщества'), ('_UOF', 'Предложка пользователя'), ('_CDR', 'Черновик владельца'), ('_COF', 'Черновик предложки'), ('FIX', 'Закреплен'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('_CLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('_DCOF', 'Удалённая предложка сообщества'), ('_DELM', 'Удалённая предложка пользователя'), ('_DELM', 'Удалённый менеджерский'), ('_CLOM', 'Закрытый менеджерский'), ('_REP', 'Репост')], max_length=5, verbose_name='Статус статьи'),
        ),
    ]
