# Generated by Django 2.2.5 on 2019-09-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_connection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.Connection', verbose_name='Связь')),
            ],
        ),
    ]
