# Generated by Django 2.2.5 on 2019-09-11 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_connection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.Connection', verbose_name='Связь')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_connections', to=settings.AUTH_USER_MODEL, verbose_name='С кем связывается')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL, verbose_name='Кто связывается')),
            ],
        ),
    ]
