# Generated by Django 2.2.5 on 2019-09-05 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_auto_20190905_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='target_connection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.Connection', verbose_name='Связь'),
        ),
    ]
