# Generated by Django 2.2.5 on 2019-09-03 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import profiles.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('last_activity', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Activity')),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='user/list', verbose_name='Аватар')),
                ('cover', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=profiles.helpers.upload_to_user_cover_directory, verbose_name='Фон')),
                ('bio', models.TextField(blank=True, max_length=300, null=True, verbose_name='Биография')),
                ('url', models.URLField(blank=True, null=True, verbose_name='УРЛ')),
                ('followers_count_visible', models.BooleanField(default=False, verbose_name='Число подписчиков видно')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Местоположение')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
