# Generated by Django 2.2.5 on 2019-09-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190905_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_activity',
        ),
    ]
