# Generated by Django 2.2.5 on 2019-09-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_userprofile_last_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='sity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='badges',
        ),
    ]
