# Generated by Django 2.2.5 on 2019-09-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20190907_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='статус-слоган'),
        ),
    ]
