# Generated by Django 2.2.5 on 2019-10-05 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Активность'),
        ),
    ]
