# Generated by Django 2.2.5 on 2019-11-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Закрытый профиль'),
        ),
    ]
