# Generated by Django 2.2.16 on 2020-09-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_community'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='post_user', to='posts.Post'),
        ),
    ]
