# Generated by Django 3.2 on 2021-04-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='traks',
            new_name='tracks',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='articles',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во статей'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='docs',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во документов'),
        ),
    ]
