# Generated by Django 3.1 on 2020-08-26 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneuserlocation',
            name='city_lat',
            field=models.FloatField(blank=True, default=0, verbose_name='Ширина города'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oneuserlocation',
            name='city_lon',
            field=models.FloatField(blank=True, default=0, verbose_name='Долгота города'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='threeuserlocation',
            name='city_lat',
            field=models.FloatField(blank=True, default=0, verbose_name='Ширина города'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='threeuserlocation',
            name='city_lon',
            field=models.FloatField(blank=True, default=0, verbose_name='Долгота города'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twouserlocation',
            name='city_lat',
            field=models.FloatField(blank=True, default=0, verbose_name='Ширина города'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twouserlocation',
            name='city_lon',
            field=models.FloatField(blank=True, default=0, verbose_name='Долгота города'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileanketa',
            name='attitude_to_alcohol',
            field=models.CharField(blank=True, choices=[('Не выбрано', 'Не выбрано'), ('Резко негативное', 'Резко негативное'), ('Негативное', 'ДНегативное'), ('Компромиссное', 'Компромиссное'), ('Помогу бросить пить', 'Помогу бросить пить')], max_length=50, verbose_name='Отношение к алкоголю'),
        ),
        migrations.AlterField(
            model_name='userprofileanketa',
            name='attitude_to_smoking',
            field=models.CharField(blank=True, choices=[('Не выбрано', 'Не выбрано'), ('Резко негативное', 'Резко негативное'), ('Негативное', 'ДНегативное'), ('Компромиссное', 'Компромиссное'), ('Помогу бросить курить', 'Помогу бросить курить')], max_length=50, verbose_name='Отношение к курению'),
        ),
        migrations.AlterField(
            model_name='userprofileanketa',
            name='mainthing_in_life',
            field=models.CharField(blank=True, choices=[('Не выбрано', 'Не выбрано'), ('Семья и дети', 'Семья и дети'), ('Карьера и деньги', 'Карьера и деньги'), ('Развлечение и отдых', 'Развлечение и отдых'), ('Наука и исследования', 'Наука и исследования'), ('Совершенствование мира', 'Совершенствование мира'), ('Саморазвитие', 'Саморазвитие'), ('Красота и искусство', 'Красота и искусство'), ('Слава и влияние', 'Слава и влияние')], max_length=50, verbose_name='Главное в жизни'),
        ),
        migrations.AlterField(
            model_name='userprofileanketa',
            name='mainthing_in_people',
            field=models.CharField(blank=True, choices=[('Не выбрано', 'Не выбрано'), ('Ум и креативность', 'Ум и креативность'), ('Доброта и честность', 'Доброта и честность'), ('Красота и здоровье', 'Красота и здоровье'), ('Власть и богатство', 'Власть и богатство'), ('Смелость и упорство', 'Смелость и упорство'), ('Юмор и жизнелюбие', 'Юмор и жизнелюбие')], max_length=50, verbose_name='Главное в людях'),
        ),
        migrations.AlterField(
            model_name='userprofileanketa',
            name='political_preferences',
            field=models.CharField(blank=True, choices=[('Не выбраны', 'Не выбраны'), ('Индиффирентные', 'Индиффирентные'), ('Коммунистические', 'Коммунистические'), ('Социалистические', 'Социалистические'), ('Умеренные', 'Умеренные'), ('Либеральные', 'Либеральные'), ('Консервативные', 'Консервативные'), ('Либералистические', 'Либералистические'), ('Ультраконсервативные', 'Ультраконсервативные')], max_length=50, verbose_name='Полит. предпочтения'),
        ),
        migrations.AlterField(
            model_name='userprofileanketa',
            name='worldview',
            field=models.CharField(blank=True, choices=[('Не выбрано', 'Не выбрано'), ('Иудаизм', 'Иудаизм'), ('Православие', 'Православие'), ('Католицизм', 'Католицизм'), ('Протестантизм', 'Протестантизм'), ('Ислам', 'Ислам'), ('Буддизм', 'Буддизм'), ('Конфуцианство', 'Конфуцианство'), ('Светский гуманизм', 'Светский гуманизм'), ('Пастафарианство', 'Пастафарианство')], max_length=50, verbose_name='Мировоззрение'),
        ),
        migrations.AlterField(
            model_name='userprofilefamily',
            name='dad',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_dad', to=settings.AUTH_USER_MODEL, verbose_name='Папа'),
        ),
        migrations.AlterField(
            model_name='userprofilefamily',
            name='mom',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_mom', to=settings.AUTH_USER_MODEL, verbose_name='Мама'),
        ),
    ]
