# Generated by Django 2.2.5 on 2019-09-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190913_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на facebook'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на instagram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на twitter'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vk_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на vk'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на youtube'),
        ),
    ]
