# Generated by Django 2.2.5 on 2019-11-06 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationssettings',
            name='follow_notifications',
        ),
        migrations.RemoveField(
            model_name='usernotificationssettings',
            name='post_comment_notifications',
        ),
        migrations.RemoveField(
            model_name='usernotificationssettings',
            name='post_comment_reply_notifications',
        ),
        migrations.RemoveField(
            model_name='usernotificationssettings',
            name='post_comment_user_mention_notifications',
        ),
        migrations.RemoveField(
            model_name='usernotificationssettings',
            name='post_user_mention_notifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_private',
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='comment_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления о комментариях к записям'),
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='comment_react_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления о реакциях на комментарии к записям'),
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='comment_reply_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления об ответах на комментарии к записям'),
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='comment_reply_react_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления реакциях на ответы к комментариям'),
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='comment_user_mention_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления об упоминаниях в комментариях к записям'),
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='react_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления о реакциях к записи'),
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='repost_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления о репостах записей'),
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='user_mention_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления об упоминаниях в записям'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_global_moderator',
            field=models.BooleanField(default=False, verbose_name='Глобальный модератор'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Суперпользователь'),
        ),
        migrations.CreateModel(
            name='UserPrivateSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=False, verbose_name='Закрытый профиль')),
                ('can_message', models.BooleanField(default=True, verbose_name='Вам могут писать сообщения все пользователи')),
                ('photo_visible_all', models.BooleanField(default=True, verbose_name='Ваши фото видны всем')),
                ('photo_visible_frends', models.BooleanField(default=True, verbose_name='Ваши фото видны Вашим друзьям')),
                ('can_comments', models.BooleanField(default=True, verbose_name='Могут оставлять комментарии все пользователи')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
