# Generated by Django 2.2.5 on 2019-09-18 11:53

from django.db import migrations, models
import users.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190917_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=users.helpers.upload_to_user_avatar_directory, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=users.helpers.upload_to_user_cover_directory, verbose_name='Фон'),
        ),
    ]
