# Generated by Django 3.1 on 2020-08-28 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200828_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilefamily',
            name='dad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_dad', to=settings.AUTH_USER_MODEL, verbose_name='Папа'),
        ),
        migrations.AlterField(
            model_name='userprofilefamily',
            name='mom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_mom', to=settings.AUTH_USER_MODEL, verbose_name='Мама'),
        ),
        migrations.AlterField(
            model_name='userprofilefamily',
            name='partner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_partner', to=settings.AUTH_USER_MODEL, verbose_name='Муж/Жена'),
        ),
    ]
