# Generated by Django 3.1 on 2020-08-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200826_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneuserlocation',
            name='city_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина города'),
        ),
        migrations.AlterField(
            model_name='oneuserlocation',
            name='city_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота города'),
        ),
        migrations.AlterField(
            model_name='threeuserlocation',
            name='city_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина города'),
        ),
        migrations.AlterField(
            model_name='threeuserlocation',
            name='city_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота города'),
        ),
        migrations.AlterField(
            model_name='twouserlocation',
            name='city_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина города'),
        ),
        migrations.AlterField(
            model_name='twouserlocation',
            name='city_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота города'),
        ),
    ]
