# Generated by Django 2.2.5 on 2019-09-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190914_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на facebook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на instagram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sity',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Местоположение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='статус-слоган'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на twitter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vk_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на vk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='youtube_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на youtube'),
            preserve_default=False,
        ),
    ]
