# Generated by Django 2.2.5 on 2019-11-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191106_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprivatesettings',
            name='can_add_article',
            field=models.BooleanField(default=False, verbose_name='Вам могут писать статьи на стене'),
        ),
        migrations.AddField(
            model_name='userprivatesettings',
            name='can_add_good',
            field=models.BooleanField(default=False, verbose_name='Вам могут добавлять товары'),
        ),
        migrations.AddField(
            model_name='userprivatesettings',
            name='can_add_post',
            field=models.BooleanField(default=False, verbose_name='Вам могут писать записи на стене'),
        ),
    ]
