# Generated by Django 2.2.5 on 2019-09-24 20:18

from django.db import migrations
import imagekit.models.fields
import users.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190918_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=users.helpers.upload_to_user_avatar_directory, verbose_name='Аватар'),
        ),
    ]
