# Generated by Django 2.2.5 on 2020-01-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191210_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationssettings',
            name='comment_react_notifications',
        ),
        migrations.RemoveField(
            model_name='usernotificationssettings',
            name='comment_reply_react_notifications',
        ),
        migrations.RemoveField(
            model_name='usernotificationssettings',
            name='react_notifications',
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='comment_dislike_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления о дизлайках на комментарии к записям'),
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='comment_like_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления о лайках на комментарии к записям'),
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='comment_reply_dislike_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления о дизлайках на ответы к комментариям'),
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='comment_reply_like_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления о лайках на ответы к комментариям'),
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='dislike_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления о дизлайках к записям'),
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='like_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления о лайках к записям'),
        ),
    ]
