# Generated by Django 3.1 on 2020-08-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200826_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneuserlocation',
            name='city_lat',
        ),
        migrations.RemoveField(
            model_name='oneuserlocation',
            name='city_lon',
        ),
        migrations.RemoveField(
            model_name='threeuserlocation',
            name='city_lat',
        ),
        migrations.RemoveField(
            model_name='threeuserlocation',
            name='city_lon',
        ),
        migrations.RemoveField(
            model_name='twouserlocation',
            name='city_lat',
        ),
        migrations.RemoveField(
            model_name='twouserlocation',
            name='city_lon',
        ),
    ]
