# Generated by Django 3.2 on 2021-06-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocListPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('list', models.PositiveIntegerField(default=0, verbose_name='Фотоальбом')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Порядок отображения списка документов',
                'verbose_name_plural': 'Порядки отображения списков документов',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='GoodListPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('list', models.PositiveIntegerField(default=0, verbose_name='Фотоальбом')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Порядок отображения списка товаров',
                'verbose_name_plural': 'Порядки отображения списков товаров',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='PhotoListPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('list', models.PositiveIntegerField(default=0, verbose_name='Фотоальбом')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Порядок отображения фотоальбома',
                'verbose_name_plural': 'Порядки отображения фотоальбомов',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='PlayListPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('list', models.PositiveIntegerField(default=0, verbose_name='Фотоальбом')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Порядок отображения плейлиста',
                'verbose_name_plural': 'Порядки отображения плейлистов',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='PostListPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('list', models.PositiveIntegerField(default=0, verbose_name='Фотоальбом')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Порядок отображения списка записей',
                'verbose_name_plural': 'Порядки отображения списков записей',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='SurveyListPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('list', models.PositiveIntegerField(default=0, verbose_name='Фотоальбом')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Порядок отображения списка опросов',
                'verbose_name_plural': 'Порядки отображения списков опросов',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='VideoListPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('list', models.PositiveIntegerField(default=0, verbose_name='Фотоальбом')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Порядок отображения видеольбома',
                'verbose_name_plural': 'Порядки отображения видеоальбомов',
                'ordering': ['-position'],
            },
        ),
    ]
