# Generated by Django 2.2.5 on 2019-09-16 12:59

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190914_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='', upload_to='user/list', verbose_name='Аватар'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Биография'),
            preserve_default=False,
        ),
    ]
