# Generated by Django 3.2 on 2021-06-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_doclistposition_goodlistposition_photolistposition_playlistposition_postlistposition_surveylistposit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoListPosition',
            new_name='UserDocListPosition',
        ),
        migrations.RenameModel(
            old_name='DocListPosition',
            new_name='UserGoodListPosition',
        ),
        migrations.RenameModel(
            old_name='PhotoListPosition',
            new_name='UserPhotoListPosition',
        ),
        migrations.RenameModel(
            old_name='SurveyListPosition',
            new_name='UserPlayListPosition',
        ),
        migrations.RenameModel(
            old_name='PostListPosition',
            new_name='UserPostListPosition',
        ),
        migrations.RenameModel(
            old_name='GoodListPosition',
            new_name='UserSurveyListPosition',
        ),
        migrations.RenameModel(
            old_name='PlayListPosition',
            new_name='UserVideoListPosition',
        ),
        migrations.AlterModelOptions(
            name='userdoclistposition',
            options={'ordering': ['-position'], 'verbose_name': 'Порядок отображения списка документов', 'verbose_name_plural': 'Порядки отображения списков документов'},
        ),
        migrations.AlterModelOptions(
            name='usergoodlistposition',
            options={'ordering': ['-position'], 'verbose_name': 'Порядок отображения списка товаров', 'verbose_name_plural': 'Порядки отображения списков товаров'},
        ),
        migrations.AlterModelOptions(
            name='userplaylistposition',
            options={'ordering': ['-position'], 'verbose_name': 'Порядок отображения плейлиста', 'verbose_name_plural': 'Порядки отображения плейлистов'},
        ),
        migrations.AlterModelOptions(
            name='usersurveylistposition',
            options={'ordering': ['-position'], 'verbose_name': 'Порядок отображения списка опросов', 'verbose_name_plural': 'Порядки отображения списков опросов'},
        ),
        migrations.AlterModelOptions(
            name='uservideolistposition',
            options={'ordering': ['-position'], 'verbose_name': 'Порядок отображения видеольбома', 'verbose_name_plural': 'Порядки отображения видеоальбомов'},
        ),
    ]
