# Generated by Django 2.2.5 on 2019-11-11 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191111_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivatesettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_private', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
