# Generated by Django 3.2 on 2021-06-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210614_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpostlistposition',
            options={'ordering': ['position'], 'verbose_name': 'Порядок отображения списка записей', 'verbose_name_plural': 'Порядки отображения списков записей'},
        ),
    ]
