# Generated by Django 2.2.5 on 2019-11-13 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191111_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblock',
            name='blocked_user',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL, verbose_name='Кого блокирует'),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='blocker',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Кто блокирует'),
        ),
    ]
