# Generated by Django 2.2.5 on 2020-02-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200215_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserColorSettings',
        ),
    ]
