# Generated by Django 3.2 on 2021-06-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userpostlistposition_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpostlistposition',
            options={'ordering': ['position'], 'verbose_name': 'Порядок отображения списка записей', 'verbose_name_plural': 'Порядки отображения списков записей'},
        ),
    ]
