# Generated by Django 3.2 on 2021-06-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userpostlistposition_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpostlistposition',
            options={'ordering': ['-position'], 'verbose_name': 'Порядок отображения списка записей', 'verbose_name_plural': 'Порядки отображения списков записей'},
        ),
        migrations.AddField(
            model_name='userdoclistposition',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='1 - открыт, 0 - недоступен'),
        ),
        migrations.AddField(
            model_name='usergoodlistposition',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='1 - открыт, 0 - недоступен'),
        ),
        migrations.AddField(
            model_name='userplaylistposition',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='1 - открыт, 0 - недоступен'),
        ),
        migrations.AddField(
            model_name='userpostlistposition',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='1 - открыт, 0 - недоступен'),
        ),
        migrations.AddField(
            model_name='usersurveylistposition',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='1 - открыт, 0 - недоступен'),
        ),
        migrations.AddField(
            model_name='uservideolistposition',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='1 - открыт, 0 - недоступен'),
        ),
    ]
