# Generated by Django 2.2.5 on 2020-03-07 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usercolorsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoodNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о комментариях к записям')),
                ('comment_reply_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления об ответах на комментарии к записям')),
                ('comment_user_mention_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления об упоминаниях в комментариях к записям')),
                ('user_mention_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления об упоминаниях в записям')),
                ('repost_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о репостах записей')),
                ('like_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о лайках к записям')),
                ('dislike_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о дизлайках к записям')),
                ('comment_like_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о лайках на комментарии к записям')),
                ('comment_dislike_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о дизлайках на комментарии к записям')),
                ('comment_reply_like_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о лайках на ответы к комментариям')),
                ('comment_reply_dislike_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о дизлайках на ответы к комментариям')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_good_notify', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserItemNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о комментариях к записям')),
                ('comment_reply_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления об ответах на комментарии к записям')),
                ('comment_user_mention_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления об упоминаниях в комментариях к записям')),
                ('user_mention_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления об упоминаниях в записям')),
                ('repost_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о репостах записей')),
                ('like_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о лайках к записям')),
                ('dislike_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о дизлайках к записям')),
                ('comment_like_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о лайках на комментарии к записям')),
                ('comment_dislike_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о дизлайках на комментарии к записям')),
                ('comment_reply_like_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о лайках на ответы к комментариям')),
                ('comment_reply_dislike_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о дизлайках на ответы к комментариям')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_item_notify', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_request_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о заявках в друзья')),
                ('connection_confirmed_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о приеме заявки в друзья')),
                ('community_invite_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о приглашениях в сообщества')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_notify', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserPhotoNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о комментариях к записям')),
                ('comment_reply_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления об ответах на комментарии к записям')),
                ('comment_user_mention_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления об упоминаниях в комментариях к записям')),
                ('user_mention_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления об упоминаниях в записям')),
                ('repost_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о репостах записей')),
                ('like_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о лайках к записям')),
                ('dislike_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о дизлайках к записям')),
                ('comment_like_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о лайках на комментарии к записям')),
                ('comment_dislike_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о дизлайках на комментарии к записям')),
                ('comment_reply_like_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о лайках на ответы к комментариям')),
                ('comment_reply_dislike_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о дизлайках на ответы к комментариям')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_photo_notify', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserVideoNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о комментариях к записям')),
                ('comment_reply_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления об ответах на комментарии к записям')),
                ('comment_user_mention_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления об упоминаниях в комментариях к записям')),
                ('user_mention_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления об упоминаниях в записям')),
                ('repost_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о репостах записей')),
                ('like_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о лайках к записям')),
                ('dislike_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о дизлайках к записям')),
                ('comment_like_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о лайках на комментарии к записям')),
                ('comment_dislike_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о дизлайках на комментарии к записям')),
                ('comment_reply_like_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о лайках на ответы к комментариям')),
                ('comment_reply_dislike_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о дизлайках на ответы к комментариям')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_video_notify', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.RenameModel(
            old_name='UserPrivateSettings',
            new_name='UserItemPrivate',
        ),
        migrations.DeleteModel(
            name='UserNotificationsSettings',
        ),
    ]
