# Generated by Django 2.2.5 on 2020-03-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200307_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='followers_count_visible',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_global_moderator',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_superuser',
        ),
    ]
