# Generated by Django 2.2.5 on 2020-03-08 15:25

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200308_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoUserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip 1')),
                ('sity_ru', models.CharField(blank=True, max_length=100, verbose_name='Город по-русски')),
                ('sity_en', models.CharField(blank=True, max_length=100, verbose_name='Город по-английски')),
                ('region_ru', models.CharField(blank=True, max_length=100, verbose_name='Регион по-русски')),
                ('region_en', models.CharField(blank=True, max_length=100, verbose_name='Регион по-английски')),
                ('country_ru', models.CharField(blank=True, max_length=100, verbose_name='Страна по-русски')),
                ('country_en', models.CharField(blank=True, max_length=100, verbose_name='Страна по-английски')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_location_2', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Местоположения и ip пользователей',
                'verbose_name': 'Местоположение и ip пользователя',
            },
        ),
        migrations.CreateModel(
            name='ThreeUserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip 1')),
                ('sity_ru', models.CharField(blank=True, max_length=100, verbose_name='Город по-русски')),
                ('sity_en', models.CharField(blank=True, max_length=100, verbose_name='Город по-английски')),
                ('region_ru', models.CharField(blank=True, max_length=100, verbose_name='Регион по-русски')),
                ('region_en', models.CharField(blank=True, max_length=100, verbose_name='Регион по-английски')),
                ('country_ru', models.CharField(blank=True, max_length=100, verbose_name='Страна по-русски')),
                ('country_en', models.CharField(blank=True, max_length=100, verbose_name='Страна по-английски')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_location_3', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Местоположения и ip пользователей',
                'verbose_name': 'Местоположение и ip пользователя',
            },
        ),
        migrations.CreateModel(
            name='OneUserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip 1')),
                ('sity_ru', models.CharField(blank=True, max_length=100, verbose_name='Город по-русски')),
                ('sity_en', models.CharField(blank=True, max_length=100, verbose_name='Город по-английски')),
                ('region_ru', models.CharField(blank=True, max_length=100, verbose_name='Регион по-русски')),
                ('region_en', models.CharField(blank=True, max_length=100, verbose_name='Регион по-английски')),
                ('country_ru', models.CharField(blank=True, max_length=100, verbose_name='Страна по-русски')),
                ('country_en', models.CharField(blank=True, max_length=100, verbose_name='Страна по-английски')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Местоположения и ip пользователей',
                'verbose_name': 'Местоположение и ip пользователя',
            },
        ),
        migrations.AddIndex(
            model_name='twouserlocation',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='users_twous_created_ed152d_brin'),
        ),
        migrations.AddIndex(
            model_name='threeuserlocation',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='users_three_created_1682f1_brin'),
        ),
        migrations.AddIndex(
            model_name='oneuserlocation',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='users_oneus_created_5e5d14_brin'),
        ),
    ]
