# Generated by Django 2.2.5 on 2020-03-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200308_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_1', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip 1')),
                ('ip_2', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip 2')),
                ('ip_3', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip 3')),
            ],
        ),
        migrations.RemoveField(
            model_name='oneuserlocation',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='threeuserlocation',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='twouserlocation',
            name='ip',
        ),
    ]
