# Generated by Django 2.2.5 on 2020-03-08 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200308_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipuser',
            options={'verbose_name': 'ip пользователя', 'verbose_name_plural': 'ip пользователей'},
        ),
        migrations.AlterModelOptions(
            name='threeuserlocation',
            options={'verbose_name': 'Местоположение пользователя', 'verbose_name_plural': 'Местоположения пользователей'},
        ),
        migrations.AlterModelOptions(
            name='twouserlocation',
            options={'verbose_name': 'Местоположение пользователя', 'verbose_name_plural': 'Местоположения пользователей'},
        ),
        migrations.AddField(
            model_name='ipuser',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_ip', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
