# Generated by Django 3.2 on 2021-07-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprivate_can_see_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommunityCanSeeExcludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.PositiveIntegerField(default=0, verbose_name='id назначателя')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='id пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='UserCommunityCanSeeIncludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.PositiveIntegerField(default=0, verbose_name='id назначателя')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='id пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='UserDocAddExcludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.PositiveIntegerField(default=0, verbose_name='id назначателя')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='id пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='UserDocAddIncludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.PositiveIntegerField(default=0, verbose_name='id назначателя')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='id пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='UserDocCanSeeExcludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.PositiveIntegerField(default=0, verbose_name='id назначателя')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='id пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='UserDocCanSeeIncludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.PositiveIntegerField(default=0, verbose_name='id назначателя')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='id пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='UserFriendCanSeeExcludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.PositiveIntegerField(default=0, verbose_name='id назначателя')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='id пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='UserFriendCanSeeIncludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.PositiveIntegerField(default=0, verbose_name='id назначателя')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='id пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessageCanSeeExcludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.PositiveIntegerField(default=0, verbose_name='id назначателя')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='id пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessageCanSeeIncludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.PositiveIntegerField(default=0, verbose_name='id назначателя')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='id пользователя')),
            ],
        ),
        migrations.RenameField(
            model_name='userprivate',
            old_name='can_see_message',
            new_name='can_receive_message',
        ),
        migrations.RenameField(
            model_name='userprivate',
            old_name='can_see_boards',
            new_name='can_see_board',
        ),
        migrations.RenameField(
            model_name='userprivate',
            old_name='can_see_friends',
            new_name='can_see_friend',
        ),
        migrations.RenameField(
            model_name='userprivate',
            old_name='can_see_workspaces',
            new_name='can_see_workspace',
        ),
    ]
