# Generated by Django 3.2 on 2021-07-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210721_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_doc',
            field=models.CharField(choices=[('AC', 'Все пользователи'), ('F', 'Друзья'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('FB', 'Друзья, кроме'), ('SF', 'Некоторые друзья')], default='AC', max_length=2, verbose_name='Кто видит документы'),
        ),
        migrations.AlterField(
            model_name='userprivateplanner',
            name='add_comments',
            field=models.CharField(choices=[('AC', 'Все пользователи'), ('M', 'Участники пространства или доски'), ('F', 'Друзья'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('FB', 'Друзья, кроме'), ('SF', 'Некоторые друзья'), ('MB', 'Участники, кроме'), ('SM', 'Некоторые участники')], default='M', max_length=2, verbose_name='Кто добавляет комментарии'),
        ),
    ]
