# Generated by Django 2.2.5 on 2020-03-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200308_1636'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='twouserlocation',
            name='users_twous_created_ed152d_brin',
        ),
        migrations.RemoveIndex(
            model_name='oneuserlocation',
            name='users_oneus_created_5e5d14_brin',
        ),
        migrations.RemoveIndex(
            model_name='threeuserlocation',
            name='users_three_created_1682f1_brin',
        ),
        migrations.RemoveField(
            model_name='oneuserlocation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='threeuserlocation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='twouserlocation',
            name='created',
        ),
    ]
