# Generated by Django 3.2 on 2021-07-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210722_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprivate',
            name='can_see_board',
        ),
        migrations.RemoveField(
            model_name='userprivate',
            name='can_see_workspace',
        ),
        migrations.AddField(
            model_name='userprivate',
            name='can_see_planner_board',
            field=models.CharField(choices=[('AC', 'Все пользователи'), ('M', 'Участники пространства или доски'), ('F', 'Друзья'), ('FM', 'Друзья и участники'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('FB', 'Друзья, кроме'), ('SF', 'Некоторые друзья'), ('MB', 'Участники, кроме'), ('SM', 'Некоторые участники')], default='M', max_length=2, verbose_name='Кто видит доски планирования'),
        ),
        migrations.AddField(
            model_name='userprivate',
            name='can_see_planner_column',
            field=models.CharField(choices=[('AC', 'Все пользователи'), ('M', 'Участники пространства или доски'), ('F', 'Друзья'), ('FM', 'Друзья и участники'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('FB', 'Друзья, кроме'), ('SF', 'Некоторые друзья'), ('MB', 'Участники, кроме'), ('SM', 'Некоторые участники')], default='M', max_length=2, verbose_name='Кто видит колонки досок планирования'),
        ),
        migrations.AddField(
            model_name='userprivate',
            name='can_see_planner_workspace',
            field=models.CharField(choices=[('AC', 'Все пользователи'), ('M', 'Участники пространства или доски'), ('F', 'Друзья'), ('FM', 'Друзья и участники'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('FB', 'Друзья, кроме'), ('SF', 'Некоторые друзья'), ('MB', 'Участники, кроме'), ('SM', 'Некоторые участники')], default='M', max_length=2, verbose_name='Кто видит рабочие пространства и весь раздел планирования'),
        ),
        migrations.AlterField(
            model_name='userprivateplanner',
            name='add_comments',
            field=models.CharField(choices=[('AC', 'Все пользователи'), ('M', 'Участники пространства или доски'), ('F', 'Друзья'), ('FM', 'Друзья и участники'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('FB', 'Друзья, кроме'), ('SF', 'Некоторые друзья'), ('MB', 'Участники, кроме'), ('SM', 'Некоторые участники')], default='M', max_length=2, verbose_name='Кто добавляет комментарии'),
        ),
        migrations.AlterField(
            model_name='userprivateplanner',
            name='can_see_comments',
            field=models.CharField(choices=[('AC', 'Все пользователи'), ('M', 'Участники пространства или доски'), ('F', 'Друзья'), ('FM', 'Друзья и участники'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('FB', 'Друзья, кроме'), ('SF', 'Некоторые друзья'), ('MB', 'Участники, кроме'), ('SM', 'Некоторые участники')], default='M', max_length=2, verbose_name='Кто видит комментарии'),
        ),
    ]
