# Generated by Django 2.2.5 on 2020-03-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200308_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oneuserlocation',
            options={'verbose_name': 'Местоположение 1', 'verbose_name_plural': 'Местоположения 1'},
        ),
        migrations.AlterModelOptions(
            name='threeuserlocation',
            options={'verbose_name': 'Местоположение 3', 'verbose_name_plural': 'Местоположения 3'},
        ),
        migrations.AlterModelOptions(
            name='twouserlocation',
            options={'verbose_name': 'Местоположение 2', 'verbose_name_plural': 'Местоположения 2'},
        ),
        migrations.AlterIndexTogether(
            name='ipuser',
            index_together={('id', 'user')},
        ),
        migrations.AlterIndexTogether(
            name='oneuserlocation',
            index_together={('id', 'user')},
        ),
        migrations.AlterIndexTogether(
            name='threeuserlocation',
            index_together={('id', 'user')},
        ),
        migrations.AlterIndexTogether(
            name='twouserlocation',
            index_together={('id', 'user')},
        ),
    ]
