# Generated by Django 3.2 on 2021-09-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210722_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprivate',
            name='can_receive_message',
        ),
        migrations.RemoveField(
            model_name='userprivate',
            name='can_see_planner_board',
        ),
        migrations.RemoveField(
            model_name='userprivate',
            name='can_see_planner_column',
        ),
        migrations.RemoveField(
            model_name='userprivate',
            name='can_see_planner_workspace',
        ),
        migrations.AddField(
            model_name='userprivate',
            name='can_add_in_chat',
            field=models.CharField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (9, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто добавляет в беседы'),
        ),
        migrations.AddField(
            model_name='userprivate',
            name='can_see_info',
            field=models.CharField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (9, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто видит информацию'),
        ),
        migrations.AddField(
            model_name='userprivate',
            name='can_see_planner',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Участники пространства или доски'), (2, 'Друзья'), (4, 'Друзья и участники'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (9, 'Некоторые друзья'), (8, 'Участники, кроме'), (10, 'Некоторые участники')], default=3, max_length=2, verbose_name='Кто видит раздел планирования'),
        ),
        migrations.AddField(
            model_name='userprivate',
            name='can_send_message',
            field=models.CharField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (9, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_community',
            field=models.CharField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (9, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто видит сообщества'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_doc',
            field=models.CharField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (9, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто видит документы'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_friend',
            field=models.CharField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (9, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто видит друзей'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_good',
            field=models.CharField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (9, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_music',
            field=models.CharField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (9, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_photo',
            field=models.CharField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (9, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_post',
            field=models.CharField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (9, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто видит стену'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_video',
            field=models.CharField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (9, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
    ]
