# Generated by Django 2.2.5 on 2020-03-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200308_1847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserItemPrivate',
            new_name='UserPrivate',
        ),
    ]
