# Generated by Django 2.2.5 on 2020-03-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200308_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneuserlocation',
            name='city_lat',
            field=models.FloatField(blank=True, default=0, verbose_name='Ширина города'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oneuserlocation',
            name='city_lon',
            field=models.FloatField(blank=True, default=0, verbose_name='Долгота города'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threeuserlocation',
            name='city_lat',
            field=models.FloatField(blank=True, default=0, verbose_name='Ширина города'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threeuserlocation',
            name='city_lon',
            field=models.FloatField(blank=True, default=0, verbose_name='Долгота города'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twouserlocation',
            name='city_lat',
            field=models.FloatField(blank=True, default=0, verbose_name='Ширина города'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twouserlocation',
            name='city_lon',
            field=models.FloatField(blank=True, default=0, verbose_name='Долгота города'),
            preserve_default=False,
        ),
    ]
