# Generated by Django 2.2.5 on 2020-03-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200309_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneuserlocation',
            name='city_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина города'),
        ),
        migrations.AlterField(
            model_name='oneuserlocation',
            name='city_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота города'),
        ),
        migrations.AlterField(
            model_name='threeuserlocation',
            name='city_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина города'),
        ),
        migrations.AlterField(
            model_name='threeuserlocation',
            name='city_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота города'),
        ),
        migrations.AlterField(
            model_name='twouserlocation',
            name='city_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина города'),
        ),
        migrations.AlterField(
            model_name='twouserlocation',
            name='city_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота города'),
        ),
    ]
