# Generated by Django 3.2 on 2021-10-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20211006_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPostListPosition',
            new_name='UserPostsListPosition',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, max_length=5000, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Деятельность'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_books',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Любимые книги'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_films',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Любимые фильмы'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_game',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Любимые игры'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_music',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Любимая музыка'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_quotes',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Любимые цитаты'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Интересы'),
        ),
    ]
