# Generated by Django 3.2 on 2021-10-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20211017_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDocListPosition',
            new_name='UserDocsListPosition',
        ),
    ]
