# Generated by Django 2.2.5 on 2020-03-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200309_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Телефон'),
        ),
    ]
