# Generated by Django 3.2 on 2021-10-21 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_userdoclistposition_userdocslistposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(default=0, verbose_name='Общая высота в метрах'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Общее проведенное время'),
        ),
    ]
