# Generated by Django 3.2 on 2021-12-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20211021_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPopulateFriend',
        ),
    ]
