# Generated by Django 3.2 on 2021-12-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20211209_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListUC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Основной список'), (2, 'Пользовательский'), (0, 'Нет значения')], default=0, verbose_name='Рекомендуемое сообщество')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.PositiveIntegerField(default=0, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='NotifyUC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.PositiveIntegerField(default=0, verbose_name='Кто получает')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('community', models.PositiveIntegerField(default=0, verbose_name='Сообщество')),
                ('mute', models.BooleanField(default=False, verbose_name='Источник скрыт')),
                ('sleep', models.DateTimeField(blank=True, null=True, verbose_name='Не показывать до...')),
                ('list', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.listuc', verbose_name='Список')),
            ],
            options={
                'verbose_name': 'Друзья/сообщества и подписки',
                'verbose_name_plural': 'Друзья/сообщества и подписки',
            },
        ),
        migrations.CreateModel(
            name='NewsUC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.PositiveIntegerField(default=0, verbose_name='Кто получает')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('community', models.PositiveIntegerField(default=0, verbose_name='Сообщество')),
                ('mute', models.BooleanField(default=False, verbose_name='Источник скрыт')),
                ('sleep', models.DateTimeField(blank=True, null=True, verbose_name='Не показывать до...')),
                ('list', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.listuc', verbose_name='Список')),
            ],
            options={
                'verbose_name': 'Друзья/сообщества и подписки',
                'verbose_name_plural': 'Друзья/сообщества и подписки',
            },
        ),
        migrations.CreateModel(
            name='FeaturedUC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.PositiveIntegerField(default=0, verbose_name='Кто получает')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Рекомендуемый друг')),
                ('community', models.PositiveIntegerField(default=0, verbose_name='Рекомендуемое сообщество')),
                ('mute', models.BooleanField(default=False, verbose_name='Источник скрыт')),
                ('sleep', models.DateTimeField(blank=True, null=True, verbose_name='Не показывать до...')),
                ('list', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.listuc', verbose_name='Список')),
            ],
            options={
                'verbose_name': 'Рекомендованные друзья',
                'verbose_name_plural': 'Рекомендованные друзья',
            },
        ),
    ]
