# Generated by Django 3.2 on 2021-12-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_featureduc_listuc_newsuc_notifyuc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFeaturedFriend',
        ),
    ]
