# Generated by Django 3.2 on 2021-12-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_delete_userfeaturedfriend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureduc',
            options={'verbose_name': 'Источник рекомендаций', 'verbose_name_plural': 'Источники рекомендаций'},
        ),
        migrations.AlterModelOptions(
            name='newsuc',
            options={'verbose_name': 'Источник новостей', 'verbose_name_plural': 'Источники новостей'},
        ),
        migrations.AlterModelOptions(
            name='notifyuc',
            options={'verbose_name': 'Источник уведомлений', 'verbose_name_plural': 'Источники уведомлений'},
        ),
    ]
