# Generated by Django 3.2 on 2021-12-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20211211_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePrivate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_private', serialize=False, to='users.user', verbose_name='Пользователь')),
                ('can_see_community', models.PositiveSmallIntegerField(choices=[('AC', 'Все пользователи'), ('F', 'Друзья'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('AB', 'Друзья, кроме'), ('SF', 'Некоторые друзья')], default=1, verbose_name='Кто видит сообщества')),
                ('can_see_info', models.PositiveSmallIntegerField(choices=[('AC', 'Все пользователи'), ('F', 'Друзья'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('AB', 'Друзья, кроме'), ('SF', 'Некоторые друзья')], default=1, verbose_name='Кто видит информацию')),
                ('can_see_friend', models.PositiveSmallIntegerField(choices=[('AC', 'Все пользователи'), ('F', 'Друзья'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('AB', 'Друзья, кроме'), ('SF', 'Некоторые друзья')], default=1, verbose_name='Кто видит друзей')),
                ('can_send_message', models.PositiveSmallIntegerField(choices=[('AC', 'Все пользователи'), ('F', 'Друзья'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('AB', 'Друзья, кроме'), ('SF', 'Некоторые друзья')], default=1, verbose_name='Кто пишет сообщения')),
                ('can_add_in_chat', models.PositiveSmallIntegerField(choices=[('AC', 'Все пользователи'), ('F', 'Друзья'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('AB', 'Друзья, кроме'), ('SF', 'Некоторые друзья')], default=1, verbose_name='Кто добавляет в беседы')),
                ('can_see_post', models.PositiveSmallIntegerField(choices=[('AC', 'Все пользователи'), ('F', 'Друзья'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('AB', 'Друзья, кроме'), ('SF', 'Некоторые друзья')], default=1, verbose_name='Кто видит стену')),
                ('can_see_photo', models.PositiveSmallIntegerField(choices=[('AC', 'Все пользователи'), ('F', 'Друзья'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('AB', 'Друзья, кроме'), ('SF', 'Некоторые друзья')], default=1, verbose_name='Кто пишет сообщения')),
                ('can_see_good', models.PositiveSmallIntegerField(choices=[('AC', 'Все пользователи'), ('F', 'Друзья'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('AB', 'Друзья, кроме'), ('SF', 'Некоторые друзья')], default=1, verbose_name='Кто пишет сообщения')),
                ('can_see_video', models.PositiveSmallIntegerField(choices=[('AC', 'Все пользователи'), ('F', 'Друзья'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('AB', 'Друзья, кроме'), ('SF', 'Некоторые друзья')], default=1, verbose_name='Кто пишет сообщения')),
                ('can_see_music', models.PositiveSmallIntegerField(choices=[('AC', 'Все пользователи'), ('F', 'Друзья'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('AB', 'Друзья, кроме'), ('SF', 'Некоторые друзья')], default=1, verbose_name='Кто пишет сообщения')),
                ('can_see_planner', models.PositiveSmallIntegerField(choices=[('AC', 'Все пользователи'), ('ME', 'Участники пространства или доски'), ('F', 'Друзья'), ('FM', 'Друзья и участники'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('AB', 'Друзья, кроме'), ('SF', 'Некоторые друзья'), ('MB', 'Участники, кроме'), ('SM', 'Некоторые участники')], default=2, verbose_name='Кто видит раздел планирования')),
                ('can_see_doc', models.PositiveSmallIntegerField(choices=[('AC', 'Все пользователи'), ('F', 'Друзья'), ('EO', 'Друзья и друзья друзей'), ('Y', 'Только я'), ('AB', 'Друзья, кроме'), ('SF', 'Некоторые друзья')], default=1, verbose_name='Кто видит документы')),
            ],
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_add_in_chat',
            field=models.CharField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (8, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто добавляет в беседы'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_community',
            field=models.CharField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (8, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто видит сообщества'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_doc',
            field=models.CharField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (8, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто видит документы'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_friend',
            field=models.CharField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (8, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто видит друзей'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_good',
            field=models.CharField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (8, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_info',
            field=models.CharField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (8, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто видит информацию'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_music',
            field=models.CharField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (8, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_photo',
            field=models.CharField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (8, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_planner',
            field=models.CharField(choices=[(1, 'Все пользователи'), (2, 'Участники пространства или доски'), (4, 'Друзья'), (3, 'Друзья и участники'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (8, 'Некоторые друзья'), (9, 'Участники, кроме'), (10, 'Некоторые участники')], default=2, max_length=2, verbose_name='Кто видит раздел планирования'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_post',
            field=models.CharField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (8, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто видит стену'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_see_video',
            field=models.CharField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (8, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='userprivate',
            name='can_send_message',
            field=models.CharField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (7, 'Друзья, кроме'), (8, 'Некоторые друзья')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
    ]
