# Generated by Django 2.2.5 on 2020-03-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200319_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='are_guidelines_accepted',
            new_name='is_phone_accepted',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=17, verbose_name='Телефон'),
        ),
    ]
