# Generated by Django 2.2.5 on 2020-03-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20200320_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneuserlocation',
            name='phone',
            field=models.CharField(blank=True, max_length=5, verbose_name='Начало номера'),
        ),
        migrations.AddField(
            model_name='threeuserlocation',
            name='phone',
            field=models.CharField(blank=True, max_length=5, verbose_name='Начало номера'),
        ),
        migrations.AddField(
            model_name='twouserlocation',
            name='phone',
            field=models.CharField(blank=True, max_length=5, verbose_name='Начало номера'),
        ),
    ]
