# Generated by Django 3.2 on 2021-12-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20211214_1522'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='featureduc',
            constraint=models.UniqueConstraint(fields=('owner', 'user', 'community'), name='feature_uc'),
        ),
    ]
