# Generated by Django 3.2 on 2021-12-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_featureduc_feature_uc'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='newsuc',
            constraint=models.UniqueConstraint(fields=('owner', 'user', 'community'), name='news_uc'),
        ),
        migrations.AddConstraint(
            model_name='notifyuc',
            constraint=models.UniqueConstraint(fields=('owner', 'user', 'community'), name='notify_uc'),
        ),
    ]
