# Generated by Django 3.2 on 2021-12-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20211221_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileprivate',
            name='can_see_good',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (17, 'Друзья, кроме'), (18, 'Некоторые друзья')], default=1, verbose_name='Кто видит товары'),
        ),
        migrations.AlterField(
            model_name='profileprivate',
            name='can_see_music',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (17, 'Друзья, кроме'), (18, 'Некоторые друзья')], default=1, verbose_name='Кто видит аудиозаписи'),
        ),
        migrations.AlterField(
            model_name='profileprivate',
            name='can_see_photo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (17, 'Друзья, кроме'), (18, 'Некоторые друзья')], default=1, verbose_name='Кто видит фотографии'),
        ),
        migrations.AlterField(
            model_name='profileprivate',
            name='can_see_planner',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (17, 'Друзья, кроме'), (18, 'Некоторые друзья')], default=2, verbose_name='Кто видит раздел планирования'),
        ),
        migrations.AlterField(
            model_name='profileprivate',
            name='can_see_post',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (17, 'Друзья, кроме'), (18, 'Некоторые друзья')], default=1, verbose_name='Кто видит записи'),
        ),
        migrations.AlterField(
            model_name='profileprivate',
            name='can_see_video',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (17, 'Друзья, кроме'), (18, 'Некоторые друзья')], default=1, verbose_name='Кто видит видеозаписи'),
        ),
    ]
