# Generated by Django 3.2 on 2021-12-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20211221_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileprivate',
            name='can_see_planner',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (17, 'Друзья, кроме'), (18, 'Некоторые друзья')], default=5, verbose_name='Кто видит раздел планирования'),
        ),
    ]
