# Generated by Django 3.2 on 2021-12-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_profileprivate_can_see_planner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileprivate',
            name='can_add_in_chat',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (4, 'Друзья'), (5, 'Друзья и друзья друзей'), (6, 'Только я'), (17, 'Друзья, кроме'), (18, 'Некоторые друзья')], default=1, verbose_name='Кто приглашает в беседы'),
        ),
    ]
