# Generated by Django 2.2.5 on 2020-01-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoundParsing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('artwork_url', models.URLField(blank=True, max_length=255)),
                ('bpm', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=255)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('permalink', models.CharField(blank=True, max_length=255)),
                ('permalink_url', models.URLField(blank=True, max_length=255)),
                ('release', models.CharField(blank=True, max_length=255)),
                ('release_day', models.CharField(blank=True, max_length=255)),
                ('release_month', models.CharField(blank=True, max_length=255)),
                ('release_year', models.CharField(blank=True, max_length=255)),
                ('stream_url', models.URLField(blank=True, max_length=255)),
                ('streamable', models.BooleanField(default=True)),
                ('tag_list', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('uri', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
