# Generated by Django 3.2 on 2021-04-29 19:15

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import music.helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundGenres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
            },
        ),
        migrations.CreateModel(
            name='SoundList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('PRI', 'Приватный'), ('MAN', 'Созданный персоналом'), ('TPRO', 'Обработка'), ('TDEL', 'Удалённый'), ('TDELP', 'Удалённый приватный'), ('TDELM', 'Удалённый менеджерский'), ('TCLO', 'Закрытый менеджером'), ('TCLOP', 'Закрытый приватный'), ('TCLOM', 'Закрытый основной'), ('TCLOMA', 'Закрытый менеджерский')], default='TPRO', max_length=6, verbose_name='Тип списка')),
                ('order', models.PositiveIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=music.helpers.upload_to_music_directory)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('creator', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_playlist', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'плейлист',
                'verbose_name_plural': 'плейлисты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SoundSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('RS', 'русские исполнители'), ('AS', 'английские исполнители'), ('NS', 'исполнители по цифрам')], default='AS', max_length=5, verbose_name='Язык исполнителя')),
            ],
            options={
                'verbose_name': 'буква поиска музыки',
                'verbose_name_plural': 'буквы поиска музыки',
            },
        ),
        migrations.CreateModel(
            name='SoundTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_papa', to='music.soundsymbol', verbose_name='Буква')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='UserTempSoundList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_field', to='music.soundgenres', verbose_name='Связь на жанр')),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_field', to='music.soundlist', verbose_name='Связь на плейлист человека или сообщества')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_field', to='music.soundtags', verbose_name='Связь на тег')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_of_field', to=settings.AUTH_USER_MODEL, verbose_name='Слушатель')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=music.helpers.upload_to_music_directory)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PRO', 'Обработка'), ('PUB', 'Опубликовано'), ('TDEL', 'Удалено'), ('PRI', 'Приватно'), ('TCLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('TDELP', 'Удалённый приватный'), ('TDELM', 'Удалённый менеджерский'), ('TCLOP', 'Закрытый приватный'), ('TCLOM', 'Закрытый менеджерский')], default='PRO', max_length=5)),
                ('file', models.FileField(blank=True, upload_to=music.helpers.upload_to_music_directory, validators=[music.helpers.validate_file_extension], verbose_name='Аудиозапись')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Кол-во дизлайков')),
                ('reposts', models.PositiveIntegerField(default=0, verbose_name='Кол-во репостов')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_genre', to='music.soundgenres', verbose_name='Жанр трека')),
                ('list', models.ManyToManyField(blank='True', related_name='playlist', to='music.SoundList')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_tag', to='music.soundtags', verbose_name='Буква')),
            ],
            options={
                'verbose_name': 'спарсенные треки',
                'verbose_name_plural': 'спарсенные треки',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='music',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='music_music_created_577adb_brin'),
        ),
    ]
