# Generated by Django 2.2.5 on 2020-01-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200102_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundparsing',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='soundparsing',
            name='description',
        ),
        migrations.AddField(
            model_name='soundparsing',
            name='isrc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='soundparsing',
            name='user_avatar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='soundparsing',
            name='user_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
