# Generated by Django 2.2.16 on 2020-09-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200906_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundcloudparsing',
            options={'ordering': ['-created_at'], 'verbose_name': 'спарсенные треки', 'verbose_name_plural': 'спарсенные треки'},
        ),
    ]
