# Generated by Django 3.1 on 2020-08-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200825_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundcloudparsing',
            name='good_comment',
        ),
        migrations.RemoveField(
            model_name='soundcloudparsing',
            name='item',
        ),
        migrations.RemoveField(
            model_name='soundcloudparsing',
            name='item_comment',
        ),
        migrations.RemoveField(
            model_name='soundcloudparsing',
            name='message',
        ),
        migrations.RemoveField(
            model_name='soundcloudparsing',
            name='photo_comment',
        ),
        migrations.RemoveField(
            model_name='soundcloudparsing',
            name='video_comment',
        ),
        migrations.RemoveField(
            model_name='soundlist',
            name='community',
        ),
        migrations.RemoveField(
            model_name='soundlist',
            name='post',
        ),
    ]
