# Generated by Django 2.2.16 on 2020-09-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_message_post'),
        ('music', '0003_auto_20200922_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundlist',
            name='message',
            field=models.ManyToManyField(blank=True, related_name='message_soundlist', to='chat.Message'),
        ),
    ]
