# Generated by Django 3.2 on 2021-05-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210430_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='dislikes',
            new_name='dislike',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='likes',
            new_name='like',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='reposts',
            new_name='repost',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='views',
            new_name='view',
        ),
    ]
