# Generated by Django 2.2.5 on 2020-01-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200102_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soundparsing',
            old_name='user_avatar',
            new_name='label_name',
        ),
        migrations.RemoveField(
            model_name='soundparsing',
            name='user_name',
        ),
    ]
