# Generated by Django 2.2.16 on 2020-09-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_soundlist_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soundcloudparsing',
            old_name='item',
            new_name='post',
        ),
    ]
