# Generated by Django 2.2.5 on 2020-01-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20200102_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soundparsing',
            old_name='isrc',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='soundparsing',
            name='release',
        ),
        migrations.RemoveField(
            model_name='soundparsing',
            name='tag_list',
        ),
    ]
