# Generated by Django 3.2 on 2021-06-13 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20210613_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='list',
        ),
        migrations.AddField(
            model_name='music',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist', to='music.soundlist'),
        ),
    ]
