# Generated by Django 2.2.5 on 2020-01-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200102_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='SounGenres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='soundparsing',
            name='label_name',
        ),
        migrations.RemoveField(
            model_name='soundparsing',
            name='permalink_url',
        ),
        migrations.RemoveField(
            model_name='soundparsing',
            name='user',
        ),
        migrations.AlterField(
            model_name='soundparsing',
            name='genre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='music.SounGenres', verbose_name='Жанр трека'),
            preserve_default=False,
        ),
    ]
