# Generated by Django 2.2.5 on 2020-01-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20200103_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('autoplay', models.BooleanField(default=False)),
                ('track', models.ManyToManyField(related_name='players', to='music.SoundParsing')),
            ],
        ),
    ]
