# Generated by Django 2.2.5 on 2020-01-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundparsing',
            name='release_day',
        ),
        migrations.RemoveField(
            model_name='soundparsing',
            name='release_month',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='track',
            field=models.ManyToManyField(blank='True', related_name='players', to='music.SoundParsing'),
        ),
    ]
