# Generated by Django 3.2 on 2021-06-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20210614_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-order'], 'verbose_name': 'спарсенные треки', 'verbose_name_plural': 'спарсенные треки'},
        ),
    ]
