# Generated by Django 2.2.5 on 2020-01-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20200103_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundparsing',
            name='permalink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soundparsing',
            name='stream_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
