# Generated by Django 3.2 on 2021-09-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_alter_soundlist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundlist',
            name='can_see_item',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья/подписчики'), (3, 'Друзья,друзья друзей/None'), (4, 'Только я/админы'), (5, 'Друзья/подписчики, кроме'), (6, 'Некоторые друзья/подписчики')], default=1, verbose_name='Кто видит записи'),
        ),
        migrations.AddField(
            model_name='soundlist',
            name='create_copy',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья/подписчики'), (3, 'Друзья,друзья друзей/None'), (4, 'Только я/админы'), (5, 'Друзья/подписчики, кроме'), (6, 'Некоторые друзья/подписчики')], default=1, verbose_name='Кто может копировать'),
        ),
        migrations.AddField(
            model_name='soundlist',
            name='create_item',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья/подписчики'), (3, 'Друзья,друзья друзей/None'), (4, 'Только я/админы'), (5, 'Друзья/подписчики, кроме'), (6, 'Некоторые друзья/подписчики')], default=4, verbose_name='Кто создает записи и потом с этими документами работает'),
        ),
    ]
