# Generated by Django 2.2.5 on 2020-01-05 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20200103_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'буква',
                'verbose_name_plural': 'буквы',
            },
        ),
        migrations.RenameModel(
            old_name='Playlist',
            new_name='SoundList',
        ),
        migrations.AlterModelOptions(
            name='soundlist',
            options={'verbose_name': 'список', 'verbose_name_plural': 'списки'},
        ),
        migrations.AlterModelOptions(
            name='soundparsing',
            options={'ordering': ('-created_at',), 'verbose_name': 'спарсенные треки', 'verbose_name_plural': 'спарсенные треки'},
        ),
        migrations.AlterModelOptions(
            name='soungenres',
            options={'verbose_name': 'жанр', 'verbose_name_plural': 'жанры'},
        ),
        migrations.RemoveField(
            model_name='soundparsing',
            name='bpm',
        ),
        migrations.RemoveField(
            model_name='soundparsing',
            name='streamable',
        ),
        migrations.CreateModel(
            name='SoundTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.SoundSymbol', verbose_name='Буква')),
            ],
            options={
                'verbose_name': 'тег поиска',
                'verbose_name_plural': 'теги поиска',
            },
        ),
        migrations.AddField(
            model_name='soundparsing',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='music.SoundTags', verbose_name='Буква'),
            preserve_default=False,
        ),
    ]
