# Generated by Django 2.2.5 on 2020-01-05 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20200105_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundtagslist',
            name='autoplay',
        ),
        migrations.RemoveField(
            model_name='soundtagslist',
            name='tag',
        ),
        migrations.AddField(
            model_name='soundtagslist',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soundtagslist',
            name='symbol',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='music.SoundSymbol', verbose_name='Буква'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='soundparsing',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.SoundTagsList', verbose_name='Буква'),
        ),
        migrations.DeleteModel(
            name='SoundTags',
        ),
    ]
