# Generated by Django 2.2.5 on 2020-01-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20200105_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SounGenres',
            new_name='SoundGenres',
        ),
    ]
