# Generated by Django 3.2 on 2021-10-30 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import music.helpers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0020_community_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0017_auto_20211022_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTempSoundList',
            new_name='UserTempMusicList',
        ),
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('MAN', 'Созданный персоналом'), ('_DEL', 'Удалённый'), ('_DELM', 'Удалённый менеджерский'), ('_CLO', 'Закрытый менеджером'), ('_CLOM', 'Закрытый основной'), ('_CLOMA', 'Закрытый менеджерский')], max_length=6, verbose_name='Тип списка')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=music.helpers.upload_to_music_directory)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('count', models.PositiveIntegerField(default=0)),
                ('can_see_el', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=1, verbose_name='Кто видит записи')),
                ('create_el', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=7, verbose_name='Кто создает записи и потом с этими документами работает')),
                ('copy_el', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=1, verbose_name='Кто может копировать')),
                ('is_music_list', models.BooleanField(default=True)),
                ('communities', models.ManyToManyField(blank=True, related_name='_music_musiclist_communities_+', to='communities.Community')),
                ('community', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_playlist', to='communities.community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_playlist', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('users', models.ManyToManyField(blank=True, related_name='_music_musiclist_users_+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'плейлист',
                'verbose_name_plural': 'плейлисты',
            },
        ),
        migrations.AlterField(
            model_name='music',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist', to='music.musiclist'),
        ),
        migrations.AlterField(
            model_name='usertempmusiclist',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_field', to='music.musiclist', verbose_name='Связь на плейлист человека или сообщества'),
        ),
        migrations.DeleteModel(
            name='SoundList',
        ),
    ]
