# Generated by Django 2.2.5 on 2020-01-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20200105_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundsymbol',
            name='type',
            field=models.CharField(choices=[('RS', 'русские исполнители'), ('AS', 'английские исполнители'), ('NS', 'исполнители по цифрам')], default='AS', max_length=5, verbose_name='Язык исполнителя'),
        ),
    ]
