# Generated by Django 3.2 on 2021-10-30 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20211030_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='description',
        ),
        migrations.RemoveField(
            model_name='music',
            name='uri',
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_genre', to='music.soundgenres', verbose_name='Жанр трека'),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
