# Generated by Django 2.2.5 on 2020-01-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_soundsymbol_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundtags',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='soundtags',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_papa', to='music.SoundSymbol', verbose_name='Буква'),
        ),
    ]
