# Generated by Django 3.2 on 2021-12-07 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0020_auto_20211030_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicListPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_see_item', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто видит список/аудиозаписи')),
                ('can_see_comment', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто видит комментарии')),
                ('create_item', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто создает аудиозаписи')),
                ('create_comment', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто создает комментарии')),
                ('can_copy', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто может добавлять список/аудиозаписи себе')),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.musiclist', verbose_name='Список записей')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Исключения/Включения друга',
                'verbose_name_plural': 'Исключения/Включения друзей',
            },
        ),
    ]
