# Generated by Django 2.2.5 on 2020-01-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20200106_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundparsing',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
