# Generated by Django 2.2.5 on 2020-01-07 12:02

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_soundparsing_is_deleted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='soundparsing',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='music_sound_created_8261e9_brin'),
        ),
    ]
