# Generated by Django 2.2.5 on 2020-01-09 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0023_remove_soundlist_autoplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTempSoundList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('list', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.SoundList', verbose_name='Связь на плейлист человека или сообщества')),
                ('tag', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.SoundTags', verbose_name='Связь на тег')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Слушатель')),
            ],
        ),
    ]
