# Generated by Django 2.2.5 on 2020-01-10 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_usertempsoundlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundlist',
            name='creator',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_playlist', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='usertempsoundlist',
            name='list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_field', to='music.SoundList', verbose_name='Связь на плейлист человека или сообщества'),
        ),
        migrations.AlterField(
            model_name='usertempsoundlist',
            name='tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_field', to='music.SoundTags', verbose_name='Связь на тег'),
        ),
    ]
