# Generated by Django 2.2.5 on 2020-01-10 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_auto_20200110_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertempsoundlist',
            name='user',
            field=models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Слушатель'),
        ),
    ]
