# Generated by Django 2.2.5 on 2020-01-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_auto_20200110_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundparsing',
            options={'verbose_name': 'спарсенные треки', 'verbose_name_plural': 'спарсенные треки'},
        ),
    ]
