# Generated by Django 2.2.5 on 2020-01-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0027_auto_20200111_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundparsing',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_tag', to='music.SoundTags', verbose_name='Буква'),
        ),
    ]
