# Generated by Django 2.2.5 on 2020-01-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0029_auto_20200112_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundlist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
