# Generated by Django 2.2.5 on 2020-01-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_auto_20200113_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundparsing',
            name='permalink',
        ),
        migrations.RemoveField(
            model_name='soundparsing',
            name='stream_url',
        ),
    ]
