# Generated by Django 2.2.5 on 2020-01-14 09:28

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0031_auto_20200113_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundcloudParsing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('artwork_url', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('release_year', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('listen', models.IntegerField(default=0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.SoundGenres', verbose_name='Жанр трека')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_tag', to='music.SoundTags', verbose_name='Буква')),
            ],
            options={
                'verbose_name': 'спарсенные треки',
                'verbose_name_plural': 'спарсенные треки',
            },
        ),
        migrations.AlterField(
            model_name='soundlist',
            name='track',
            field=models.ManyToManyField(blank='True', related_name='players', to='music.SoundcloudParsing'),
        ),
        migrations.DeleteModel(
            name='SoundParsing',
        ),
        migrations.AddIndex(
            model_name='soundcloudparsing',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='music_sound_created_c0c921_brin'),
        ),
    ]
