# Generated by Django 2.2.5 on 2020-01-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0032_auto_20200114_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundcloudparsing',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_genre', to='music.SoundGenres', verbose_name='Жанр трека'),
        ),
    ]
