# Generated by Django 2.2.5 on 2020-03-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0034_usertempsoundlist_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundcloudparsing',
            name='listen',
        ),
    ]
