# Generated by Django 2.2.5 on 2020-03-27 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0035_remove_soundcloudparsing_listen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundcloudparsing',
            name='artwork_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soundcloudparsing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 10, 12, 2, 62659)),
        ),
        migrations.AlterField(
            model_name='soundcloudparsing',
            name='release_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
