# Generated by Django 2.2.5 on 2020-03-27 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0036_auto_20200327_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundcloudparsing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
