# Generated by Django 2.2.5 on 2020-04-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0037_auto_20200327_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertempsoundlist',
            name='list',
        ),
    ]
