# Generated by Django 2.2.5 on 2020-04-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0038_auto_20200402_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertempsoundlist',
            name='community',
        ),
        migrations.RemoveField(
            model_name='usertempsoundlist',
            name='user',
        ),
        migrations.AddField(
            model_name='usertempsoundlist',
            name='list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_field', to='music.SoundList', verbose_name='Связь на плейлист человека или сообщества'),
        ),
    ]
