# Generated by Django 2.2.5 on 2020-06-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0040_usertempsoundlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundlist',
            name='is_generic',
            field=models.BooleanField(default=False, verbose_name='Сгенерированный'),
        ),
    ]
