# Generated by Django 2.2.5 on 2020-06-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0041_soundlist_is_generic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundlist',
            options={'ordering': ['order'], 'verbose_name': 'список: весь, человека или сообщества', 'verbose_name_plural': 'списки: весь, человека или сообщества'},
        ),
        migrations.AddField(
            model_name='soundlist',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
