# Generated by Django 2.2.5 on 2020-06-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0042_auto_20200601_1457'),
    ]

    operations = [
    ]
