# Generated by Django 2.2.5 on 2019-09-11 17:02

import communities.helpers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=300, null=True, verbose_name='Описание')),
                ('rules', models.TextField(max_length=100, null=True, verbose_name='Правила')),
                ('avatar', imagekit.models.fields.ProcessedImageField(null=True, upload_to=communities.helpers.upload_to_community_avatar_directory, verbose_name='Аватар')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('type', models.CharField(choices=[('P', 'Публичное'), ('T', 'Приватное')], default='P', editable=False, max_length=2)),
                ('user_adjective', models.CharField(max_length=100, null=True, verbose_name='Какой-то пользователь')),
                ('users_adjective', models.CharField(max_length=100, null=True, verbose_name='Какие-то пользователи')),
                ('invites_enabled', models.BooleanField(default=True, verbose_name='Разрешить приглашения')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удаленное')),
            ],
            options={
                'verbose_name_plural': 'сообщества',
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_administrator', models.BooleanField(default=False, verbose_name='Это администратор')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Это модератор')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communities.Community', verbose_name='Сообщество')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создан')),
                ('action_type', models.CharField(choices=[('B', 'Заблокировать'), ('U', 'Разблокировать'), ('AM', 'Добавить модератора'), ('RM', 'Удалить модератора'), ('AA', 'Добавить администратора'), ('RA', 'Удалить администратора'), ('OP', 'Открыть пост'), ('CP', 'Закрыть пост'), ('RP', 'Удалить пост'), ('RPC', 'Удалить комментарий к посту'), ('DPC', 'Отключить комментарии'), ('EPC', 'Включить комментарии')], editable=False, max_length=5)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='communities.Community', verbose_name='Сообщество')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='communities.Community', verbose_name='Сообщество')),
            ],
        ),
    ]
