# Generated by Django 2.2.5 on 2019-11-30 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitynotificationssettings',
            name='community',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='community_notifications_settings', to='communities.Community', verbose_name='Сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communityprivatesettings',
            name='community',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='community_private_settings', to='communities.Community', verbose_name='Сообщество'),
            preserve_default=False,
        ),
    ]
