# Generated by Django 3.1 on 2020-09-03 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitycategory',
            options={'ordering': ['order'], 'verbose_name': 'Категория сообществ', 'verbose_name_plural': 'Категории сообществ'},
        ),
        migrations.AlterModelOptions(
            name='communitysubcategory',
            options={'ordering': ['order'], 'verbose_name': 'Подкатегория сообществ', 'verbose_name_plural': 'Подкатегории сообществ'},
        ),
        migrations.AlterField(
            model_name='communitysubcategory',
            name='sudcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_categories', to='communities.communitycategory', verbose_name='Категория сообщества'),
        ),
    ]
