# Generated by Django 3.2 on 2021-04-30 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityinfo',
            old_name='traks',
            new_name='tracks',
        ),
        migrations.AddField(
            model_name='communityinfo',
            name='articles',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во статей'),
        ),
        migrations.AddField(
            model_name='communityinfo',
            name='docs',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во документов'),
        ),
        migrations.AlterUniqueTogether(
            name='communitymembership',
            unique_together={('user', 'community')},
        ),
    ]
