# Generated by Django 2.2.5 on 2019-10-06 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Имя')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.CharField(max_length=64, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(editable=False, verbose_name='Когда создана')),
                ('avatar', models.ImageField(null=True, upload_to='', verbose_name='Аватар')),
                ('order', models.IntegerField(default=100, verbose_name='Номер')),
                ('communities', models.ManyToManyField(blank=True, related_name='categories', to='communities.Community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
        ),
    ]
