# Generated by Django 2.2.5 on 2019-10-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'сообщество', 'verbose_name_plural': 'сообщества'},
        ),
        migrations.AlterModelOptions(
            name='communitycategory',
            options={'verbose_name': 'Категория сообществ', 'verbose_name_plural': 'Категории сообществ'},
        ),
        migrations.AlterModelOptions(
            name='communityinvite',
            options={'verbose_name': 'Приглашение в сообщество', 'verbose_name_plural': 'Приглашения в сообщества'},
        ),
        migrations.AlterModelOptions(
            name='communitymembership',
            options={'verbose_name': 'подписчик сообщества', 'verbose_name_plural': 'подписчики сообщества'},
        ),
        migrations.AlterModelOptions(
            name='communitysubcategory',
            options={'verbose_name': 'Подкатегория сообществ', 'verbose_name_plural': 'Подкатегории сообществ'},
        ),
    ]
