# Generated by Django 2.2.5 on 2019-09-05 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='banned_users',
            field=models.ManyToManyField(related_name='banned_of_communities', to=settings.AUTH_USER_MODEL, verbose_name='Черный список'),
        ),
        migrations.AddField(
            model_name='community',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_communities', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='starrers',
            field=models.ManyToManyField(related_name='favorite_communities', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
