# Generated by Django 2.2.16 on 2020-09-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitysectionsopen',
            name='doc',
            field=models.BooleanField(default=True, verbose_name='Документы открыты'),
        ),
    ]
