# Generated by Django 2.2.16 on 2020-09-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='post_community', to='posts.Post'),
        ),
    ]
