# Generated by Django 2.2.5 on 2019-12-23 12:11

import communities.helpers
from django.conf import settings
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20191130_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='banned_of_communities', to=settings.AUTH_USER_MODEL, verbose_name='Черный список'),
        ),
        migrations.AlterField(
            model_name='community',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='', upload_to=communities.helpers.upload_to_community_avatar_directory),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='rules',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Правила'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='starrers',
            field=models.ManyToManyField(blank=True, related_name='favorite_communities', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='community',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='статус-слоган'),
            preserve_default=False,
        ),
    ]
