# Generated by Django 2.2.5 on 2019-09-05 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20190905_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='color',
        ),
        migrations.RemoveField(
            model_name='community',
            name='cover',
        ),
        migrations.AlterField(
            model_name='community',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано'),
        ),
    ]
