# Generated by Django 2.2.5 on 2019-11-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20191101_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.CharField(choices=[('P', 'Публичное'), ('T', 'Приватное'), ('C', 'Закрытое')], default='P', max_length=2),
        ),
    ]
