# Generated by Django 2.2.5 on 2019-10-06 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CommunityCategory',
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Заголовок'),
        ),
    ]
