# Generated by Django 2.2.5 on 2019-09-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20190911_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='статус-слоган'),
        ),
    ]
