# Generated by Django 2.2.5 on 2019-10-29 11:16

import communities.helpers
from django.conf import settings
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_auto_20191028_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=communities.helpers.upload_to_community_avatar_directory),
        ),
        migrations.AlterField(
            model_name='community',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=communities.helpers.upload_to_community_avatar_directory),
        ),
        migrations.RemoveField(
            model_name='community',
            name='banned_users',
        ),
        migrations.AddField(
            model_name='community',
            name='banned_users',
            field=models.ManyToManyField(related_name='banned_of_communities', to=settings.AUTH_USER_MODEL, verbose_name='Черный список'),
        ),
        migrations.RemoveField(
            model_name='community',
            name='starrers',
        ),
        migrations.AddField(
            model_name='community',
            name='starrers',
            field=models.ManyToManyField(related_name='favorite_communities', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
