# Generated by Django 2.2.5 on 2019-09-18 11:53

import communities.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20190916_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='avatar',
            field=models.ImageField(null=True, upload_to=communities.helpers.upload_to_community_avatar_directory, verbose_name='Аватар'),
        ),
    ]
