# Generated by Django 2.2.5 on 2019-09-12 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='banned_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='banned_of_communities', to=settings.AUTH_USER_MODEL, verbose_name='Черный список'),
        ),
        migrations.AlterField(
            model_name='community',
            name='starrers',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_communities', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='community',
            name='user_adjective',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Какой-то пользователь'),
        ),
        migrations.AlterField(
            model_name='community',
            name='users_adjective',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Какие-то пользователи'),
        ),
    ]
