# Generated by Django 2.2.16 on 2020-09-23 20:23

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_post'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='community',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='communities_created_2903f5_brin'),
        ),
    ]
