# Generated by Django 2.2.5 on 2019-10-09 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0003_auto_20191006_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='user_adjective',
        ),
        migrations.RemoveField(
            model_name='community',
            name='users_adjective',
        ),
        migrations.RemoveField(
            model_name='communitycategory',
            name='communities',
        ),
        migrations.RemoveField(
            model_name='communitycategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='communitycategory',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='communitycategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='communitycategory',
            name='title',
        ),
        migrations.RemoveField(
            model_name='community',
            name='banned_users',
        ),
        migrations.AddField(
            model_name='community',
            name='banned_users',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='banned_of_communities', to=settings.AUTH_USER_MODEL, verbose_name='Черный список'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
        migrations.RemoveField(
            model_name='community',
            name='starrers',
        ),
        migrations.AddField(
            model_name='community',
            name='starrers',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_communities', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communitycategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='communitycategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Номер'),
        ),
        migrations.CreateModel(
            name='CommunitySubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('avatar', models.ImageField(null=True, upload_to='', verbose_name='Аватар')),
                ('order', models.IntegerField(default=0, verbose_name='Номер')),
                ('sudcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_categories', to='communities.CommunityCategory', verbose_name='Подкатегория сообщества')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='community_sub_categories', to='communities.CommunitySubCategory', verbose_name='Подкатегория сообщества'),
            preserve_default=False,
        ),
    ]
