# Generated by Django 2.2.5 on 2019-11-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_auto_20191107_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='community',
            name='rules',
            field=models.TextField(max_length=1000, null=True, verbose_name='Правила'),
        ),
    ]
