# Generated by Django 2.2.5 on 2019-09-05 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0003_auto_20190905_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityinvite',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_communities_invites', to=settings.AUTH_USER_MODEL, verbose_name='Кто приглашает в сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communityinvite',
            name='invited_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='communities_invites', to=settings.AUTH_USER_MODEL, verbose_name='Кого приглашают в сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communitylog',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.Post', verbose_name='Пост'),
        ),
        migrations.AddField(
            model_name='communitylog',
            name='source_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто модерирует'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communitylog',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кого модерируют'),
        ),
        migrations.AddField(
            model_name='communitymembership',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='communities_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Члены сообщества'),
            preserve_default=False,
        ),
    ]
