# Generated by Django 2.2.5 on 2019-09-05 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20190905_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitylog',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано'),
        ),
    ]
