# Generated by Django 2.2.5 on 2019-10-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20191029_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.CharField(choices=[('P', 'Публичное'), ('T', 'Приватное')], default='P', max_length=2),
        ),
    ]
