# Generated by Django 2.2.5 on 2019-11-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20191108_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityNotificationsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о комментариях к записям')),
                ('react_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о реакциях к записи')),
                ('comment_reply_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления об ответах на комментарии к записям')),
                ('comment_reply_react_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления реакциях на ответы к комментариям')),
                ('comment_react_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о реакциях на комментарии к записям')),
                ('connection_request_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о заявках в сообщество')),
                ('comment_user_mention_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления об упоминаниях в комментариях к записям')),
                ('user_mention_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления об упоминаниях в записям')),
                ('repost_notifications', models.BooleanField(default=True, verbose_name='Отправлять уведомления о репостах записей')),
                ('commynity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_notifications_settings', to='communities.Community', verbose_name='Сообщество')),
            ],
        ),
    ]
