# Generated by Django 3.2 on 2021-05-26 10:42

import communities.helpers
from django.conf import settings
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0005_auto_20210526_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='banned_users',
        ),
        migrations.RemoveField(
            model_name='communityinfo',
            name='b_avatar',
        ),
        migrations.RemoveField(
            model_name='communityinfo',
            name='cover',
        ),
        migrations.AddField(
            model_name='community',
            name='b_avatar',
            field=models.ImageField(blank=True, upload_to=communities.helpers.upload_to_community_avatar_directory),
        ),
        migrations.AddField(
            model_name='community',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=communities.helpers.upload_to_community_cover_directory),
        ),
        migrations.AddField(
            model_name='communityinfo',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='banned_of_communities', to=settings.AUTH_USER_MODEL, verbose_name='Черный список'),
        ),
        migrations.AlterField(
            model_name='community',
            name='s_avatar',
            field=models.ImageField(blank=True, upload_to=communities.helpers.upload_to_community_avatar_directory),
        ),
    ]
