# Generated by Django 2.2.5 on 2020-01-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_auto_20200118_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymembership',
            name='is_advertiser',
            field=models.BooleanField(default=False, verbose_name='Это рекламодатель'),
        ),
        migrations.AddField(
            model_name='communitymembership',
            name='is_editor',
            field=models.BooleanField(default=False, verbose_name='Это редактор'),
        ),
    ]
