# Generated by Django 2.2.5 on 2019-11-09 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_communitynotificationssettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitynotificationssettings',
            old_name='commynity',
            new_name='community',
        ),
        migrations.CreateModel(
            name='CommunityPrivateSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_visible_all', models.BooleanField(default=True, verbose_name='Фото сообщества видны всем')),
                ('photo_visible_member', models.BooleanField(default=True, verbose_name='Фото сообщества видны подписчикам')),
                ('can_comments', models.BooleanField(default=True, verbose_name='Все могут оставлять комментарии все пользователи')),
                ('can_add_post', models.BooleanField(default=False, verbose_name='Все могут писать записи на стене')),
                ('can_add_article', models.BooleanField(default=False, verbose_name='Все могут писать статьи на стене')),
                ('can_add_good', models.BooleanField(default=False, verbose_name='Все могут добавлять товары')),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_private_settings', to='communities.Community', verbose_name='Сообщество')),
            ],
        ),
    ]
