# Generated by Django 3.2 on 2021-06-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_auto_20210526_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDocListPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('list', models.PositiveIntegerField(default=0, verbose_name='Фотоальбом')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Порядок отображения списка документов',
                'verbose_name_plural': 'Порядки отображения списков документов',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='CommunityGoodListPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('list', models.PositiveIntegerField(default=0, verbose_name='Фотоальбом')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Порядок отображения списка товаров',
                'verbose_name_plural': 'Порядки отображения списков товаров',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPhotoListPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('list', models.PositiveIntegerField(default=0, verbose_name='Фотоальбом')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Порядок отображения фотоальбома',
                'verbose_name_plural': 'Порядки отображения фотоальбомов',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPlayListPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('list', models.PositiveIntegerField(default=0, verbose_name='Фотоальбом')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Порядок отображения плейлиста',
                'verbose_name_plural': 'Порядки отображения плейлистов',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostListPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('list', models.PositiveIntegerField(default=0, verbose_name='Фотоальбом')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Порядок отображения списка записей',
                'verbose_name_plural': 'Порядки отображения списков записей',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='CommunitySurveyListPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('list', models.PositiveIntegerField(default=0, verbose_name='Фотоальбом')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Порядок отображения списка опросов',
                'verbose_name_plural': 'Порядки отображения списков опросов',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='CommunityVideoListPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.PositiveIntegerField(default=0, verbose_name='Пользователь')),
                ('list', models.PositiveIntegerField(default=0, verbose_name='Фотоальбом')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Порядок отображения видеольбома',
                'verbose_name_plural': 'Порядки отображения видеоальбомов',
                'ordering': ['-position'],
            },
        ),
    ]
