# Generated by Django 2.2.5 on 2019-11-09 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_auto_20191109_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
