# Generated by Django 2.2.5 on 2019-11-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_auto_20191109_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='avatar',
        ),
    ]
