# Generated by Django 3.2 on 2021-06-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_communitydoclistposition_communitygoodlistposition_communityphotolistposition_communityplaylistposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydoclistposition',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='1 - открыт, 0 - недоступен'),
        ),
        migrations.AddField(
            model_name='communitygoodlistposition',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='1 - открыт, 0 - недоступен'),
        ),
        migrations.AddField(
            model_name='communityphotolistposition',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='1 - открыт, 0 - недоступен'),
        ),
        migrations.AddField(
            model_name='communityplaylistposition',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='1 - открыт, 0 - недоступен'),
        ),
        migrations.AddField(
            model_name='communitypostlistposition',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='1 - открыт, 0 - недоступен'),
        ),
        migrations.AddField(
            model_name='communitysurveylistposition',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='1 - открыт, 0 - недоступен'),
        ),
        migrations.AddField(
            model_name='communityvideolistposition',
            name='type',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='1 - открыт, 0 - недоступен'),
        ),
    ]
