# Generated by Django 2.2.5 on 2020-01-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_auto_20200121_1459'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='communitymembership',
            name='communities_communi_f9047f_idx',
        ),
        migrations.RemoveIndex(
            model_name='communitymembership',
            name='communities_communi_b6abad_idx',
        ),
        migrations.RemoveIndex(
            model_name='communitymembership',
            name='communities_communi_91a862_idx',
        ),
        migrations.RemoveIndex(
            model_name='communitymembership',
            name='communities_communi_5976b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='communitymembership',
            name='communities_communi_029e1f_idx',
        ),
    ]
