# Generated by Django 3.2 on 2021-07-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_auto_20210722_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitysectionsopen',
            name='can_see_board',
        ),
        migrations.RemoveField(
            model_name='communitysectionsopen',
            name='can_see_workspace',
        ),
        migrations.AddField(
            model_name='communitysectionsopen',
            name='can_see_planner_board',
            field=models.CharField(choices=[('AC', 'Все пользователи'), ('M', 'Участники пространства или доски'), ('ME', 'Подписчики'), ('Y', 'Только я'), ('MEB', 'Подписчики, кроме'), ('SME', 'Некоторые подписчики'), ('MB', 'Участники, кроме'), ('SM', 'Некоторые участники')], default='M', max_length=3, verbose_name='Кто видит доски планирования'),
        ),
        migrations.AddField(
            model_name='communitysectionsopen',
            name='can_see_planner_column',
            field=models.CharField(choices=[('AC', 'Все пользователи'), ('M', 'Участники пространства или доски'), ('ME', 'Подписчики'), ('Y', 'Только я'), ('MEB', 'Подписчики, кроме'), ('SME', 'Некоторые подписчики'), ('MB', 'Участники, кроме'), ('SM', 'Некоторые участники')], default='M', max_length=3, verbose_name='Кто видит колонки досок планирования'),
        ),
        migrations.AddField(
            model_name='communitysectionsopen',
            name='can_see_planner_workspace',
            field=models.CharField(choices=[('AC', 'Все пользователи'), ('M', 'Участники пространства или доски'), ('ME', 'Подписчики'), ('Y', 'Только я'), ('MEB', 'Подписчики, кроме'), ('SME', 'Некоторые подписчики'), ('MB', 'Участники, кроме'), ('SM', 'Некоторые участники')], default='M', max_length=3, verbose_name='Кто видит рабочие пространства и весь раздел планирования'),
        ),
    ]
