# Generated by Django 3.2 on 2021-09-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_auto_20210920_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitysectionsopen',
            name='can_receive_message',
        ),
        migrations.RemoveField(
            model_name='communitysectionsopen',
            name='can_see_planner_board',
        ),
        migrations.RemoveField(
            model_name='communitysectionsopen',
            name='can_see_planner_column',
        ),
        migrations.RemoveField(
            model_name='communitysectionsopen',
            name='can_see_planner_workspace',
        ),
        migrations.AddField(
            model_name='communitysectionsopen',
            name='can_add_in_chat',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики')], default=1, max_length=2, verbose_name='Кто добавляет в беседы'),
        ),
        migrations.AddField(
            model_name='communitysectionsopen',
            name='can_see_community',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики')], default=1, max_length=2, verbose_name='Кто видит сообщества'),
        ),
        migrations.AddField(
            model_name='communitysectionsopen',
            name='can_see_info',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики')], default=1, max_length=2, verbose_name='Кто видит информацию'),
        ),
        migrations.AddField(
            model_name='communitysectionsopen',
            name='can_see_planner',
            field=models.CharField(choices=[(1, 'Все пользователи'), (2, 'Участники пространства или доски'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики'), (6, 'Участники, кроме'), (8, 'Некоторые участники')], default=2, max_length=2, verbose_name='Кто видит раздел планирования'),
        ),
        migrations.AddField(
            model_name='communitysectionsopen',
            name='can_send_message',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='communitysectionsopen',
            name='can_see_doc',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики')], default=1, max_length=2, verbose_name='Кто видит документы'),
        ),
        migrations.AlterField(
            model_name='communitysectionsopen',
            name='can_see_good',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='communitysectionsopen',
            name='can_see_members',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики')], default=1, max_length=3, verbose_name='Кто видит друзей'),
        ),
        migrations.AlterField(
            model_name='communitysectionsopen',
            name='can_see_music',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='communitysectionsopen',
            name='can_see_photo',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='communitysectionsopen',
            name='can_see_post',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики')], default=1, max_length=2, verbose_name='Кто видит стену'),
        ),
        migrations.AlterField(
            model_name='communitysectionsopen',
            name='can_see_video',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
    ]
