# Generated by Django 3.2 on 2021-10-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_auto_20211004_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_community',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики'), (9, 'Администраторы')], default=1, max_length=2, verbose_name='Кто видит сообщества'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_doc',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики'), (9, 'Администраторы')], default=1, max_length=2, verbose_name='Кто видит документы'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_good',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики'), (9, 'Администраторы')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_info',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики'), (9, 'Администраторы')], default=1, max_length=2, verbose_name='Кто видит информацию'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_member',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики'), (9, 'Администраторы')], default=1, max_length=3, verbose_name='Кто видит друзей'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_music',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики'), (9, 'Администраторы')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_photo',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики'), (9, 'Администраторы')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_planner',
            field=models.CharField(choices=[(1, 'Все пользователи'), (2, 'Участники пространства или доски'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики'), (6, 'Участники, кроме'), (8, 'Некоторые участники'), (9, 'Администраторы')], default=2, max_length=2, verbose_name='Кто видит раздел планирования'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_post',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики'), (9, 'Администраторы')], default=1, max_length=2, verbose_name='Кто видит стену'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_video',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики'), (9, 'Администраторы')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_send_message',
            field=models.CharField(choices=[(1, 'Все пользователи'), (3, 'Подписчики'), (4, 'Только я'), (5, 'Подписчики, кроме'), (7, 'Некоторые подписчики'), (9, 'Администраторы')], default=1, max_length=2, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='communityprivategood',
            name='add_comment',
            field=models.CharField(choices=[('1', 'Все пользователи'), ('2', 'Подписчики'), ('3', 'Только я'), ('4', 'Подписчики, кроме'), ('5', 'Некоторые подписчики'), ('6', 'Администраторы')], default='1', max_length=5, verbose_name='Кто пишет комментарии'),
        ),
        migrations.AlterField(
            model_name='communityprivategood',
            name='add_item',
            field=models.CharField(choices=[('1', 'Все пользователи'), ('2', 'Подписчики'), ('3', 'Только я'), ('4', 'Подписчики, кроме'), ('5', 'Некоторые подписчики'), ('6', 'Администраторы')], default='3', max_length=5, verbose_name='Кто добавляет товары и потом с этими товарами работает'),
        ),
        migrations.AlterField(
            model_name='communityprivategood',
            name='can_see_comment',
            field=models.CharField(choices=[('1', 'Все пользователи'), ('2', 'Подписчики'), ('3', 'Только я'), ('4', 'Подписчики, кроме'), ('5', 'Некоторые подписчики'), ('6', 'Администраторы')], default='1', max_length=5, verbose_name='Кто видит комментарии'),
        ),
        migrations.AlterField(
            model_name='communityprivatemusic',
            name='add_item',
            field=models.CharField(choices=[('1', 'Все пользователи'), ('2', 'Подписчики'), ('3', 'Только я'), ('4', 'Подписчики, кроме'), ('5', 'Некоторые подписчики'), ('6', 'Администраторы')], default='3', max_length=5, verbose_name='Кто добавляет аудио и потом с этими аудио работает'),
        ),
        migrations.AlterField(
            model_name='communityprivatephoto',
            name='add_comment',
            field=models.CharField(choices=[('1', 'Все пользователи'), ('2', 'Подписчики'), ('3', 'Только я'), ('4', 'Подписчики, кроме'), ('5', 'Некоторые подписчики'), ('6', 'Администраторы')], default='1', max_length=5, verbose_name='Кто пишет комментарии'),
        ),
        migrations.AlterField(
            model_name='communityprivatephoto',
            name='add_item',
            field=models.CharField(choices=[('1', 'Все пользователи'), ('2', 'Подписчики'), ('3', 'Только я'), ('4', 'Подписчики, кроме'), ('5', 'Некоторые подписчики'), ('6', 'Администраторы')], default='3', max_length=5, verbose_name='Кто добавляет фото и потом с этими фото работает'),
        ),
        migrations.AlterField(
            model_name='communityprivatephoto',
            name='can_see_comment',
            field=models.CharField(choices=[('1', 'Все пользователи'), ('2', 'Подписчики'), ('3', 'Только я'), ('4', 'Подписчики, кроме'), ('5', 'Некоторые подписчики'), ('6', 'Администраторы')], default='1', max_length=5, verbose_name='Кто видит комментарии'),
        ),
        migrations.AlterField(
            model_name='communityprivateplanner',
            name='add_comments',
            field=models.CharField(choices=[('1', 'Все пользователи'), ('3', 'Участники пространства или доски'), ('2', 'Друзья'), ('4', 'Друзья и друзья друзей'), ('5', 'Только я'), ('6', 'Друзья, кроме'), ('8', 'Некоторые друзья'), ('7', 'Участники, кроме'), ('9', 'Некоторые участники'), ('10', 'Администраторы')], default='3', max_length=2, verbose_name='Кто добавляет комментарии'),
        ),
        migrations.AlterField(
            model_name='communityprivateplanner',
            name='can_see_comments',
            field=models.CharField(choices=[('1', 'Все пользователи'), ('3', 'Участники пространства или доски'), ('2', 'Друзья'), ('4', 'Друзья и друзья друзей'), ('5', 'Только я'), ('6', 'Друзья, кроме'), ('8', 'Некоторые друзья'), ('7', 'Участники, кроме'), ('9', 'Некоторые участники'), ('10', 'Администраторы')], default='3', max_length=2, verbose_name='Кто видит комментарии'),
        ),
        migrations.AlterField(
            model_name='communityprivatepost',
            name='add_comment',
            field=models.CharField(choices=[('1', 'Все пользователи'), ('2', 'Подписчики'), ('3', 'Только я'), ('4', 'Подписчики, кроме'), ('5', 'Некоторые подписчики'), ('6', 'Администраторы')], default='1', max_length=5, verbose_name='Кто пишет комментарии'),
        ),
        migrations.AlterField(
            model_name='communityprivatepost',
            name='add_item',
            field=models.CharField(choices=[('1', 'Все пользователи'), ('2', 'Подписчики'), ('3', 'Только я'), ('4', 'Подписчики, кроме'), ('5', 'Некоторые подписчики'), ('6', 'Администраторы')], default='3', max_length=5, verbose_name='Кто добавляет записи и потом с этими записями работает'),
        ),
        migrations.AlterField(
            model_name='communityprivatepost',
            name='can_see_comment',
            field=models.CharField(choices=[('1', 'Все пользователи'), ('2', 'Подписчики'), ('3', 'Только я'), ('4', 'Подписчики, кроме'), ('5', 'Некоторые подписчики'), ('6', 'Администраторы')], default='1', max_length=5, verbose_name='Кто видит комментарии'),
        ),
        migrations.AlterField(
            model_name='communityprivatevideo',
            name='add_comment',
            field=models.CharField(choices=[('1', 'Все пользователи'), ('2', 'Подписчики'), ('3', 'Только я'), ('4', 'Подписчики, кроме'), ('5', 'Некоторые подписчики'), ('6', 'Администраторы')], default='1', max_length=5, verbose_name='Кто пишет комментарии'),
        ),
        migrations.AlterField(
            model_name='communityprivatevideo',
            name='add_item',
            field=models.CharField(choices=[('1', 'Все пользователи'), ('2', 'Подписчики'), ('3', 'Только я'), ('4', 'Подписчики, кроме'), ('5', 'Некоторые подписчики'), ('6', 'Администраторы')], default='3', max_length=5, verbose_name='Кто добавляет видео и потом с этими видео работает'),
        ),
        migrations.AlterField(
            model_name='communityprivatevideo',
            name='can_see_comment',
            field=models.CharField(choices=[('1', 'Все пользователи'), ('2', 'Подписчики'), ('3', 'Только я'), ('4', 'Подписчики, кроме'), ('5', 'Некоторые подписчики'), ('6', 'Администраторы')], default='1', max_length=5, verbose_name='Кто видит комментарии'),
        ),
    ]
