# Generated by Django 3.2 on 2021-10-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0014_auto_20211006_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityprivatemusic',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityprivatephoto',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityprivateplanner',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityprivatevideo',
            name='community',
        ),
        migrations.DeleteModel(
            name='CommunityPrivateGood',
        ),
        migrations.DeleteModel(
            name='CommunityPrivateMusic',
        ),
        migrations.DeleteModel(
            name='CommunityPrivatePhoto',
        ),
        migrations.DeleteModel(
            name='CommunityPrivatePlanner',
        ),
        migrations.DeleteModel(
            name='CommunityPrivateVideo',
        ),
    ]
