# Generated by Django 3.2 on 2021-10-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0015_auto_20211006_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.CharField(choices=[('CLO', 'Закрытый'), ('PRI', 'Приватный'), ('MAN', 'Созданный персоналом'), ('PUB', 'Открытый'), ('_DELO', 'Открытый удалённый'), ('_DELP', 'Приватный удалённый'), ('_DELC', 'Закрытый удалённый'), ('_DELM', 'Менеджерский удалённый'), ('_BANO', 'Открытый баннер'), ('_BANP', 'Приватный баннер'), ('_BANC', 'Закрытый баннер'), ('_BANM', 'Менеджерский баннер'), ('_SUSO', 'Открытый замороженный'), ('_SUSP', 'Приватный замороженный'), ('_SUSC', 'Закрытый замороженный'), ('_SUSM', 'Менеджерский замороженный'), ('_BLOO', 'Открытый блокнутый'), ('_BLOP', 'Приватный блокнутый'), ('_BLOC', 'Закрытый блокнутый'), ('_BLOM', 'Менеджерский блокнутый')], max_length=5),
        ),
    ]
