# Generated by Django 3.2 on 2021-10-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0016_alter_community_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunityPostListPosition',
            new_name='CommunityPostsListPosition',
        ),
    ]
