# Generated by Django 3.2 on 2021-10-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0017_rename_communitypostlistposition_communitypostslistposition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunityDocListPosition',
            new_name='CommunityDocsListPosition',
        ),
    ]
