# Generated by Django 3.2 on 2021-10-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0018_rename_communitydoclistposition_communitydocslistposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityinfo',
            name='description',
        ),
    ]
