# Generated by Django 3.2 on 2021-10-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0019_remove_communityinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
