# Generated by Django 3.2 on 2021-12-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0020_community_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymembership',
            name='visited',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество визитов'),
        ),
    ]
