# Generated by Django 3.2 on 2021-12-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0022_auto_20211209_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPrivate2',
            fields=[
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='community_private2', serialize=False, to='communities.community', verbose_name='Сообщество')),
                ('can_see_member', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто видит друзей')),
                ('can_see_info', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто видит информацию')),
                ('can_send_message', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто пишет сообщения')),
                ('can_see_post', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто видит стену')),
                ('can_see_photo', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто пишет сообщения')),
                ('can_see_good', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто пишет сообщения')),
                ('can_see_video', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто пишет сообщения')),
                ('can_see_music', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто пишет сообщения')),
                ('can_see_planner', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто видит раздел планирования')),
                ('can_see_doc', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто видит документы')),
            ],
        ),
        migrations.RemoveField(
            model_name='communityprivate',
            name='can_see_community',
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_doc',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто видит документы'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_good',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_info',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто видит информацию'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_member',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто видит друзей'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_music',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_photo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_planner',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто видит раздел планирования'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_post',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто видит стену'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_see_video',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто пишет сообщения'),
        ),
        migrations.AlterField(
            model_name='communityprivate',
            name='can_send_message',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=1, verbose_name='Кто пишет сообщения'),
        ),
        migrations.DeleteModel(
            name='CommunityPrivatePost',
        ),
    ]
