# Generated by Django 3.2 on 2021-12-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0023_auto_20211221_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityPrivate',
        ),
    ]
