# Generated by Django 3.2 on 2021-12-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0024_delete_communityprivate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitymembership',
            options={'ordering': ['-visited'], 'verbose_name': 'подписчик сообщества', 'verbose_name_plural': 'подписчики сообщества'},
        ),
    ]
