# Generated by Django 3.2 on 2021-12-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0026_auto_20211223_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityprivate2',
            name='can_see_stat',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Подписчики'), (3, 'Создатель'), (5, 'Подписчики, кроме'), (6, 'Некоторые подписчики'), (4, 'Персонал')], default=3, verbose_name='Кто видит статистику'),
        ),
    ]
