# Generated by Django 3.2 on 2021-12-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0027_communityprivate2_can_see_stat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitymemberperm',
            old_name='can_see_members',
            new_name='can_see_member',
        ),
    ]
