STANDART,             1

TRAINEE_MODERATOR,    10,13,16,19
MODERATOR,
HIGH_MODERATOR,
TEAMLEAD_MODERATOR,

TRAINEE_SUPPORT,      20,23,26,29
SUPPORT,
HIGH_SUPPORT,
TEAMLEAD_SUPPORT,

TRAINEE_MANAGER,      30,33,36,39
MANAGER,
HIGH_MANAGER,
TEAMLEAD_MANAGER,

ADVERTISER,            40,44,49
HIGH_ADVERTISER,
TEAMLEAD_ADVERTISER,

ADMINISTRATOR,         50,54,59
HIGH_ADMINISTRATOR,
TEAMLEAD_ADMINISTRATOR,
