{
    'original_format': 'wav',
    'download_url': 'https://api.soundcloud.com/tracks/49931/download',
    'label_name': '',
    'tag_list': 'dub minimalist hypnotic flanger',
    'comment_count': 35,
    'genre': 'dub',
    'id': 49931,
    'playback_count': 362904,
    'license': 'cc-by-nc',
    'stream_url': 'https://api.soundcloud.com/tracks/49931/stream',
    'reposts_count': 7,
    'title': 'Hobnotropic',
    'release': '',
    'user_uri': 'https://api.soundcloud.com/users/1433',
    'embeddable_by': 'all',
    'label_id': None,
    'user_favorite': None,
    'release_day': None,
    'downloadable': True,
    'user_playback_count': None,
    'available_country_codes': None,
    'waveform_url': 'https://wave.sndcdn.com/IqSLUxN7arjs_m.png',
    'bpm': 84,
    'label': None,
    'purchase_url': 'https://soundcloud.com/matas',
    'last_modified': '2019/12/04 11:38:02 +0000',
    'artwork_url': 'https://i1.sndcdn.com/artworks-000000103093-941e7e-large.jpg',
    'user': {
        'kind': 'user',
        'avatar_url': 'https://i1.sndcdn.com/avatars-000001548772-zay6dy-large.jpg',
        'last_modified': '2020/01/22 10:47:13 +0000',
        'username': 'matas',
        'permalink': 'matas',
        'permalink_url': 'https://soundcloud.com/matas',
        'id': 1433,
        'uri': 'https://api.soundcloud.com/users/1433'
    },
    'release_month': None,
    'domain_lockings': None,
    'sharing': 'public',
    'downloads_remaining': None,
    'purchase_title': 'Get more tracks!',
    'original_content_size': 130032044,
    'commentable': True,
    'favoritings_count': 61,
    'isrc': None,
    'key_signature': '',
    'release_year': None,
    'download_count': 780,
    'kind': 'track',
    'uri': 'https://api.soundcloud.com/tracks/49931',
    'state': 'finished',
    'streamable': True,
    'permalink_url': 'https://soundcloud.com/matas/hobnotropic',
    'track_type': 'original',
    'video_url': None,
    'created_at': '2008/10/27 09:56:47 +0000',
    'secret_uri': None,
    'secret_token': None,
    'description': "Kinda of an experiment in search for my own sound. I've produced this track from 2 loops I've made using Hobnox Audiotool ( http://www.hobnox.com/audiotool.1046.en.html ). Imported into Ableton LIve! and tweaked some FX afterwards.",
    'permalink': 'hobnotropic',
    'user_id': 1433,
    'duration': 489138
}
