{
    'tag_list': '',
    'created_at': '2011/11/18 01:48:46 +0000',
    'purchase_title': None,
    'permalink_url': 'https://soundcloud.com/truro-cathedral/1-durufl-introit-and-kyrie',
    'permalink': '1-durufl-introit-and-kyrie',
    'release': '',
    'title': 'Duruflé  Introit and Kyrie',
    'id': 28301249,
    'uri': 'https://api.soundcloud.com/tracks/28301249',
    'waveform_url': 'https://w1.sndcdn.com/HsDtfpzKGgtK_m.png',
    'kind': 'track',
    'duration': 446158,
    'artwork_url': None,
    'original_format': 'mp3',
    'genre': 'Choral',
    'streamable': True,
    'description': '',
    'stream_url': 'https://api.soundcloud.com/tracks/28301249/stream',
}
