# Generated by Django 3.1 on 2020-08-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_auto_20200825_1051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communityfollow',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='communityfollow',
            name='community',
        ),
    ]
