# Generated by Django 3.2 on 2021-12-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_auto_20210430_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityfollow',
            name='visited',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество визитов'),
        ),
        migrations.AddField(
            model_name='follow',
            name='visited',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество визитов'),
        ),
    ]
