# Generated by Django 2.2.5 on 2019-12-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_auto_20191130_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityfollow',
            options={'verbose_name': 'Подписчик группы', 'verbose_name_plural': 'Подписчики группы'},
        ),
    ]
