# Generated by Django 5.2.1 on 2025-05-17 11:09

import django.contrib.postgres.indexes
import django.db.models.deletion
import gallery.helpers
import imagekit.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('file', imagekit.models.fields.ProcessedImageField(upload_to=gallery.helpers.upload_to_photo_directory)),
                ('preview', imagekit.models.fields.ProcessedImageField(upload_to=gallery.helpers.upload_to_photo_directory)),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('comments_enabled', models.BooleanField(default=True, verbose_name='Разрешить комментарии')),
                ('votes_on', models.BooleanField(default=True, verbose_name='Реакции разрешены')),
                ('type', models.CharField(choices=[('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('_CLO', 'Закрыто модератором'), ('_MES', 'Загруженный в сообщениях')], default='PUB', max_length=5)),
                ('comment', models.PositiveIntegerField(default=0, verbose_name='Кол-во комментов')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков')),
                ('dislike', models.PositiveIntegerField(default=0, verbose_name='Кол-во дизлайков')),
                ('repost', models.PositiveIntegerField(default=0, verbose_name='Кол-во репостов')),
                ('copy', models.PositiveIntegerField(default=0, verbose_name='Кол-во копий')),
                ('order', models.PositiveIntegerField(default=0)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_community', to='communities.community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='PhotoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('type', models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('WAL', 'Фото со стены'), ('AVA', 'Фото со страницы'), ('_DEL', 'Удалённый'), ('_CLO', 'Закрытый менеджером'), ('_CLOMA', 'Закрытый основной'), ('_CLOWA', 'Закрытый со стены'), ('_CLOAM', 'Закрытый со страницы'), ('_SUS', 'Замороженный'), ('_SUSMA', 'Замороженный основной'), ('_SUSWA', 'Замороженный со стены'), ('_SUSAV', 'Замороженный со страницы')], max_length=6, verbose_name='Тип альбома')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('count', models.PositiveIntegerField(default=0)),
                ('repost', models.PositiveIntegerField(default=0, verbose_name='Кол-во репостов')),
                ('copy', models.PositiveIntegerField(default=0, verbose_name='Кол-во копий')),
                ('can_see_el', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=1, verbose_name='Кто видит записи')),
                ('can_see_comment', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=1, verbose_name='Кто видит комментарии')),
                ('create_el', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=7, verbose_name='Кто создает записи и потом с этими документами работает')),
                ('create_comment', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=1, verbose_name='Кто пишет комментарии')),
                ('copy_el', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=1, verbose_name='Кто может копировать')),
                ('communities', models.ManyToManyField(blank=True, related_name='+', to='communities.community')),
                ('community', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_lists_community', to='communities.community', verbose_name='Сообщество')),
                ('cover_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.photo', verbose_name='Обожка')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_list_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('users', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбомы',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_list', to='gallery.photolist'),
        ),
        migrations.CreateModel(
            name='PhotoListPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_see_item', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто видит список/фотографии')),
                ('can_see_comment', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто видит комментарии')),
                ('create_item', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто создает фотографии')),
                ('create_comment', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто создает комментарии')),
                ('can_copy', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто может добавлять список/фотографии себе')),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gallery.photolist', verbose_name='Список записей')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Исключения/Включения друга',
                'verbose_name_plural': 'Исключения/Включения друзей',
            },
        ),
        migrations.CreateModel(
            name='PhotoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('text', models.TextField(blank=True, null=True)),
                ('attach', models.CharField(blank=True, max_length=200, verbose_name='Прикрепленные элементы')),
                ('type', models.CharField(choices=[('PUB', 'Опубликовано'), ('EDI', 'Изменённый'), ('_DRA', 'Черновик'), ('_DEL', 'Удалённый'), ('_DELE', 'Удалённый изменённый'), ('_CLO', 'Закрытый менеджером'), ('_CLOE', 'Закрытый изменённый')], default='PUB', max_length=5, verbose_name='Тип коммента')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков')),
                ('dislike', models.PositiveIntegerField(default=0, verbose_name='Кол-во дизлайков')),
                ('repost', models.PositiveIntegerField(default=0, verbose_name='Кол-во репостов')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.photo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_comment_replies', to='gallery.photocomment', verbose_name='Родительский комментарий')),
                ('sticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.stickers')),
            ],
            options={
                'verbose_name': 'комментарий к записи',
                'verbose_name_plural': 'комментарии к записи',
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='gallery_pho_created_7ebd02_brin')],
            },
        ),
        migrations.AddIndex(
            model_name='photolist',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='gallery_pho_created_c7a26c_brin'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='gallery_pho_created_389e41_brin'),
        ),
    ]
