# Generated by Django 2.2.5 on 2019-10-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['order'], 'verbose_name': 'Фотоальбом', 'verbose_name_plural': 'Фотоальбомы'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
    ]
