# Generated by Django 2.2.16 on 2020-09-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('chat', '__first__'),
        ('communities', '0001_initial'),
        ('video', '0001_initial'),
        ('posts', '0001_initial'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='community',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_community', to='communities.Community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gallery.Photo', verbose_name='Обожка'),
        ),
        migrations.AddField(
            model_name='album',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='post_album', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='photo',
            name='good_comment',
            field=models.ManyToManyField(blank=True, related_name='good_comment_photo', to='goods.GoodComment'),
        ),
        migrations.AddField(
            model_name='photo',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='item_photo', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='photo',
            name='item_comment',
            field=models.ManyToManyField(blank=True, related_name='comment_photo', to='posts.PostComment'),
        ),
        migrations.AddField(
            model_name='photo',
            name='message',
            field=models.ManyToManyField(blank=True, related_name='message_photo', to='chat.Message'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_comment',
            field=models.ManyToManyField(blank=True, related_name='gallery_comment_photo', to='gallery.PhotoComment'),
        ),
        migrations.AddField(
            model_name='photo',
            name='video_comment',
            field=models.ManyToManyField(blank=True, related_name='video_comment_photo', to='video.VideoComment'),
        ),
    ]
