# Generated by Django 2.2.5 on 2019-12-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191211_1134'),
        ('gallery', '0002_auto_20191130_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='item_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.ItemPost'),
        ),
    ]
