# Generated by Django 2.2.16 on 2020-09-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_message_post'),
        ('gallery', '0002_auto_20200906_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='message',
            field=models.ManyToManyField(blank=True, related_name='message_album', to='chat.Message'),
        ),
    ]
