# Generated by Django 2.2.5 on 2019-12-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191211_1134'),
        ('gallery', '0003_photo_item_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='item',
        ),
        migrations.AddField(
            model_name='photo',
            name='item',
            field=models.ManyToManyField(related_name='item_photo', to='post.Posts'),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='item_comment',
        ),
        migrations.AddField(
            model_name='photo',
            name='item_comment',
            field=models.ManyToManyField(related_name='comment_photo', to='posts.ItemPost'),
        ),
    ]
