# Generated by Django 2.2.5 on 2019-11-10 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20191110_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 15, 28, 8, 432834), verbose_name='Создан'),
        ),
    ]
