# Generated by Django 2.2.16 on 2020-09-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_album_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='item',
            new_name='post',
        ),
    ]
