# Generated by Django 3.2 on 2021-05-05 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_type'),
        ('gallery', '0004_auto_20210501_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photolist',
            name='community',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_lists_community', to='communities.community', verbose_name='Сообщество'),
        ),
    ]
