# Generated by Django 2.2.5 on 2019-12-31 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20191215_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='is_generic',
        ),
    ]
