# Generated by Django 2.2.5 on 2019-11-11 10:05

from django.db import migrations
import gallery.helpers
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20191110_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(upload_to=gallery.helpers.upload_to_photo_directory),
        ),
    ]
