# Generated by Django 2.2.5 on 2019-12-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_album_is_generic'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_generic',
            field=models.BooleanField(default=False, verbose_name='Сгенерированный альбом'),
        ),
    ]
