# Generated by Django 2.2.5 on 2020-01-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_album_is_generic'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='comments_enabled',
            field=models.BooleanField(default=True, verbose_name='Разрешить комментарии'),
        ),
    ]
