# Generated by Django 3.2 on 2021-05-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_photo_community'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='status',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='photocomment',
            old_name='status',
            new_name='type',
        ),
    ]
