# Generated by Django 3.2 on 2021-06-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20210529_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photolist',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
