# Generated by Django 2.2.5 on 2020-01-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_photo_comments_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, related_name='item_photo', to='post.Posts'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='item_comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_photo', to='posts.ItemPost'),
        ),
    ]
