# Generated by Django 2.2.5 on 2019-11-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_auto_20191109_1531'),
        ('gallery', '0007_auto_20191111_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='community',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.Community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='photo',
            name='community',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.Community', verbose_name='Сообщество'),
        ),
    ]
