# Generated by Django 2.2.5 on 2019-11-12 18:41

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0008_auto_20191111_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False, verbose_name='Изменено')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удаено')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.PhotoComment', verbose_name='Родительский комментарий')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Photo')),
            ],
            options={
                'verbose_name': 'комментарий к записи',
                'verbose_name_plural': 'комментарии к записи',
            },
        ),
        migrations.CreateModel(
            name='GoodReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_reactions', to='common.Emoji')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_reactions', to='gallery.Photo')),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'реакция к записи',
                'verbose_name_plural': 'реакции к записям',
            },
        ),
        migrations.CreateModel(
            name='PhotoCommentReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_comment_reactions', to='common.Emoji')),
                ('photo_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_reactions', to='gallery.PhotoComment')),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_comment_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'реакция на комментарий',
                'unique_together': {('reactor', 'photo_comment', 'emoji')},
                'verbose_name_plural': 'реакции на комментарии',
            },
        ),
        migrations.AddIndex(
            model_name='photocomment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='gallery_pho_created_7ebd02_brin'),
        ),
        migrations.AlterUniqueTogether(
            name='goodreaction',
            unique_together={('reactor', 'photo', 'emoji')},
        ),
    ]
