# Generated by Django 2.2.5 on 2020-01-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20200122_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание'),
        ),
    ]
