# Generated by Django 2.2.5 on 2020-02-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20200122_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='item_photo', to='post.Posts'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='item_comment',
            field=models.ManyToManyField(blank=True, related_name='comment_photo', to='posts.ItemPost'),
        ),
    ]
