# Generated by Django 2.2.5 on 2019-11-15 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0009_auto_20191112_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodReaction',
            new_name='PhotoReaction',
        ),
        migrations.AddField(
            model_name='album',
            name='is_generic',
            field=models.BooleanField(default=False, editable=False, verbose_name='Сгенерированный альбом'),
        ),
    ]
