# Generated by Django 3.2 on 2021-06-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_remove_photolist_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-order'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
    ]
