# Generated by Django 2.2.5 on 2019-11-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191114_1444'),
        ('gallery', '0010_auto_20191115_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_generic',
            field=models.BooleanField(default=False, verbose_name='Сгенерированный альбом'),
        ),
    ]
