# Generated by Django 2.2.5 on 2019-11-19 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20191115_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='album_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_2', to='gallery.Album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_1', to='gallery.Album'),
        ),
    ]
