# Generated by Django 3.2 on 2021-09-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20210725_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='type',
            field=models.CharField(choices=[('_PRO', 'Обработка'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('_CLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('_MES', 'Загруженный в сообщениях'), ('_DELM', 'Удалённый менеджерский'), ('_CLOM', 'Закрытый менеджерский')], default='_PRO', max_length=5),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='type',
            field=models.CharField(choices=[('PUB', 'Опубликовано'), ('EDI', 'Изменённый'), ('_PRO', 'Обработка'), ('_DRA', 'Черновик'), ('_DEL', 'Удалённый'), ('_DELE', 'Удалённый изменённый'), ('_CLO', 'Закрытый менеджером'), ('_CLOE', 'Закрытый изменённый')], default='_PRO', max_length=5, verbose_name='Тип альбома'),
        ),
    ]
