# Generated by Django 2.2.5 on 2019-11-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20191119_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Фотоальбом', 'verbose_name_plural': 'Фотоальбомы'},
        ),
    ]
