# Generated by Django 2.2.5 on 2019-11-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_auto_20191128_2004'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photoreaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='photoreaction',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='photoreaction',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photoreaction',
            name='reactor',
        ),
        migrations.DeleteModel(
            name='PhotoCommentReaction',
        ),
        migrations.DeleteModel(
            name='PhotoReaction',
        ),
    ]
