# Generated by Django 3.2 on 2021-10-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_auto_20211014_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='photolist',
            name='is_photo_list',
            field=models.BooleanField(default=True),
        ),
    ]
