# Generated by Django 2.2.5 on 2019-11-30 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_community'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcommentvotes',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.ItemPost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemvotes',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='post.Posts'),
            preserve_default=False,
        ),
    ]
