# Generated by Django 2.2.5 on 2019-11-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20191129_1148'),
        ('main', '0008_auto_20191129_1148'),
        ('goods', '0005_auto_20191129_1148'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emoji',
        ),
        migrations.DeleteModel(
            name='EmojiGroup',
        ),
    ]
