# Generated by Django 3.1 on 2020-08-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('goods', '0001_initial'),
        ('video', '0001_initial'),
        ('posts', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodcommentvotes',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.goodcomment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodvotes',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.good'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photocommentvotes',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gallery.photocomment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photovotes',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gallery.photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postvotes',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocommentvotes',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='video.videocomment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videovotes',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='video.video'),
            preserve_default=False,
        ),
    ]
