# Generated by Django 2.2.5 on 2019-11-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20191130_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvotes',
            name='vote',
            field=models.IntegerField(choices=[(-1, 'Не нравится'), (1, 'Нравится')], default=0, verbose_name='Голос'),
        ),
    ]
