# Generated by Django 2.2.5 on 2019-11-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191129_1518'),
        ('common', '0003_likedislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='content_type',
        ),
        migrations.AddField(
            model_name='likedislike',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
            preserve_default=False,
        ),
    ]
