# Generated by Django 3.2 on 2021-07-06 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0004_stickercategory_stickers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickers',
            options={'verbose_name': 'Стикер', 'verbose_name_plural': 'Стикеры'},
        ),
        migrations.CreateModel(
            name='UserPopulateStickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество использований пользователем')),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.stickers', verbose_name='Стикер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Популярность стикеров',
                'verbose_name_plural': 'Популярность стикеров',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='UserPopulateSmiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество использований пользователем')),
                ('smile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.smiles', verbose_name='Смайл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Популярность смайликов',
                'verbose_name_plural': 'Популярность смайликов',
                'ordering': ['-count'],
            },
        ),
    ]
