# Generated by Django 2.2.5 on 2019-11-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20191130_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcommentvotes',
            old_name='parent',
            new_name='item',
        ),
    ]
