# Generated by Django 3.2 on 2021-07-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210706_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpopulatesmiles',
            name='smile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smile', to='common.smiles', verbose_name='Смайл'),
        ),
        migrations.AlterField(
            model_name='userpopulatestickers',
            name='sticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticker', to='common.stickers', verbose_name='Стикер'),
        ),
    ]
