# Generated by Django 2.2.5 on 2020-03-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_delete_proxyblacklisteddomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('code', models.PositiveSmallIntegerField(default=0, verbose_name='Код')),
            ],
        ),
    ]
