# Generated by Django 2.2.5 on 2020-03-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_phonecodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecodes',
            name='phone',
            field=models.PositiveIntegerField(default=0, verbose_name='Телефон'),
        ),
    ]
