# Generated by Django 2.2.5 on 2020-03-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20200321_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecodes',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
    ]
