# Generated by Django 5.2.1 on 2025-05-17 10:54

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Описание')),
                ('verified', models.BooleanField(default=False, verbose_name='Проверено')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'На рассмотрении'), (2, 'Объект заморожен'), (3, 'Объект закрыт'), (4, 'Объекту присвоен баннер'), (5, 'Отвергнутый')], default=1, verbose_name='Статус')),
                ('type', models.CharField(choices=[('USE', 'Пользователь'), ('COM', 'Сообщество'), ('SIT', 'Сайт'), ('MAI', 'Почта'), ('ART', 'Статья'), ('ARL', 'Список статей'), ('CHA', 'Чат'), ('MES', 'Сообщение'), ('MUL', 'Плейлист'), ('MUS', 'Трек'), ('POL', 'Список записей'), ('POS', 'Запись'), ('CPO', 'Коммент к записи'), ('DOL', 'Список документов'), ('DOC', 'Документ'), ('SUL', 'Список опросов'), ('SUR', 'Опрос'), ('PHL', 'Список фотографий'), ('PHO', 'Фотография'), ('CPH', 'Коммент к фотографии'), ('VIL', 'Список роликов'), ('VID', 'Ролик'), ('CVI', 'Коммент к ролику'), ('GOL', 'Список товаров'), ('GOO', 'Товар'), ('CGO', 'Коммент к товару'), ('WrS', 'Рабочее пространство'), ('BoA', 'Доска'), ('CoL', 'Колонка'), ('CaR', 'Карточка'), ('CwC', 'Коммент к карточке'), ('FOL', 'Список обсуждений'), ('FOI', 'Обсуждение'), ('CFO', 'Коммент к обсуждению'), ('WIL', 'Список википедии'), ('WII', 'Объект википедии'), ('CWI', 'Коммент к википедии')], max_length=4, verbose_name='Класс объекта')),
                ('object_id', models.PositiveIntegerField(default=0, verbose_name='id объекта')),
            ],
            options={
                'verbose_name': 'Проверяемый объект',
                'verbose_name_plural': 'Проверяемые объект',
            },
        ),
        migrations.CreateModel(
            name='ModeratedLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('USE', 'Пользователь'), ('COM', 'Сообщество'), ('SIT', 'Сайт'), ('MAI', 'Почта'), ('ART', 'Статья'), ('ARL', 'Список статей'), ('CHA', 'Чат'), ('MES', 'Сообщение'), ('MUL', 'Плейлист'), ('MUS', 'Трек'), ('POL', 'Список записей'), ('POS', 'Запись'), ('CPO', 'Коммент к записи'), ('DOL', 'Список документов'), ('DOC', 'Документ'), ('SUL', 'Список опросов'), ('SUR', 'Опрос'), ('PHL', 'Список фотографий'), ('PHO', 'Фотография'), ('CPH', 'Коммент к фотографии'), ('VIL', 'Список роликов'), ('VID', 'Ролик'), ('CVI', 'Коммент к ролику'), ('GOL', 'Список товаров'), ('GOO', 'Товар'), ('CGO', 'Коммент к товару'), ('WrS', 'Рабочее пространство'), ('BoA', 'Доска'), ('CoL', 'Колонка'), ('CaR', 'Карточка'), ('CwC', 'Коммент к карточке'), ('FOL', 'Список обсуждений'), ('FOI', 'Обсуждение'), ('CFO', 'Коммент к обсуждению'), ('WIL', 'Список википедии'), ('WII', 'Объект википедии'), ('CWI', 'Коммент к википедии')], max_length=4, verbose_name='Класс объекта')),
                ('object_id', models.PositiveIntegerField(default=0, verbose_name='id объекта')),
                ('manager', models.PositiveIntegerField(default=0, verbose_name='Менеджер')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Список закрыт'), (2, 'Элемент закрыт'), (3, 'Комментарий закрыт'), (4, 'Список заморожен'), (5, 'Элемент заморожен'), (7, 'Список восстановлен'), (8, 'Элемент восстановлен'), (9, 'Комментарий восстановлен'), (10, 'Список разморожен'), (11, 'Элемент разморожен'), (14, 'Жалоба на список отклонена'), (15, 'Жалоба на элемент отклонена'), (16, 'Жалоба на комментарий отклонена'), (20, 'Проверка на список убрана'), (21, 'Проверка на элемент убрана'), (22, 'Проверка на комментарий убрана'), (30, 'Баннер создан'), (31, 'Баннер убран')], default=0, verbose_name='Действие')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('time_to_suspend', models.DateTimeField(blank=True, null=True, verbose_name='Время, на которое заморожен объект')),
            ],
            options={
                'verbose_name': 'Лог модерации',
                'verbose_name_plural': 'Логи модерации',
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='managers_mo_created_d4c063_brin')],
            },
        ),
        migrations.CreateModel(
            name='ModerationPenalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('type', models.CharField(choices=[('USE', 'Пользователь'), ('COM', 'Сообщество'), ('SIT', 'Сайт'), ('MAI', 'Почта'), ('ART', 'Статья'), ('ARL', 'Список статей'), ('CHA', 'Чат'), ('MES', 'Сообщение'), ('MUL', 'Плейлист'), ('MUS', 'Трек'), ('POL', 'Список записей'), ('POS', 'Запись'), ('CPO', 'Коммент к записи'), ('DOL', 'Список документов'), ('DOC', 'Документ'), ('SUL', 'Список опросов'), ('SUR', 'Опрос'), ('PHL', 'Список фотографий'), ('PHO', 'Фотография'), ('CPH', 'Коммент к фотографии'), ('VIL', 'Список роликов'), ('VID', 'Ролик'), ('CVI', 'Коммент к ролику'), ('GOL', 'Список товаров'), ('GOO', 'Товар'), ('CGO', 'Коммент к товару'), ('WrS', 'Рабочее пространство'), ('BoA', 'Доска'), ('CoL', 'Колонка'), ('CaR', 'Карточка'), ('CwC', 'Коммент к карточке'), ('FOL', 'Список обсуждений'), ('FOI', 'Обсуждение'), ('CFO', 'Коммент к обсуждению'), ('WIL', 'Список википедии'), ('WII', 'Объект википедии'), ('CWI', 'Коммент к википедии')], max_length=5, verbose_name='Класс объекта')),
                ('object_id', models.PositiveIntegerField(default=0, verbose_name='id объекта')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Приостановлено'), (2, 'Закрыто'), (3, 'Вывешен баннер')], default=0, verbose_name='Статус объекта')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_penalties', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('moderated_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderated_object', to='managers.moderated', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Оштрафованный объект',
                'verbose_name_plural': 'Оштрафованные объект',
            },
        ),
        migrations.CreateModel(
            name='ModerationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('type', models.CharField(choices=[('P', 'Порнография'), ('NC', 'Для взрослых'), ('S', 'Рассылка спама'), ('B', 'Оскорбительное поведение'), ('F', 'Мошенничество'), ('K', 'Клон моей страницы'), ('OP', 'Моя старая страница'), ('D', 'Наркотики'), ('NM', 'Не нравственный контент'), ('RH', 'Риторика ненависти'), ('U', 'Неэтичное поведение')], max_length=4, verbose_name='Класс объекта')),
                ('moderated_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='managers.moderated', verbose_name='Объект')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL, verbose_name='Репортер')),
            ],
            options={
                'verbose_name': 'Жалоба на объект',
                'verbose_name_plural': 'Жалобы на объект',
            },
        ),
        migrations.CreateModel(
            name='StaffLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Модератор-стажер создан'), (2, 'Модератор-стажер удален'), (5, 'Модератор создан'), (6, 'Модератор удален'), (9, 'Старший модератор создан'), (10, 'Старший модератор удален'), (13, 'Модератор-тимлид создан'), (14, 'Модератор-тимлид удален'), (17, 'Менеджер-стажер создан'), (18, 'Менеджер-стажер удален'), (21, 'Менеджер создан'), (22, 'Менеджер удален'), (25, 'Старший менеджер создан'), (26, 'Старший менеджер удален'), (29, 'Менеджер-тимлид создан'), (30, 'Менеджер-тимлид удален'), (33, 'Менеджер рекламы создан'), (33, 'Менеджер рекламы удален'), (37, 'Старший рекламы создан'), (38, 'Старший рекламы удален'), (41, 'Тимлид рекламы создан'), (42, 'Тимлид рекламы удален'), (45, 'Администратор создан'), (46, 'Администратор удален'), (49, 'Старший администратор создан'), (50, 'Старший администратор удален'), (53, 'Тимлид-администратор создан'), (54, 'Тимлид-администратор удален'), (57, 'Суперменеджер создан'), (58, 'Суперменеджер удален')], default=0, verbose_name='Действие')),
                ('user_pk', models.PositiveIntegerField(default=0, verbose_name='id назначаемого')),
                ('manager', models.PositiveIntegerField(default=0, verbose_name='id менеджера')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Лог работы с персоналом',
                'verbose_name_plural': 'Логи работы с персоналом',
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='managers_st_created_18483c_brin')],
            },
        ),
        migrations.CreateModel(
            name='SupportUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Уровень 1'), (2, 'Уровень 2'), (3, 'Уровень 3'), (4, 'Уровень 4'), (5, 'Уровень 5')], default=0, verbose_name='Уровень сложности')),
                ('manager', models.PositiveIntegerField(default=0, verbose_name='Менеджер')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('points', models.IntegerField(default=0, verbose_name='Компетентность условная')),
                ('chats', models.PositiveIntegerField(default=0, verbose_name='Всего чатов')),
            ],
            options={
                'verbose_name': 'Агент техподдержки',
                'verbose_name_plural': 'Агенты техподдержки',
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='managers_su_created_d64035_brin')],
            },
        ),
    ]
