# Generated by Django 3.2 on 2021-05-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiouserstaff',
            name='level',
            field=models.CharField(blank=True, choices=[('A', 'Администратор'), ('M', 'Модератор'), ('E', 'Редактор'), ('R', 'Рекламодатель')], max_length=5, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='docuserstaff',
            name='level',
            field=models.CharField(blank=True, choices=[('A', 'Администратор'), ('M', 'Модератор'), ('E', 'Редактор'), ('R', 'Рекламодатель')], max_length=5, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='gooduserstaff',
            name='level',
            field=models.CharField(blank=True, choices=[('A', 'Администратор'), ('M', 'Модератор'), ('E', 'Редактор'), ('R', 'Рекламодатель')], max_length=5, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='moderated',
            name='status',
            field=models.CharField(choices=[('P', 'На рассмотрении'), ('S', 'Объект заморожен'), ('C', 'Объект закрыт'), ('BG', 'Объекту присвоен баннер'), ('R', 'Отвергнутый')], default='P', max_length=5, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='moderationpenalty',
            name='status',
            field=models.CharField(choices=[('S', 'Приостановлено'), ('B', 'Закрыто'), ('BA', 'Вывешен баннер')], max_length=5, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='photouserstaff',
            name='level',
            field=models.CharField(blank=True, choices=[('A', 'Администратор'), ('M', 'Модератор'), ('E', 'Редактор'), ('R', 'Рекламодатель')], max_length=5, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='postuserstaff',
            name='level',
            field=models.CharField(blank=True, choices=[('A', 'Администратор'), ('M', 'Модератор'), ('E', 'Редактор'), ('R', 'Рекламодатель')], max_length=5, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='videouserstaff',
            name='level',
            field=models.CharField(blank=True, choices=[('A', 'Администратор'), ('M', 'Модератор'), ('E', 'Редактор'), ('R', 'Рекламодатель')], max_length=5, verbose_name='Уровень доступа'),
        ),
    ]
