# Generated by Django 3.1 on 2020-08-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200825_1051'),
        ('music', '0001_initial'),
        ('goods', '0002_auto_20200825_1051'),
        ('posts', '0001_initial'),
        ('video', '0001_initial'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatedaudio',
            name='music',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_audio', to='music.soundcloudparsing', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedgood',
            name='good',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_good', to='goods.good', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedgoodcomment',
            name='comment',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_good_comment', to='goods.goodcomment', verbose_name='Комментарий к товару'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedphoto',
            name='photo',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_photo', to='gallery.photo', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedphotocomment',
            name='comment',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_photo_comment', to='gallery.photocomment', verbose_name='Комментарий к фотографии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedpost',
            name='post',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_post', to='posts.post', verbose_name='Запись'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedpostcomment',
            name='comment',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_post_comment', to='posts.postcomment', verbose_name='Комментарий к записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedvideo',
            name='video',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_video', to='video.video', verbose_name='Ролик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedvideocomment',
            name='comment',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_video_comment', to='video.videocomment', verbose_name='Комментарий к ролику'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationpenaltyaudio',
            name='audio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='audio_penalties', to='music.soundcloudparsing', verbose_name='Оштрафованный трек'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationpenaltygoodcomment',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='good_comment_penalties', to='goods.goodcomment', verbose_name='Оштрафованный комментарий к товару'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationpenaltyphotocomment',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='photo_comment_penalties', to='gallery.photocomment', verbose_name='Оштрафованный комментарий к фотографии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationpenaltypostcomment',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_penalties', to='posts.postcomment', verbose_name='Оштрафованный комментарий к записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationpenaltyvideocomment',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='video_comment_penalties', to='video.videocomment', verbose_name='Оштрафованный комментарий к ролику'),
            preserve_default=False,
        ),
    ]
