# Generated by Django 2.2.16 on 2020-09-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200906_1514'),
        ('goods', '0002_auto_20200906_1514'),
        ('posts', '0001_initial'),
        ('video', '0001_initial'),
        ('music', '0001_initial'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatedaudio',
            name='music',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_audio', to='music.SoundcloudParsing', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedgood',
            name='good',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_good', to='goods.Good', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedgoodcomment',
            name='comment',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_good_comment', to='goods.GoodComment', verbose_name='Комментарий к товару'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedphoto',
            name='photo',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_photo', to='gallery.Photo', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedphotocomment',
            name='comment',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_photo_comment', to='gallery.PhotoComment', verbose_name='Комментарий к фотографии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedpost',
            name='post',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_post', to='posts.Post', verbose_name='Запись'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedpostcomment',
            name='comment',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_post_comment', to='posts.PostComment', verbose_name='Комментарий к записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedvideo',
            name='video',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_video', to='video.Video', verbose_name='Ролик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderatedvideocomment',
            name='comment',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderated_video_comment', to='video.VideoComment', verbose_name='Комментарий к ролику'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationpenaltyaudio',
            name='audio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='audio_penalties', to='music.SoundcloudParsing', verbose_name='Оштрафованный трек'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationpenaltygood',
            name='good',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='good_penalties', to='goods.Good', verbose_name='Оштрафованный товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationpenaltygoodcomment',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='good_comment_penalties', to='goods.GoodComment', verbose_name='Оштрафованный комментарий к товару'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationpenaltyphoto',
            name='photo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='photo_penalties', to='gallery.Photo', verbose_name='Оштрафованная фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationpenaltyphotocomment',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='photo_comment_penalties', to='gallery.PhotoComment', verbose_name='Оштрафованный комментарий к фотографии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationpenaltypost',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_penalties', to='posts.Post', verbose_name='Оштрафованная запись'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationpenaltypostcomment',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_penalties', to='posts.PostComment', verbose_name='Оштрафованный комментарий к записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationpenaltyvideo',
            name='video',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='video_penalties', to='video.Video', verbose_name='Оштрафованный ролик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationpenaltyvideocomment',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='video_comment_penalties', to='video.VideoComment', verbose_name='Оштрафованный комментарий к ролику'),
            preserve_default=False,
        ),
    ]
