# Generated by Django 3.1 on 2020-08-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_auto_20200825_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderatedaudio',
            name='music',
        ),
        migrations.RemoveField(
            model_name='moderatedgood',
            name='good',
        ),
        migrations.RemoveField(
            model_name='moderatedgoodcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='moderatedphoto',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='moderatedphotocomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='moderatedpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='moderatedpostcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='moderatedvideo',
            name='video',
        ),
        migrations.RemoveField(
            model_name='moderatedvideocomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='moderationpenaltyaudio',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='moderationpenaltygoodcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='moderationpenaltyphotocomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='moderationpenaltypostcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='moderationpenaltyvideocomment',
            name='comment',
        ),
    ]
