# Generated by Django 3.2 on 2022-01-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_auto_20210911_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planneruserstaff',
            name='user',
        ),
        migrations.DeleteModel(
            name='CanWorkStaffPlannerUser',
        ),
        migrations.DeleteModel(
            name='PlannerUserStaff',
        ),
    ]
