# Generated by Django 3.2 on 2021-09-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frends', '0002_connectperm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectperm',
            name='can_add_post',
        ),
        migrations.AddField(
            model_name='connectperm',
            name='can_copy_doc',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто копирует документы и списки'),
        ),
        migrations.AddField(
            model_name='connectperm',
            name='can_copy_good',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто копирует товары и списки'),
        ),
        migrations.AddField(
            model_name='connectperm',
            name='can_copy_music',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто копирует музыку и списки'),
        ),
        migrations.AddField(
            model_name='connectperm',
            name='can_copy_photo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто копирует фото и списки'),
        ),
        migrations.AddField(
            model_name='connectperm',
            name='can_copy_planner',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто копирует рабочие пространства и доски'),
        ),
        migrations.AddField(
            model_name='connectperm',
            name='can_copy_post',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто копирует записи и списки'),
        ),
        migrations.AddField(
            model_name='connectperm',
            name='can_copy_video',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто копирует видео и списки'),
        ),
        migrations.AddField(
            model_name='connectperm',
            name='can_create_good_comment',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто создает комменты к товарам'),
        ),
        migrations.AddField(
            model_name='connectperm',
            name='can_create_photo_comment',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто создает комменты к фото'),
        ),
        migrations.AddField(
            model_name='connectperm',
            name='can_create_planner_comment',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто создает комменты к задачам'),
        ),
        migrations.AddField(
            model_name='connectperm',
            name='can_create_post_comment',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто создает комменты к записям'),
        ),
        migrations.AddField(
            model_name='connectperm',
            name='can_create_video_comment',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто создает комменты к видео'),
        ),
        migrations.AlterField(
            model_name='connectperm',
            name='can_see_doc',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто видит документы и списки'),
        ),
        migrations.AlterField(
            model_name='connectperm',
            name='can_see_good',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто видит товары и списки'),
        ),
        migrations.AlterField(
            model_name='connectperm',
            name='can_see_music',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто видит музыку и списки'),
        ),
        migrations.AlterField(
            model_name='connectperm',
            name='can_see_photo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто видит фото и списки'),
        ),
        migrations.AlterField(
            model_name='connectperm',
            name='can_see_planner',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто видит рабочие пространства и доски'),
        ),
        migrations.AlterField(
            model_name='connectperm',
            name='can_see_video',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто видит видео и списки'),
        ),
    ]
