# Generated by Django 2.2.5 on 2019-09-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frends', '0002_auto_20190916_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='target_connection',
        ),
    ]
