# Generated by Django 3.2 on 2021-12-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frends', '0003_auto_20210921_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='visited',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество визитов'),
        ),
    ]
