# Generated by Django 3.2 on 2021-12-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frends', '0004_connect_visited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connect',
            options={'ordering': ['-visited'], 'verbose_name': 'Друг', 'verbose_name_plural': 'Друзья'},
        ),
    ]
