# Generated by Django 3.2 on 2021-04-29 19:12

import chat.helpers
from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('LIS', 'Пользовательский'), ('PRI', 'Приватный'), ('MAN', 'Созданный персоналом'), ('TPRO', 'Обработка'), ('TFIX', 'Закреплённый'), ('TDEL', 'Удалённый'), ('TDELP', 'Удалённый приватный'), ('TDELM', 'Удалённый менеджерский'), ('TCLO', 'Закрытый менеджером'), ('TCLOP', 'Закрытый приватный'), ('TCLOM', 'Закрытый основной'), ('TCLOMA', 'Закрытый менеджерский'), ('TCLOF', 'Закрытый закреплённый')], default='TPRO', max_length=6, verbose_name='Тип чата')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=chat.helpers.upload_to_chat_directory)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Беседа',
                'verbose_name_plural': 'Беседы',
            },
        ),
        migrations.CreateModel(
            name='ChatUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_administrator', models.BooleanField(default=False, verbose_name='Это администратор')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('chat', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='chat_relation', to='chat.chat', verbose_name='Чат')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='chat_users', to=settings.AUTH_USER_MODEL, verbose_name='Члены сообщества')),
            ],
            options={
                'verbose_name': 'участник беседы',
                'verbose_name_plural': 'участники бесед',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('unread', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('PRO', 'Обработка'), ('PUB', 'Опубликовано'), ('TDEL', 'Удалено'), ('PRI', 'Приватно'), ('TCLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('TDELP', 'Удалённый приватный'), ('TDELM', 'Удалённый менеджерский'), ('TCLOP', 'Закрытый приватный'), ('TCLOM', 'Закрытый менеджерский')], default='PRO', max_length=5, verbose_name='Статус сообщения')),
                ('attach', models.CharField(blank=True, max_length=200, verbose_name='Прикрепленные элементы')),
                ('voice', models.FileField(blank=True, upload_to=chat.helpers.upload_to_chat_directory, verbose_name='Голосовое сообщение')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message', to='chat.chat')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_creator', to='chat.chatusers', verbose_name='Создатель')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_thread', to='chat.message')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('created',),
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='chat_messag_created_aeee25_brin'),
        ),
        migrations.AddIndex(
            model_name='chatusers',
            index=models.Index(fields=['chat', 'user'], name='chat_chatus_chat_id_277a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatusers',
            index=models.Index(fields=['chat', 'user', 'is_administrator'], name='chat_chatus_chat_id_10903e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatusers',
            unique_together={('user', 'chat')},
        ),
        migrations.AddIndex(
            model_name='chat',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='chat_chat_created_6a9d53_brin'),
        ),
    ]
