# Generated by Django 3.2 on 2021-05-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210430_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='status',
            new_name='type',
        ),
    ]
