# Generated by Django 3.2 on 2021-06-26 18:07

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210626_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['order'], 'verbose_name': 'Беседа', 'verbose_name_plural': 'Беседы'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='chat_chat_created_ab4521_brin',
        ),
        migrations.AddField(
            model_name='chat',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='chat_chat_created_6a9d53_brin'),
        ),
    ]
