# Generated by Django 3.2 on 2021-06-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210626_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_recipient', to='chat.chatusers', verbose_name='Получаетель'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('PRI', 'Пользовательский'), ('MAN', 'Созданный персоналом'), ('_PRO', 'Обработка'), ('_FIXT', 'Закреплённый приватный'), ('_FIXG', 'Закреплённый групповой'), ('_DEL', 'Удалённый приватный'), ('_DELG', 'Удалённый групповой'), ('_DELM', 'Удалённый менеджерский'), ('_DELPF', 'Удалённый приватный закреплённый'), ('_DELGF', 'Удалённый групповой закреплённый'), ('_CLO', 'Закрытый приватный'), ('_CLOG', 'Закрытый групповой'), ('_CLOM', 'Закрытый менеджерский'), ('_CLOPF', 'Закрытый закреплённый приватный'), ('_CLOGF', 'Закрытый групповой закреплённый')], default='_PRO', max_length=6, verbose_name='Тип чата'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('_PRO', 'Обработка'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('EDI', 'Изменено'), ('_CLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('_DELF', 'Удалённый закрепленный'), ('_DELFI', 'Удалённый измененный закрепленный'), ('_DELE', 'Удалённый измененный'), ('_DELM', 'Удалённый менеджерский'), ('_CLOE', 'Закрытый измененный'), ('_CLOM', 'Закрытый менеджерский'), ('_CLOFI', 'Закрытый измененный закрепленный'), ('_CLOF', 'Закрытый закрепленный')], default='_PRO', max_length=6, verbose_name='Статус сообщения'),
        ),
    ]
