# Generated by Django 3.2 on 2021-06-28 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_auto_20210627_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chat.message', verbose_name='Сообщение')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Добавивший')),
            ],
            options={
                'verbose_name': 'Избранное сообщение',
                'verbose_name_plural': 'Избранные сообщения',
                'unique_together': {('user', 'message')},
            },
        ),
    ]
