# Generated by Django 3.2 on 2021-06-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_messagefavourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_copy', to='chat.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('_PRO', 'Обработка'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('EDI', 'Изменено'), ('_CLO', 'Закрыто модератором'), ('_DELF', 'Удалённый закрепленный'), ('_DELFI', 'Удалённый измененный закрепленный'), ('_DELE', 'Удалённый измененный'), ('_CLOE', 'Закрытый измененный'), ('_CLOFI', 'Закрытый измененный закрепленный'), ('_CLOF', 'Закрытый закрепленный')], default='_PRO', max_length=6, verbose_name='Статус сообщения'),
        ),
    ]
