# Generated by Django 3.2 on 2021-07-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20210630_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='unread',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Не прочитано'),
        ),
    ]
