# Generated by Django 3.2 on 2021-09-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_message_sticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('_PRO', 'Обработка'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('EDI', 'Изменено'), ('_CLO', 'Закрыто модератором'), ('_DRA', 'Черновик'), ('_DELF', 'Удалённый закрепленный'), ('_DELFI', 'Удалённый измененный закрепленный'), ('_DELE', 'Удалённый измененный'), ('_CLOE', 'Закрытый измененный'), ('_CLOFI', 'Закрытый измененный закрепленный'), ('_CLOF', 'Закрытый закрепленный')], default='_PRO', max_length=6, verbose_name='Статус сообщения'),
        ),
    ]
