# Generated by Django 3.2 on 2021-09-12 10:28

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('attach', models.CharField(blank=True, max_length=200, verbose_name='Прикрепленные элементы')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_version', to='chat.message')),
            ],
            options={
                'verbose_name': 'Копия сообщения перед изменением',
                'verbose_name_plural': 'Копии сообщений перед изменением',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='messageversion',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='chat_messag_created_a63fe8_brin'),
        ),
    ]
