# Generated by Django 3.2 on 2021-09-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_message_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageversion',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_transfer_version', to='chat.message'),
        ),
    ]
