# Generated by Django 3.2 on 2021-09-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_messageversion_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='transfer',
        ),
        migrations.AddField(
            model_name='message',
            name='transfer',
            field=models.ManyToManyField(blank=True, related_name='_chat_message_transfer_+', to='chat.Message'),
        ),
    ]
