# Generated by Django 3.2 on 2021-09-15 16:35

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0019_auto_20210914_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('MAN', 'Специальное'), ('_PRO', 'Обработка'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('EDI', 'Изменено'), ('_CLO', 'Закрыто модератором'), ('_DRA', 'Черновик'), ('_DELF', 'Удалённый закрепленный'), ('_DELFI', 'Удалённый измененный закрепленный'), ('_DELE', 'Удалённый измененный'), ('_CLOE', 'Закрытый измененный'), ('_CLOFI', 'Закрытый измененный закрепленный'), ('_CLOF', 'Закрытый закрепленный')], default='_PRO', max_length=6, verbose_name='Статус сообщения'),
        ),
        migrations.CreateModel(
            name='MessageFixed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Чат')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Тот, кто закрепил сообщение')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
            ],
            options={
                'verbose_name': 'Закрепленное сообщение',
                'verbose_name_plural': 'Закрепленные сообщения',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='messagefixed',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='chat_messag_created_10441e_brin'),
        ),
    ]
