# Generated by Django 3.2 on 2021-09-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_auto_20210915_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='can_add_admin',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Создатель'), (3, 'Создатель и админы')], default=1, verbose_name='Кто назначает админов'),
        ),
        migrations.AddField(
            model_name='chat',
            name='can_add_members',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все участники'), (2, 'Создатель'), (3, 'Создатель и админы')], default=1, verbose_name='Кто приглашает участников'),
        ),
        migrations.AddField(
            model_name='chat',
            name='can_edit_info',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все участники'), (2, 'Создатель'), (3, 'Создатель и админы')], default=1, verbose_name='Кто редактирует информацию'),
        ),
        migrations.AddField(
            model_name='chat',
            name='can_fix_item',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все участники'), (2, 'Создатель'), (3, 'Создатель и админы')], default=1, verbose_name='Кто закрепляет сообщения'),
        ),
        migrations.AddField(
            model_name='chat',
            name='can_mention',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все участники'), (2, 'Создатель'), (3, 'Создатель и админы')], default=1, verbose_name='Кто упоминает о беседе'),
        ),
        migrations.AddField(
            model_name='chatusers',
            name='no_disturb',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Не беспокоить до...'),
        ),
    ]
