# Generated by Django 3.2 on 2021-09-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_chatperm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatperm',
            name='can_see_post_comment',
        ),
        migrations.AddField(
            model_name='chat',
            name='can_add_design',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все участники'), (2, 'Создатель'), (3, 'Создатель и админы'), (4, 'Участники кроме'), (5, 'Некоторые участники')], default=1, verbose_name='Кто меняет дизайн'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='can_add_members',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все участники'), (2, 'Создатель'), (3, 'Создатель и админы'), (4, 'Участники кроме'), (5, 'Некоторые участники')], default=1, verbose_name='Кто приглашает участников'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='can_edit_info',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все участники'), (2, 'Создатель'), (3, 'Создатель и админы'), (4, 'Участники кроме'), (5, 'Некоторые участники')], default=1, verbose_name='Кто редактирует информацию'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='can_fix_item',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все участники'), (2, 'Создатель'), (3, 'Создатель и админы'), (4, 'Участники кроме'), (5, 'Некоторые участники')], default=1, verbose_name='Кто закрепляет сообщения'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='can_mention',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все участники'), (2, 'Создатель'), (3, 'Создатель и админы'), (4, 'Участники кроме'), (5, 'Некоторые участники')], default=1, verbose_name='Кто упоминает о беседе'),
        ),
    ]
