# Generated by Django 3.2 on 2021-09-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_auto_20210920_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatperm',
            name='can_add_info',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто редактирует информацию'),
        ),
    ]
