# Generated by Django 3.2 on 2021-10-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_alter_chatperm_can_add_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('MAN', 'Специальное'), ('_PRO', 'Обработка'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('EDI', 'Изменено'), ('_CLO', 'Закрыто модератором'), ('_DRA', 'Черновик'), ('_DELF', 'Удалённый закрепленный'), ('_DELFI', 'Удалённый измененный закрепленный'), ('_DELE', 'Удалённый измененный'), ('_CLOE', 'Закрытый измененный'), ('_CLOFI', 'Закрытый измененный закрепленный'), ('_CLOF', 'Закрытый закрепленный')], default='PUB', max_length=6, verbose_name='Статус сообщения'),
        ),
    ]
