# Generated by Django 3.2 on 2021-10-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_auto_20211013_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('PUB', 'Публичный'), ('PRI', 'Пользовательский'), ('MAN', 'Созданный персоналом'), ('_FIXT', 'Закреплённый приватный'), ('_FIXG', 'Закреплённый групповой'), ('_DELP', 'Удалённый публичный'), ('_DEL', 'Удалённый приватный'), ('_DELG', 'Удалённый групповой'), ('_DELM', 'Удалённый менеджерский'), ('_DELPF', 'Удалённый приватный закреплённый'), ('_DELGF', 'Удалённый групповой закреплённый'), ('_CLOP', 'Закрытый публичный'), ('_CLOPR', 'Закрытый приватный'), ('_CLOG', 'Закрытый групповой'), ('_CLOM', 'Закрытый менеджерский'), ('_CLOPF', 'Закрытый закреплённый приватный'), ('_CLOGF', 'Закрытый групповой закреплённый')], max_length=6, verbose_name='Тип чата'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('MAN', 'Специальное'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('EDI', 'Изменено'), ('_CLO', 'Закрыто модератором'), ('_DRA', 'Черновик'), ('_DELF', 'Удалённый закрепленный'), ('_DELFI', 'Удалённый измененный закрепленный'), ('_DELE', 'Удалённый измененный'), ('_CLOE', 'Закрытый измененный'), ('_CLOFI', 'Закрытый измененный закрепленный'), ('_CLOF', 'Закрытый закрепленный')], default='PUB', max_length=6, verbose_name='Статус сообщения'),
        ),
    ]
