# Generated by Django 3.2 on 2021-11-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_auto_20211014_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatusers',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
