# Generated by Django 3.2 on 2021-11-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_chatusers_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
