# Generated by Django 3.2 on 2021-11-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_chat_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='attach',
            field=models.TextField(blank=True, null=True),
        ),
    ]
