# Generated by Django 3.2 on 2021-11-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_chat_attach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('GRO', 'Групповой'), ('PUB', 'Публичный'), ('PRI', 'Пользовательский'), ('MAN', 'Созданный персоналом'), ('_FIXT', 'Закреплённый приватный'), ('_FIXG', 'Закреплённый групповой'), ('_DELP', 'Удалённый публичный'), ('_DEL', 'Удалённый приватный'), ('_DELG', 'Удалённый групповой'), ('_DELM', 'Удалённый менеджерский'), ('_DELPF', 'Удалённый приватный закреплённый'), ('_DELGF', 'Удалённый групповой закреплённый'), ('_CLOP', 'Закрытый публичный'), ('_CLOPR', 'Закрытый приватный'), ('_CLOG', 'Закрытый групповой'), ('_CLOM', 'Закрытый менеджерский'), ('_CLOPF', 'Закрытый закреплённый приватный'), ('_CLOGF', 'Закрытый групповой закреплённый')], max_length=6, verbose_name='Тип чата'),
        ),
    ]
