# Generated by Django 3.2 on 2021-11-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_alter_chat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatusers',
            name='is_active',
        ),
        migrations.AddField(
            model_name='chatusers',
            name='type',
            field=models.CharField(choices=[('ACT', 'Действующий'), ('EXI', 'Вышедший'), ('DEL', 'Уделенный')], default='ACT', max_length=3, verbose_name='Тип участника'),
        ),
    ]
