# Generated by Django 3.2 on 2021-11-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_auto_20211129_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('PUB', 'Публичный'), ('PRI', 'Приватный'), ('MAN', 'Служебный'), ('GRO', 'Групповой'), ('SUP', 'Техподдержка'), ('_DPUB', 'удал Публичный'), ('_DPRI', 'удал Приватный'), ('_DMAN', 'удал Служебный'), ('_DGRO', 'удал Групповой'), ('_DSUP', 'удал Техподдержка'), ('_CPUB', 'закр. Публичный'), ('_CPRI', 'закр. Приватный'), ('_CMAN', 'закр. Служебный'), ('_CGRO', 'закр. Групповой'), ('_CSUP', 'закр. Техподдержка')], max_length=6, verbose_name='Тип чата'),
        ),
    ]
