# Generated by Django 3.2 on 2021-11-30 17:10

import chat.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_alter_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, upload_to=chat.helpers.upload_to_chat_directory),
        ),
    ]
