# Generated by Django 3.2 on 2021-12-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_alter_chat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='can_add_admin',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Создатель'), (3, 'Создатель и админы')], default=3, verbose_name='Кто назначает админов'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='can_add_design',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все участники'), (2, 'Создатель'), (3, 'Создатель и админы'), (4, 'Участники кроме'), (5, 'Некоторые участники')], default=3, verbose_name='Кто меняет дизайн'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='can_edit_info',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все участники'), (2, 'Создатель'), (3, 'Создатель и админы'), (4, 'Участники кроме'), (5, 'Некоторые участники')], default=3, verbose_name='Кто редактирует информацию'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='can_fix_item',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все участники'), (2, 'Создатель'), (3, 'Создатель и админы'), (4, 'Участники кроме'), (5, 'Некоторые участники')], default=3, verbose_name='Кто закрепляет сообщения'),
        ),
    ]
