# Generated by Django 3.2 on 2021-12-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0034_auto_20211205_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-chat_message'], 'verbose_name': 'Беседа', 'verbose_name_plural': 'Беседы'},
        ),
    ]
