# Generated by Django 3.2 on 2021-12-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0039_auto_20211215_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='copy',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
    ]
