# Generated by Django 3.2 on 2021-12-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0040_auto_20211215_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('MAN', 'Служебное'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('EDI', 'Изменено'), ('_CLO', 'Закрыто модератором'), ('_DRA', 'Черновик'), ('_DELE', 'Удалённый измененный'), ('_CLOE', 'Закрытый измененный')], default='PUB', max_length=6, verbose_name='Статус сообщения'),
        ),
    ]
