# Generated by Django 3.2 on 2021-12-15 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0041_alter_message_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagefavourite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messagefavourite',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagefavourite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messagefixed',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='messagefixed',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='messagefixed',
            name='message',
        ),
        migrations.AddField(
            model_name='messageoptions',
            name='is_favourite',
            field=models.BooleanField(default=False, verbose_name='Это сообщение пользователь поместил в избранное'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('PFIX', 'Закреп опубл'), ('EFIX', 'Закреп измен'), ('MAN', 'Служебное'), ('PUB', 'Опубл'), ('_DEL', 'Удалено'), ('EDI', 'Изменено'), ('_CLO', 'Закрыто модератором'), ('_DRA', 'Черновик'), ('_DELEF', 'Удал измен закреп'), ('_DELPF', 'Удал опубл закреп'), ('_CLOEF', 'Закр измен закреп'), ('_CLOPF', 'Закр опубл закреп'), ('_CLOPF', 'Закр опубл закреп'), ('_DELE', 'Удал измен'), ('_CLOE', 'Закр измен')], default='PUB', max_length=6, verbose_name='Статус сообщения'),
        ),
        migrations.AlterField(
            model_name='messageoptions',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Это сообщение пользователь удалил'),
        ),
        migrations.AlterField(
            model_name='messageoptions',
            name='message',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='message_options', to='chat.message'),
        ),
        migrations.AlterField(
            model_name='messageoptions',
            name='user',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='message_options_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-инициатор исключения'),
        ),
        migrations.AlterUniqueTogether(
            name='messageoptions',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='messageoptions',
            index=models.Index(fields=['message', 'user'], name='chat_messag_message_d7fb93_idx'),
        ),
        migrations.DeleteModel(
            name='MessageFavourite',
        ),
        migrations.DeleteModel(
            name='MessageFixed',
        ),
    ]
