# Generated by Django 3.2 on 2021-12-21 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0042_auto_20211215_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='transfer',
        ),
        migrations.CreateModel(
            name='MessageTransfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chat.message', verbose_name='Сообщение, в котором пересылают')),
                ('transfer', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chat.message', verbose_name='Сообщение, которое пересылают')),
            ],
        ),
        migrations.AddIndex(
            model_name='messagetransfers',
            index=models.Index(fields=['message', 'transfer'], name='chat_messag_message_d08492_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagetransfers',
            unique_together={('message', 'transfer')},
        ),
    ]
