# Generated by Django 3.2 on 2021-12-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0043_auto_20211221_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='can_see_log',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все участники'), (2, 'Создатель'), (3, 'Создатель и админы'), (4, 'Участники кроме'), (5, 'Некоторые участники')], default=2, verbose_name='Кто видит логи'),
        ),
        migrations.AddField(
            model_name='chat',
            name='can_see_settings',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все участники'), (2, 'Создатель'), (3, 'Создатель и админы'), (4, 'Участники кроме'), (5, 'Некоторые участники')], default=2, verbose_name='Кто видит настройки'),
        ),
        migrations.AddField(
            model_name='chatperm',
            name='can_see_log',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто видит журнал действий'),
        ),
        migrations.AddField(
            model_name='chatperm',
            name='can_see_settings',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не активно'), (1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом')], default=0, verbose_name='Кто видит настройки'),
        ),
    ]
