# Generated by Django 3.2 on 2021-12-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0044_auto_20211223_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='can_edit_info',
        ),
        migrations.RemoveField(
            model_name='chatperm',
            name='can_add_info',
        ),
    ]
