# Generated by Django 3.2 on 2021-12-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0045_auto_20211223_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='can_add_design',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все участники'), (2, 'Создатель'), (3, 'Создатель и админы'), (4, 'Участники кроме'), (5, 'Некоторые участники')], default=2, verbose_name='Кто меняет дизайн'),
        ),
    ]
