# Generated by Django 3.2 on 2021-04-29 19:12

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('g_image', imagekit.models.fields.ProcessedImageField(upload_to='articles/%Y/%m/%d', verbose_name='Главное изображение')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('status', models.CharField(choices=[('PRO', 'Обработка'), ('PUB', 'Опубликовано'), ('TDEL', 'Удалено'), ('PRI', 'Приватно'), ('TCLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('TDELP', 'Удалённый приватный'), ('TDELM', 'Удалённый менеджерский'), ('TCLOP', 'Закрытый приватный'), ('TCLOM', 'Закрытый менеджерский')], default='PRO', max_length=5, verbose_name='Статус статьи')),
                ('communities', models.ManyToManyField(blank=True, related_name='communities_article', to='communities.Community')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('users', models.ManyToManyField(blank=True, related_name='users_article', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='article_art_created_37b6b0_brin'),
        ),
    ]
