# Generated by Django 3.1 on 2020-08-24 19:22

import ckeditor_uploader.fields
from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('g_image', imagekit.models.fields.ProcessedImageField(upload_to='articles/%Y/%m/%d', verbose_name='Главное изображение')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='uuid')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('status', models.CharField(choices=[('D', 'Черновик'), ('PG', 'Обработка'), ('P', 'Опубликована'), ('A', 'Архивирована')], default='P', max_length=2, verbose_name='Статус статьи')),
                ('creator', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='article_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='article_art_created_37b6b0_brin'),
        ),
    ]
