# Generated by Django 2.2.5 on 2019-11-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='g_image',
        ),
    ]
