# Generated by Django 2.2.5 on 2019-10-06 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='articlecommentmute',
            name='post_comment',
        ),
        migrations.RemoveField(
            model_name='articlecommentusermention',
            name='post_comment',
        ),
        migrations.RemoveField(
            model_name='articlemute',
            name='post',
        ),
        migrations.RemoveField(
            model_name='articlerepost',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='articlerepost',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='articleusermention',
            name='post',
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='article.Article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecommentmute',
            name='article_comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='article.ArticleComment', verbose_name='Статья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecommentusermention',
            name='article_comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_mentions', to='article.ArticleComment', verbose_name='Статья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlemute',
            name='article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='article.Article', verbose_name='Статья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleusermention',
            name='article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_mentions', to='article.Article', verbose_name='Статья'),
            preserve_default=False,
        ),
    ]
