# Generated by Django 2.2.5 on 2019-10-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleRepost',
        ),
    ]
