# Generated by Django 3.2 on 2021-05-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='status',
            new_name='type',
        ),
    ]
