# Generated by Django 2.2.5 on 2019-10-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20191006_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlerepost',
            name='article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='article_repost', to='article.Article'),
            preserve_default=False,
        ),
    ]
