# Generated by Django 3.1 on 2020-08-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200825_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='community',
        ),
    ]
