# Generated by Django 2.2.16 on 2020-09-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_message_post'),
        ('article', '0002_article_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='message',
            field=models.ManyToManyField(blank=True, related_name='attached_message', to='chat.Message'),
        ),
    ]
