# Generated by Django 2.2.16 on 2020-09-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='item_attach',
            new_name='post',
        ),
    ]
