# Generated by Django 2.2.5 on 2019-10-06 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlerepost_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_replies', to='article.ArticleComment', verbose_name='Родительский комментарий'),
        ),
    ]
