# Generated by Django 2.2.5 on 2019-10-09 14:40

import article.helpers
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20191006_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=article.helpers.upload_to_article_image_directory, verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('D', 'Черновик'), ('PG', 'Обработка'), ('P', 'Опубликована'), ('A', 'Архивирована')], default='D', max_length=2, verbose_name='Статус статьи'),
        ),
    ]
