# Generated by Django 2.2.5 on 2019-10-09 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20191009_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='modified',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
