# Generated by Django 2.2.5 on 2019-10-10 10:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20191009_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_medium',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
