# Generated by Django 2.2.5 on 2019-10-10 18:16

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20191010_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlerepost',
            options={'ordering': ['-id']},
        ),
        migrations.AddIndex(
            model_name='articlecomment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='article_art_created_7d5288_brin'),
        ),
        migrations.AddIndex(
            model_name='articlerepost',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='article_art_created_812ec2_brin'),
        ),
    ]
