# Generated by Django 2.2.5 on 2019-10-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20191010_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments_enabled',
        ),
        migrations.RemoveField(
            model_name='article',
            name='community',
        ),
    ]
