# Generated by Django 2.2.5 on 2019-10-10 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0011_auto_20191010_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlerepost',
            options={},
        ),
        migrations.AlterField(
            model_name='articlecommentmute',
            name='article_comment',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='article.ArticleComment', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlecommentmute',
            name='muter',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='article_comment_mutes', to=settings.AUTH_USER_MODEL, verbose_name='Кто заглушил'),
        ),
        migrations.AlterField(
            model_name='articlecommentusermention',
            name='article_comment',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_mentions', to='article.ArticleComment', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlecommentusermention',
            name='user',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='article_comment_mentions', to=settings.AUTH_USER_MODEL, verbose_name='Упомянутый в комментарии'),
        ),
        migrations.AlterField(
            model_name='articlemute',
            name='article',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='article.Article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlemute',
            name='muter',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='article_mutes', to=settings.AUTH_USER_MODEL, verbose_name='Кто заглушил'),
        ),
        migrations.AlterField(
            model_name='articlerepost',
            name='article',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='article_repost', to='article.Article'),
        ),
        migrations.AlterField(
            model_name='articlerepost',
            name='author',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articleusermention',
            name='article',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_mentions', to='article.Article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articleusermention',
            name='user',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='article_mentions', to=settings.AUTH_USER_MODEL, verbose_name='Упоминаемый'),
        ),
        migrations.AlterUniqueTogether(
            name='articlecommentmute',
            unique_together={('article_comment', 'muter')},
        ),
        migrations.AlterUniqueTogether(
            name='articlecommentusermention',
            unique_together={('user', 'article_comment')},
        ),
        migrations.AlterUniqueTogether(
            name='articlemute',
            unique_together={('article', 'muter')},
        ),
        migrations.AlterUniqueTogether(
            name='articlerepost',
            unique_together={('author', 'article')},
        ),
        migrations.AlterUniqueTogether(
            name='articleusermention',
            unique_together={('user', 'article')},
        ),
    ]
