# Generated by Django 2.2.5 on 2019-10-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20191011_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
