# Generated by Django 2.2.5 on 2019-10-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_article_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content_hard',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_lite',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_medium',
        ),
    ]
