# Generated by Django 2.2.5 on 2019-10-15 16:22

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20191015_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='articles/%Y/%m/%d', verbose_name='Главное изображение'),
        ),
    ]
