# Generated by Django 2.2.5 on 2019-10-16 12:11

import ckeditor_uploader.fields
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20191015_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='articles/%Y/%m/%d', verbose_name='Главное изображение'),
            preserve_default=False,
        ),
    ]
