# Generated by Django 2.2.16 on 2020-09-09 18:23

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import docs.helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('goods', '0002_auto_20200906_1514'),
        ('gallery', '0002_auto_20200906_1514'),
        ('video', '0002_auto_20200906_1514'),
        ('posts', '0003_auto_20200908_1912'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('MA', 'Основной список'), ('LI', 'Пользовательский список')], default='LI', max_length=5, verbose_name='Тип листа')),
                ('order', models.PositiveIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('is_public', models.BooleanField(default=True, verbose_name='Виден другим')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_doclist', to='communities.Community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_doclist', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('post', models.ManyToManyField(blank=True, related_name='post_doclist', to='posts.Post')),
            ],
            options={
                'verbose_name': 'список документов',
                'ordering': ['order'],
                'verbose_name_plural': 'списки документов',
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to=docs.helpers.upload_to_doc_directory, verbose_name='Документ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('type', models.CharField(choices=[('P', 'Личный документ'), ('S', 'Учебный документ'), ('B', 'Книга'), ('O', 'Другой документ')], default='P', max_length=2)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('good_comment', models.ManyToManyField(blank=True, related_name='good_comment_doc', to='goods.GoodComment')),
                ('item', models.ManyToManyField(blank=True, related_name='item_doc', to='posts.Post')),
                ('item_comment', models.ManyToManyField(blank=True, related_name='comment_doc', to='posts.PostComment')),
                ('list', models.ManyToManyField(blank='True', related_name='doc_list', to='docs.DocList')),
                ('message', models.ManyToManyField(blank=True, related_name='message_doc', to='chat.Message')),
                ('photo_comment', models.ManyToManyField(blank=True, related_name='gallery_comment_doc', to='gallery.PhotoComment')),
                ('video_comment', models.ManyToManyField(blank=True, related_name='video_comment_doc', to='video.VideoComment')),
            ],
            options={
                'verbose_name': 'Документ',
                'ordering': ['-created'],
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.AddIndex(
            model_name='doc',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='docs_doc_created_1fe2f0_brin'),
        ),
    ]
