# Generated by Django 2.2.16 on 2020-09-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
    ]
