# Generated by Django 2.2.16 on 2020-09-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20200909_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc2',
            name='is_community',
            field=models.BooleanField(default=False, verbose_name='Пренадлежит к сообществу'),
        ),
    ]
