# Generated by Django 3.2 on 2021-05-05 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0003_auto_20210430_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doclist',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_lists_community', to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AlterField(
            model_name='doclist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_lists_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
