# Generated by Django 2.2.16 on 2020-09-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_message_post'),
        ('docs', '0004_doc2_is_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='doclist',
            name='message',
            field=models.ManyToManyField(blank=True, related_name='message_doclist', to='chat.Message'),
        ),
    ]
