# Generated by Django 3.2 on 2021-06-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_doc_type_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doclist',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
