# Generated by Django 3.2 on 2021-06-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_auto_20210613_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doclist',
            options={'verbose_name': 'список документов', 'verbose_name_plural': 'списки документов'},
        ),
        migrations.RemoveField(
            model_name='doclist',
            name='order',
        ),
    ]
