# Generated by Django 3.2 on 2021-06-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_auto_20210614_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'ordering': ['-order'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
