# Generated by Django 3.2 on 2021-09-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_auto_20210927_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='doclist',
            name='can_see_el',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья и друзья друзей'), (4, 'Только я'), (5, 'Друзья, кроме'), (6, 'Некоторые друзья')], default=1, verbose_name='Кто видит документы'),
        ),
        migrations.AddField(
            model_name='doclist',
            name='copy_el',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья и друзья друзей'), (4, 'Только я'), (5, 'Друзья, кроме'), (6, 'Некоторые друзья')], default=1, verbose_name='Кто копирует документы'),
        ),
        migrations.AddField(
            model_name='doclist',
            name='create_el',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья и друзья друзей'), (4, 'Только я'), (5, 'Друзья, кроме'), (6, 'Некоторые друзья')], default=4, verbose_name='Кто создает документы и потом с этими документами работает'),
        ),
    ]
