# Generated by Django 3.2 on 2021-10-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_auto_20211007_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='type',
            field=models.CharField(choices=[('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('_CLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('_DELM', 'Удалённый менеджерский'), ('_CLOM', 'Закрытый менеджерский')], max_length=5),
        ),
        migrations.AlterField(
            model_name='doc',
            name='type_2',
            field=models.CharField(choices=[('BOO', 'Книга'), ('ART', 'Статья'), ('PU', 'Заметка'), ('FIL', 'Файл'), ('OTH', 'Другое')], max_length=5),
        ),
        migrations.AlterField(
            model_name='doclist',
            name='type',
            field=models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('MAN', 'Созданный персоналом'), ('_DEL', 'Удалённый'), ('_DELM', 'Удалённый менеджерский'), ('_CLO', 'Закрытый менеджером'), ('_CLOM', 'Закрытый основной'), ('_CLOMA', 'Закрытый менеджерский')], max_length=6, verbose_name='Тип списка'),
        ),
    ]
