# Generated by Django 2.2.5 on 2019-10-31 13:06

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=32)),
                ('order', models.IntegerField(default=100)),
                ('created', models.DateTimeField(editable=False)),
                ('is_reaction_group', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'группы смайликов',
                'verbose_name': 'группа смайликоа',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='uuid')),
                ('comments_enabled', models.BooleanField(default=True, verbose_name='Разрешить комментарии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Изменено')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыто')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('is_repost', models.BooleanField(default=False, verbose_name='Это репост')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('creator', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='main.Item')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'записи',
                'verbose_name': 'запись',
            },
        ),
        migrations.CreateModel(
            name='ItemComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False, verbose_name='Изменено')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удаено')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ItemComment', verbose_name='Родительский комментарий')),
            ],
            options={
                'verbose_name_plural': 'комментарии к записи',
                'verbose_name': 'комментарий к записи',
            },
        ),
        migrations.CreateModel(
            name='ProxyBlacklistedDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=16)),
                ('image', models.ImageField(upload_to='emoji/')),
                ('created', models.DateTimeField(editable=False)),
                ('order', models.IntegerField(default=100)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emojis', to='main.EmojiGroup')),
            ],
            options={
                'verbose_name_plural': 'смайлики',
                'verbose_name': 'смайлик',
            },
        ),
        migrations.CreateModel(
            name='ItemReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='main.Emoji')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='main.Item')),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reactor', 'item', 'emoji')},
                'verbose_name_plural': 'реакции к записям',
                'verbose_name': 'реакция к записи',
            },
        ),
        migrations.CreateModel(
            name='ItemCommentReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_reactions', to='main.Emoji')),
                ('item_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='main.ItemComment')),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reactor', 'item_comment', 'emoji')},
                'verbose_name_plural': 'реакции на комментарии',
                'verbose_name': 'реакция на комментарий',
            },
        ),
        migrations.AddIndex(
            model_name='itemcomment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='main_itemco_created_ca7994_brin'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='main_item_created_848de4_brin'),
        ),
    ]
