# Generated by Django 2.2.5 on 2019-10-27 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreaction',
            name='emoji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_emoji', to='main.Emoji'),
        ),
        migrations.AlterField(
            model_name='itemreaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_react', to='main.Item'),
        ),
        migrations.AlterField(
            model_name='itemreaction',
            name='reactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactor', to=settings.AUTH_USER_MODEL),
        ),
    ]
