# Generated by Django 2.2.5 on 2019-12-01 14:33

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCommentPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_comment_photo', imagekit.models.fields.ProcessedImageField(upload_to='comment_photos/%Y/%m/%d')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ItemComment')),
            ],
        ),
        migrations.DeleteModel(
            name='TopPost',
        ),
    ]
