# Generated by Django 2.2.5 on 2019-10-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191019_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=32)),
                ('order', models.IntegerField(default=100)),
                ('created', models.DateTimeField(editable=False)),
                ('is_reaction_group', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=16)),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(editable=False)),
                ('order', models.IntegerField(default=100)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emojis', to='main.EmojiGroup')),
            ],
        ),
    ]
