# Generated by Django 2.2.5 on 2019-10-27 21:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20191027_2132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemreaction',
            unique_together={('reactor', 'item', 'emoji')},
        ),
    ]
