# Generated by Django 2.2.5 on 2019-11-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('D', 'Черновик'), ('PG', 'Обработка'), ('P', 'Опубликована'), ('A', 'Архивирована')], default='P', max_length=2, verbose_name='Статус статьи'),
        ),
    ]
