# Generated by Django 2.2.5 on 2019-10-10 17:00

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_remove_userinvite_badge'),
        ('main', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='main_item_created_848de4_brin'),
        ),
    ]
