# Generated by Django 2.2.5 on 2019-10-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_repost',
            field=models.BooleanField(default=False, verbose_name='Это репост'),
        ),
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='main.Item'),
        ),
    ]
