# Generated by Django 2.2.5 on 2019-12-02 11:41

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191201_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcommentphoto',
            name='item_comment_photo2',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='comment_photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
