# Generated by Django 2.2.5 on 2019-10-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_emoji_emojigroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyBlacklistedDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
