# Generated by Django 2.2.5 on 2019-10-28 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191027_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreaction',
            name='emoji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Emoji'),
        ),
        migrations.AlterField(
            model_name='itemreaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
        migrations.AlterField(
            model_name='itemreaction',
            name='reactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
