# Generated by Django 2.2.5 on 2019-10-19 16:29

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_proxyblacklisteddomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCommentReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='itemcomment',
            name='main_commen_created_c5fc21_brin',
        ),
        migrations.AddIndex(
            model_name='itemcomment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='main_itemco_created_ca7994_brin'),
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='ItemComment',
        ),
        migrations.AddField(
            model_name='itemreaction',
            name='emoji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='main.Emoji'),
        ),
        migrations.AddField(
            model_name='itemreaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='main.Item'),
        ),
        migrations.AddField(
            model_name='itemreaction',
            name='reactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcommentreaction',
            name='emoji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_reactions', to='main.Emoji'),
        ),
        migrations.AddField(
            model_name='itemcommentreaction',
            name='item_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='main.ItemComment'),
        ),
        migrations.AddField(
            model_name='itemcommentreaction',
            name='reactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='itemreaction',
            unique_together={('reactor', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcommentreaction',
            unique_together={('reactor', 'item_comment')},
        ),
    ]
