# Generated by Django 2.2.5 on 2019-10-28 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20191028_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emoji',
            options={'verbose_name': 'смайлик', 'verbose_name_plural': 'смайлики'},
        ),
        migrations.AlterModelOptions(
            name='emojigroup',
            options={'verbose_name': 'группа смайликоа', 'verbose_name_plural': 'группы смайликов'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id'], 'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
        migrations.AlterModelOptions(
            name='itemcomment',
            options={'verbose_name': 'комментарий к записи', 'verbose_name_plural': 'комментарии к записи'},
        ),
        migrations.AlterModelOptions(
            name='itemcommentreaction',
            options={'verbose_name': 'реакция на комментарий', 'verbose_name_plural': 'реакции на комментарии'},
        ),
        migrations.AlterModelOptions(
            name='itemreaction',
            options={'verbose_name': 'реакция к записи', 'verbose_name_plural': 'реакции к записям'},
        ),
        migrations.AlterField(
            model_name='itemreaction',
            name='emoji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='main.Emoji'),
        ),
        migrations.AlterField(
            model_name='itemreaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='main.Item'),
        ),
        migrations.AlterField(
            model_name='itemreaction',
            name='reactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='itemcommentreaction',
            unique_together={('reactor', 'item_comment', 'emoji')},
        ),
    ]
