# Generated by Django 2.2.5 on 2019-11-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191109_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created'], 'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
    ]
