# Generated by Django 2.2.5 on 2019-12-02 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_itemcommentphoto_item_comment_photo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcommentphoto',
            name='parent',
            field=models.OneToOneField(blank=True, limit_choices_to=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ItemComment'),
        ),
    ]
