# Generated by Django 2.2.5 on 2019-11-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191109_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
    ]
