# Generated by Django 2.2.5 on 2019-12-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191202_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcommentphoto',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ItemComment'),
        ),
    ]
