# Generated by Django 2.2.5 on 2019-10-29 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_auto_20191029_1427'),
        ('main', '0005_auto_20191028_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='community',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.Community', verbose_name='Сообщество'),
        ),
    ]
