# Generated by Django 2.2.5 on 2019-11-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191109_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcomment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='itemcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.ItemComment', verbose_name='Родительский комментарий'),
        ),
    ]
