# Generated by Django 2.2.5 on 2019-10-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191010_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_fixed',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
    ]
