# Generated by Django 2.2.5 on 2019-12-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191203_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='itemcomment',
            name='votes',
        ),
    ]
