# Generated by Django 2.2.5 on 2019-11-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191114_1444'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemreaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itemreaction',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='itemreaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemreaction',
            name='reactor',
        ),
        migrations.DeleteModel(
            name='ItemCommentReaction',
        ),
        migrations.DeleteModel(
            name='ItemReaction',
        ),
    ]
