# Generated by Django 2.2.5 on 2019-12-04 12:35

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191204_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcomment',
            name='item_comment_photo',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='comment_photos/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcomment',
            name='item_comment_photo2',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='comment_photos/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemCommentPhoto',
        ),
    ]
