# Generated by Django 2.2.5 on 2019-12-04 13:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191204_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcomment',
            name='item_comment_photo',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='comment_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='itemcomment',
            name='item_comment_photo2',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='comment_photos/%Y/%m/%d'),
        ),
    ]
