# Generated by Django 2.2.5 on 2019-11-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191129_1148'),
    ]
