# Generated by Django 2.2.5 on 2019-10-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191017_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id']},
        ),
    ]
