# Generated by Django 2.2.5 on 2019-12-04 13:25

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191204_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcomment',
            name='item_comment_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='', upload_to='comment_photos/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemcomment',
            name='item_comment_photo2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='', upload_to='comment_photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
