# Generated by Django 2.2.5 on 2019-11-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_likedislike'),
        ('main', '0009_item_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcomment',
            name='votes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='comments', to='common.LikeDislike'),
        ),
    ]
