# Generated by Django 2.2.5 on 2019-11-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_itemcomment_votes'),
    ]
