# Generated by Django 2.2.5 on 2019-12-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191204_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcomment',
            name='text',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
