# Generated by Django 2.2.5 on 2019-12-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191204_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcomment',
            name='item_comment_photo',
        ),
        migrations.RemoveField(
            model_name='itemcomment',
            name='item_comment_photo2',
        ),
    ]
