# Generated by Django 2.2.5 on 2019-11-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191129_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='votes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='items_vote', to='common.ItemVotes'),
        ),
    ]
