# Generated by Django 2.2.5 on 2019-11-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191129_1518'),
    ]
