# Generated by Django 2.2.5 on 2019-11-30 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191129_1618'),
    ]
