# Generated by Django 2.2.5 on 2020-03-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191211_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='item',
            name='views',
        ),
    ]
