# Generated by Django 2.2.5 on 2020-06-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200311_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comment_attach',
            field=models.ManyToManyField(blank=True, related_name='attached_comment', to='main.ItemComment'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_attach',
            field=models.ManyToManyField(blank=True, related_name='_item_item_attach_+', to='main.Item'),
        ),
    ]
