# Generated by Django 2.2.5 on 2020-06-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200607_1957'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemmute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itemmute',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemmute',
            name='muter',
        ),
        migrations.DeleteModel(
            name='ItemCommentMute',
        ),
        migrations.DeleteModel(
            name='ItemMute',
        ),
    ]
