# Generated by Django 2.2.5 on 2020-06-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200613_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='comments_enabled',
        ),
    ]
