# Generated by Django 2.2.5 on 2019-09-11 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создан')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionCircle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circles.Circle', verbose_name='Круг')),
            ],
        ),
    ]
