# Generated by Django 2.2.5 on 2019-09-03 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='connections',
            field=models.ManyToManyField(db_index=True, related_name='circles', through='circles.ConnectionCircle', to='connections.Connection', verbose_name='Соединение'),
        ),
        migrations.AddField(
            model_name='connectioncircle',
            name='connection',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='connections.Connection', verbose_name='Соединение'),
            preserve_default=False,
        ),
    ]
