# Generated by Django 2.2.5 on 2019-09-11 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connections', '0001_initial'),
        ('posts', '0001_initial'),
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='connections',
            field=models.ManyToManyField(db_index=True, related_name='circles', through='circles.ConnectionCircle', to='connections.Connection', verbose_name='Соединение'),
        ),
        migrations.AddField(
            model_name='circle',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circles', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='circle',
            name='posts',
            field=models.ManyToManyField(db_index=True, related_name='circles', to='posts.Post', verbose_name='Посты'),
        ),
        migrations.AddField(
            model_name='connectioncircle',
            name='connection',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='connections.Connection', verbose_name='Соединение'),
            preserve_default=False,
        ),
    ]
