# Generated by Django 2.2.5 on 2019-09-05 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circles', '0002_auto_20190903_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circles', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='circle',
            name='posts',
            field=models.ManyToManyField(db_index=True, related_name='circles', to='posts.Post', verbose_name='Посты'),
        ),
    ]
