# Generated by Django 2.2.5 on 2019-09-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_auto_20190905_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='posts',
        ),
    ]
