# Generated by Django 2.2.5 on 2019-10-03 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=300, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Когда создана')),
                ('avatar', models.ImageField(null=True, upload_to='', verbose_name='Аватар')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('communities', models.ManyToManyField(blank=True, related_name='categories', to='communities.Community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
        ),
    ]
