# Generated by Django 2.2.5 on 2019-09-11 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=300, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Когда создана')),
                ('avatar', models.ImageField(null=True, upload_to='', verbose_name='Аватар')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
            ],
        ),
    ]
