# Generated by Django 2.2.5 on 2019-10-18 19:44

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import goods.helpers
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Item')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание товара')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена товара')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=goods.helpers.upload_to_good_image_directory, verbose_name='Главное изображение')),
                ('image2', imagekit.models.fields.ProcessedImageField(null=True, upload_to=goods.helpers.upload_to_good_image_directory, verbose_name='Изображение 2')),
                ('image3', imagekit.models.fields.ProcessedImageField(null=True, upload_to=goods.helpers.upload_to_good_image_directory, verbose_name='Изображение 3')),
                ('image4', imagekit.models.fields.ProcessedImageField(null=True, upload_to=goods.helpers.upload_to_good_image_directory, verbose_name='Изображение 4')),
                ('image5', imagekit.models.fields.ProcessedImageField(null=True, upload_to=goods.helpers.upload_to_good_image_directory, verbose_name='Изображение 5')),
                ('image6', imagekit.models.fields.ProcessedImageField(null=True, upload_to=goods.helpers.upload_to_good_image_directory, verbose_name='Изображение 6')),
                ('image7', imagekit.models.fields.ProcessedImageField(null=True, upload_to=goods.helpers.upload_to_good_image_directory, verbose_name='Изображение 7')),
                ('is_active', models.BooleanField(default=False, verbose_name='Товар активен')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Товар не актуален')),
                ('is_reklama', models.BooleanField(default=False, verbose_name='Это реклама')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
            bases=('main.item',),
        ),
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
                ('image', models.ImageField(blank=True, upload_to='goods/list', verbose_name='Изображение')),
            ],
            options={
                'ordering': ['order', 'name'],
                'verbose_name': 'категория товаров',
                'verbose_name_plural': 'категории товаров',
            },
        ),
        migrations.CreateModel(
            name='GoodSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подкатегории')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер подкатегории')),
                ('image', models.ImageField(blank=True, upload_to='sub_category/list', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodCategory', verbose_name='Категория-родитель')),
            ],
        ),
        migrations.CreateModel(
            name='GoodRepost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_repost', to='goods.Good')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodSubCategory', verbose_name='Подкатегория'),
        ),
        migrations.AddIndex(
            model_name='goodrepost',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='goods_goodr_created_e115dd_brin'),
        ),
    ]
