# Generated by Django 2.2.5 on 2019-10-06 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название категории')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядковый номер')),
                ('image', models.ImageField(blank=True, upload_to='goods/list', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'категория товаров',
                'ordering': ['order', 'name'],
                'verbose_name_plural': 'категории товаров',
            },
        ),
        migrations.CreateModel(
            name='GoodSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название подкатегории')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядковый номер подкатегории')),
                ('image', models.ImageField(blank=True, upload_to='sub_category/list', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodCategory', verbose_name='Категория-родитель')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='uuid')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание товара')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена товара')),
                ('img0', models.ImageField(blank=True, upload_to='goods/%Y/%m/%d')),
                ('img1', models.ImageField(blank=True, upload_to='goods/%Y/%m/%d')),
                ('img2', models.ImageField(blank=True, upload_to='goods/%Y/%m/%d')),
                ('img3', models.ImageField(blank=True, upload_to='goods/%Y/%m/%d')),
                ('img4', models.ImageField(blank=True, upload_to='goods/%Y/%m/%d')),
                ('img5', models.ImageField(blank=True, upload_to='goods/%Y/%m/%d')),
                ('img6', models.ImageField(blank=True, upload_to='goods/%Y/%m/%d')),
                ('img7', models.ImageField(blank=True, upload_to='goods/%Y/%m/%d')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('is_active', models.BooleanField(default=False, verbose_name='Товар активен')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Товар не актуален')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Опубликованo')),
                ('is_reklama', models.BooleanField(default=False, verbose_name='Это реклама')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodSubCategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
