# Generated by Django 2.2.5 on 2019-11-03 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20191101_1455'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='community',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.Community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='good',
            name='status',
            field=models.CharField(choices=[('D', 'Отложен'), ('P', 'Опубликован'), ('S', 'Продан')], default='P', max_length=2, verbose_name='Статус'),
        ),
    ]
