# Generated by Django 2.2.5 on 2019-10-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='comments_enabled',
            field=models.BooleanField(default=True, verbose_name='Разрешить комментарии'),
        ),
        migrations.AddField(
            model_name='good',
            name='community',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.Community', verbose_name='Сообщество'),
        ),
    ]
