# Generated by Django 2.2.5 on 2019-10-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsubcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Подкатегория товаров', 'verbose_name_plural': 'Подкатегории товаров'},
        ),
    ]
