# Generated by Django 2.2.5 on 2020-03-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_good_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='views',
        ),
    ]
