# Generated by Django 2.2.16 on 2020-09-13 11:17

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_post'),
        ('posts', '0005_auto_20200912_1005'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0002_auto_20200906_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='community',
        ),
        migrations.RemoveField(
            model_name='good',
            name='uuid',
        ),
        migrations.CreateModel(
            name='GoodAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='uuid')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('is_public', models.BooleanField(default=True, verbose_name='Виден другим')),
                ('type', models.CharField(choices=[('MA', 'Основной альбом'), ('AL', 'Пользовательский альбом')], default='MA', max_length=5, verbose_name='Тип альбома')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('community', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_album_community', to='communities.Community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_album_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('post', models.ManyToManyField(blank=True, related_name='post_good_album', to='posts.Post')),
            ],
            options={
                'verbose_name_plural': 'Подборки товаров',
                'verbose_name': 'Подборка товаров',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='good_album', to='goods.GoodAlbum', verbose_name='Подборка'),
        ),
        migrations.AddIndex(
            model_name='goodalbum',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='goods_gooda_created_161801_brin'),
        ),
    ]
