# Generated by Django 3.2 on 2021-04-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20210430_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='status',
            field=models.CharField(choices=[('_PRO', 'Обработка'), ('_DRA', 'Черновик'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('PRI', 'Приватно'), ('_CLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('_DELP', 'Удалённый приватный'), ('_DELM', 'Удалённый менеджерский'), ('_CLOP', 'Закрытый приватный'), ('_CLOM', 'Закрытый менеджерский')], default='_PRO', max_length=6, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='goodcomment',
            name='status',
            field=models.CharField(choices=[('PUB', 'Опубликовано'), ('EDI', 'Изменённый'), ('_PRO', 'Обработка'), ('_DEL', 'Удалённый'), ('_DELE', 'Удалённый изменённый'), ('_CLO', 'Закрытый менеджером'), ('_CLOE', 'Закрытый изменённый')], default='_PRO', max_length=5, verbose_name='Тип альбома'),
        ),
        migrations.AlterField(
            model_name='goodlist',
            name='type',
            field=models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('PRI', 'Приватный'), ('MAN', 'Созданный персоналом'), ('_PRO', 'Обработка'), ('_DEL', 'Удалённый'), ('_DELP', 'Удалённый приватный'), ('_DELM', 'Удалённый менеджерский'), ('_CLO', 'Закрытый менеджером'), ('_CLOP', 'Закрытый приватный'), ('_CLOM', 'Закрытый основной'), ('_CLOMA', 'Закрытый менеджерский')], default='_PRO', max_length=6, verbose_name='Тип альбома'),
        ),
    ]
