# Generated by Django 2.2.5 on 2019-10-10 10:50

from django.db import migrations, models
import goods.helpers
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20191006_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='img0',
        ),
        migrations.RemoveField(
            model_name='good',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='good',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='good',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='good',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='good',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='good',
            name='img6',
        ),
        migrations.RemoveField(
            model_name='good',
            name='img7',
        ),
        migrations.AddField(
            model_name='good',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to=goods.helpers.upload_to_good_image_directory, verbose_name='Главное изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=goods.helpers.upload_to_good_image_directory, verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='good',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=goods.helpers.upload_to_good_image_directory, verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='good',
            name='image4',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=goods.helpers.upload_to_good_image_directory, verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='good',
            name='image5',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=goods.helpers.upload_to_good_image_directory, verbose_name='Изображение 5'),
        ),
        migrations.AddField(
            model_name='good',
            name='image6',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=goods.helpers.upload_to_good_image_directory, verbose_name='Изображение 6'),
        ),
        migrations.AddField(
            model_name='good',
            name='image7',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=goods.helpers.upload_to_good_image_directory, verbose_name='Изображение 7'),
        ),
        migrations.AlterField(
            model_name='goodcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='goodsubcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название подкатегории'),
        ),
        migrations.AlterField(
            model_name='goodsubcategory',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер подкатегории'),
        ),
    ]
