# Generated by Django 2.2.5 on 2019-11-12 18:25

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('goods', '0003_auto_20191109_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False, verbose_name='Изменено')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удаено')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Good')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodComment', verbose_name='Родительский комментарий')),
            ],
            options={
                'verbose_name': 'комментарий к записи',
                'verbose_name_plural': 'комментарии к записи',
            },
        ),
        migrations.CreateModel(
            name='GoodReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_reactions', to='common.Emoji')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_reactions', to='goods.Good')),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reactor', 'good', 'emoji')},
                'verbose_name': 'реакция к записи',
                'verbose_name_plural': 'реакции к записям',
            },
        ),
        migrations.CreateModel(
            name='GoodCommentReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('emoji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_comment_reactions', to='common.Emoji')),
                ('good_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_reactions', to='goods.GoodComment')),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_comment_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reactor', 'good_comment', 'emoji')},
                'verbose_name': 'реакция на комментарий',
                'verbose_name_plural': 'реакции на комментарии',
            },
        ),
        migrations.AddIndex(
            model_name='goodcomment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='goods_goodc_created_4f76f1_brin'),
        ),
    ]
