# Generated by Django 2.2.5 on 2019-10-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20191010_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='uuid',
            new_name='good_uuid',
        ),
    ]
