# Generated by Django 2.2.5 on 2020-06-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_good_views'),
    ]

    operations = [
    ]
