# Generated by Django 3.2 on 2021-05-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20210430_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='ad_views',
            new_name='ad_view',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='reposts',
            new_name='repost',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='views',
            new_name='view',
        ),
        migrations.RenameField(
            model_name='goodcomment',
            old_name='reposts',
            new_name='repost',
        ),
        migrations.AddField(
            model_name='good',
            name='dislike',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во дизлайков'),
        ),
        migrations.AddField(
            model_name='good',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
        migrations.AddField(
            model_name='goodcomment',
            name='dislike',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во дизлайков'),
        ),
        migrations.AddField(
            model_name='goodcomment',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
    ]
