# Generated by Django 2.2.16 on 2020-09-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200913_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodalbum',
            name='is_public',
        ),
    ]
