# Generated by Django 2.2.5 on 2019-11-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20191112_1825'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goodreaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='goodreaction',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='goodreaction',
            name='good',
        ),
        migrations.RemoveField(
            model_name='goodreaction',
            name='reactor',
        ),
        migrations.DeleteModel(
            name='GoodCommentReaction',
        ),
        migrations.DeleteModel(
            name='GoodReaction',
        ),
    ]
