# Generated by Django 2.2.5 on 2019-10-22 11:33

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20191022_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='goods/%Y/%m/%d', verbose_name='изображение 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='goods/%Y/%m/%d', verbose_name='изображение 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='image4',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='goods/%Y/%m/%d', verbose_name='изображение 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='image5',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='goods/%Y/%m/%d', verbose_name='изображение 5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='goods/%Y/%m/%d', verbose_name='Главное изображение'),
        ),
    ]
