# Generated by Django 2.2.5 on 2020-06-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200603_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Цена товара'),
        ),
    ]
