# Generated by Django 2.2.16 on 2020-09-20 18:55

from django.db import migrations
import goods.helpers
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20200913_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=goods.helpers.upload_to_good_directory, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=goods.helpers.upload_to_good_directory, verbose_name='изображение 2'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=goods.helpers.upload_to_good_directory, verbose_name='изображение 3'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image4',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=goods.helpers.upload_to_good_directory, verbose_name='изображение 4'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image5',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=goods.helpers.upload_to_good_directory, verbose_name='изображение 5'),
        ),
    ]
