# Generated by Django 2.2.5 on 2019-10-22 13:14

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20191022_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='goods/%Y/%m/%d', verbose_name='изображение 2'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='goods/%Y/%m/%d', verbose_name='изображение 3'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image4',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='goods/%Y/%m/%d', verbose_name='изображение 4'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image5',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='goods/%Y/%m/%d', verbose_name='изображение 5'),
        ),
    ]
