# Generated by Django 2.2.5 on 2019-10-10 18:16

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20191010_1716'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='goodcomment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='goods_goodc_created_4f76f1_brin'),
        ),
        migrations.AddIndex(
            model_name='goodrepost',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='goods_goodr_created_e115dd_brin'),
        ),
    ]
