# Generated by Django 3.2 on 2021-05-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_good_community'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='status',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='goodcomment',
            old_name='status',
            new_name='type',
        ),
    ]
