# Generated by Django 2.2.5 on 2019-10-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20191010_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcategory',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
