# Generated by Django 2.2.5 on 2019-10-25 10:30

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20191022_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['-created'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddIndex(
            model_name='good',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='goods_good_created_414618_brin'),
        ),
    ]
