# Generated by Django 2.2.5 on 2019-10-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20191010_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='community',
        ),
    ]
