# Generated by Django 3.2 on 2021-06-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20210613_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodlist',
            name='order',
        ),
    ]
