# Generated by Django 2.2.5 on 2019-10-11 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_remove_good_community'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='good_uuid',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='goodcomment',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodcomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
    ]
