# Generated by Django 2.2.5 on 2019-10-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20191011_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='uuid',
        ),
        migrations.DeleteModel(
            name='GoodComment',
        ),
    ]
