# Generated by Django 3.2 on 2021-10-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_auto_20211007_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodcomment',
            old_name='comment',
            new_name='good',
        ),
    ]
