# Generated by Django 3.2 on 2021-10-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_rename_comment_goodcomment_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='type',
            field=models.CharField(choices=[('_DRA', 'Черновик'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('_CLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('_DELM', 'Удалённый менеджерский'), ('_CLOM', 'Закрытый менеджерский')], max_length=6, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='goodcomment',
            name='type',
            field=models.CharField(choices=[('PUB', 'Опубликовано'), ('EDI', 'Изменённый'), ('_DRA', 'Черновик'), ('_DEL', 'Удалённый'), ('_DELE', 'Удалённый изменённый'), ('_CLO', 'Закрытый менеджером'), ('_CLOE', 'Закрытый изменённый')], max_length=5, verbose_name='Тип альбома'),
        ),
        migrations.AlterField(
            model_name='goodlist',
            name='type',
            field=models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('MAN', 'Созданный персоналом'), ('_DEL', 'Удалённый'), ('_DELM', 'Удалённый менеджерский'), ('_CLO', 'Закрытый менеджером'), ('_CLOM', 'Закрытый основной'), ('_CLOMA', 'Закрытый менеджерский')], max_length=6, verbose_name='Тип альбома'),
        ),
    ]
