# Generated by Django 2.2.5 on 2019-09-05 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_auto_20190905_1211'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatedobject',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_objects', to='communities.Community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='moderationpenalty',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_penalties', to=settings.AUTH_USER_MODEL, verbose_name='Оштрафованный пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationreport',
            name='reporter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='moderation_reports', to=settings.AUTH_USER_MODEL, verbose_name='Репортер'),
            preserve_default=False,
        ),
    ]
