# Generated by Django 2.2.16 on 2020-09-27 21:39

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Кто заходит')),
                ('community', models.PositiveIntegerField(default=0, verbose_name='В какое сообщество заходил')),
                ('platform', models.PositiveIntegerField(default=0, verbose_name='0 Комп, 1 Телефон')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name_plural': 'Посещения сообщества',
                'verbose_name': 'Посещение сообщества',
            },
        ),
        migrations.CreateModel(
            name='GoodNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Кто смотрит')),
                ('good', models.PositiveIntegerField(default=0, verbose_name='Какой товар смотрит')),
                ('platform', models.PositiveIntegerField(default=0, verbose_name='0 Комп, 1 Телефон')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name_plural': 'Посещения товара',
                'verbose_name': 'Посещение товара',
            },
        ),
        migrations.CreateModel(
            name='MusicNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Кто слушает')),
                ('music', models.PositiveIntegerField(default=0, verbose_name='Какой трек слушает')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name_plural': 'Прослушивания трека',
                'verbose_name': 'Прослушивание трека',
            },
        ),
        migrations.CreateModel(
            name='PostAdNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Кто смотрит')),
                ('post', models.PositiveIntegerField(default=0, verbose_name='Какую запись смотрит')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name_plural': 'Охват рекламных записей на стене и в лентах',
                'verbose_name': 'Охват рекламной записи на стене и в лентах',
            },
        ),
        migrations.CreateModel(
            name='PostNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Кто смотрит')),
                ('post', models.PositiveIntegerField(default=0, verbose_name='Какую запись смотрит')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name_plural': 'Охват записей на стене и в лентах',
                'verbose_name': 'Охват записи на стене и в лентах',
            },
        ),
        migrations.CreateModel(
            name='UserNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.PositiveIntegerField(default=0, verbose_name='Кто заходит')),
                ('target', models.PositiveIntegerField(default=0, verbose_name='К кому заходит')),
                ('platform', models.PositiveIntegerField(default=0, verbose_name='0 Комп, 1 Телефон')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name_plural': 'Кто к кому заходил',
                'verbose_name': 'Кто к кому заходил',
            },
        ),
        migrations.CreateModel(
            name='VideoNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Кто смотрит')),
                ('video', models.PositiveIntegerField(default=0, verbose_name='Какой ролик смотрит')),
                ('platform', models.PositiveIntegerField(default=0, verbose_name='0 Комп, 1 Телефон')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name_plural': 'Просмотры ролика',
                'verbose_name': 'Просмотр ролика',
            },
        ),
        migrations.AddIndex(
            model_name='videonumbers',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='stst_videon_created_baeb2e_brin'),
        ),
        migrations.AddIndex(
            model_name='usernumbers',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='stst_usernu_created_c7bca1_brin'),
        ),
        migrations.AddIndex(
            model_name='postnumbers',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='stst_postnu_created_dd324b_brin'),
        ),
        migrations.AddIndex(
            model_name='postadnumbers',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='stst_postad_created_7e1513_brin'),
        ),
        migrations.AddIndex(
            model_name='musicnumbers',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='stst_musicn_created_771572_brin'),
        ),
        migrations.AddIndex(
            model_name='goodnumbers',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='stst_goodnu_created_ff8fc0_brin'),
        ),
        migrations.AddIndex(
            model_name='communitynumbers',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='stst_commun_created_df0234_brin'),
        ),
    ]
