# Generated by Django 2.2.5 on 2020-03-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernumbers',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во визитов'),
        ),
    ]
