# Generated by Django 2.2.16 on 2020-11-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitynumbers',
            options={'ordering': ['-created'], 'verbose_name': 'Посещение сообщества', 'verbose_name_plural': 'Посещения сообщества'},
        ),
    ]
