# Generated by Django 2.2.16 on 2020-11-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0002_auto_20201118_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitynumbers',
            options={'verbose_name': 'Посещение сообщества', 'verbose_name_plural': 'Посещения сообщества'},
        ),
    ]
