# Generated by Django 2.2.5 on 2020-03-09 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stst', '0005_auto_20200309_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernumbers',
            options={'verbose_name': 'Кто к кому заходил', 'verbose_name_plural': 'Кто к кому заходил'},
        ),
        migrations.AlterField(
            model_name='usernumbers',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL, verbose_name='К кому заходит'),
        ),
        migrations.AlterField(
            model_name='usernumbers',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_user', to=settings.AUTH_USER_MODEL, verbose_name='Кто заходит'),
        ),
        migrations.AlterUniqueTogether(
            name='usernumbers',
            unique_together={('visitor', 'target')},
        ),
    ]
