# Generated by Django 2.2.5 on 2020-03-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0006_auto_20200309_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernumbers',
            name='target',
            field=models.PositiveIntegerField(default=0, verbose_name='К кому заходит'),
        ),
        migrations.AlterField(
            model_name='usernumbers',
            name='visitor',
            field=models.PositiveIntegerField(default=0, verbose_name='Кто заходит'),
        ),
    ]
