# Generated by Django 2.2.5 on 2020-03-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0007_auto_20200309_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemnumbers',
            old_name='music',
            new_name='item',
        ),
        migrations.AddField(
            model_name='commuitynumbers',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во визитов'),
        ),
        migrations.AddField(
            model_name='goodnumbers',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во визитов'),
        ),
        migrations.AddField(
            model_name='itemnumbers',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
        migrations.AddField(
            model_name='musicnumbers',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во прослушиваний'),
        ),
        migrations.AddField(
            model_name='videonumbers',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
    ]
