# Generated by Django 2.2.5 on 2020-03-10 11:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0008_auto_20200310_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommuityNumbers',
            new_name='CommunityNumbers',
        ),
        migrations.RemoveIndex(
            model_name='communitynumbers',
            name='stst_commui_created_c8b506_brin',
        ),
        migrations.AddIndex(
            model_name='communitynumbers',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='stst_commun_created_df0234_brin'),
        ),
    ]
