# Generated by Django 2.2.5 on 2020-03-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0009_auto_20200310_1127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communitynumbers',
            unique_together={('user', 'community')},
        ),
        migrations.AlterUniqueTogether(
            name='goodnumbers',
            unique_together={('user', 'good')},
        ),
        migrations.AlterUniqueTogether(
            name='itemnumbers',
            unique_together={('user', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='musicnumbers',
            unique_together={('user', 'music')},
        ),
        migrations.AlterUniqueTogether(
            name='videonumbers',
            unique_together={('user', 'video')},
        ),
    ]
