# Generated by Django 2.2.5 on 2020-03-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0010_auto_20200310_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemnumbers',
            name='count',
        ),
    ]
