# Generated by Django 2.2.5 on 2020-03-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0011_remove_itemnumbers_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitynumbers',
            name='count',
        ),
        migrations.RemoveField(
            model_name='goodnumbers',
            name='count',
        ),
        migrations.RemoveField(
            model_name='musicnumbers',
            name='count',
        ),
        migrations.RemoveField(
            model_name='usernumbers',
            name='count',
        ),
        migrations.RemoveField(
            model_name='videonumbers',
            name='count',
        ),
        migrations.AddField(
            model_name='usernumbers',
            name='platform',
            field=models.PositiveIntegerField(default=0, verbose_name='0 Комп, 1 Телефон'),
        ),
    ]
