# Generated by Django 2.2.5 on 2020-03-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0012_auto_20200317_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitynumbers',
            name='platform',
            field=models.PositiveIntegerField(default=0, verbose_name='0 Комп, 1 Телефон'),
        ),
        migrations.AddField(
            model_name='goodnumbers',
            name='platform',
            field=models.PositiveIntegerField(default=0, verbose_name='0 Комп, 1 Телефон'),
        ),
        migrations.AddField(
            model_name='videonumbers',
            name='platform',
            field=models.PositiveIntegerField(default=0, verbose_name='0 Комп, 1 Телефон'),
        ),
    ]
