# Generated by Django 2.2.5 on 2020-03-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0013_auto_20200317_1049'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communitynumbers',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='itemnumbers',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usernumbers',
            unique_together=set(),
        ),
    ]
