# Generated by Django 2.2.5 on 2020-03-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0014_auto_20200317_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitynumbers',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='goodnumbers',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='itemnumbers',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='musicnumbers',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='usernumbers',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='videonumbers',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Создано'),
        ),
    ]
