# Generated by Django 2.2.5 on 2020-03-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0015_auto_20200317_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitynumbers',
            options={'ordering': ['-created'], 'verbose_name': 'Посещение сообщества', 'verbose_name_plural': 'Посещения сообщества'},
        ),
        migrations.AlterModelOptions(
            name='goodnumbers',
            options={'ordering': ['-created'], 'verbose_name': 'Посещение товара', 'verbose_name_plural': 'Посещения товара'},
        ),
        migrations.AlterModelOptions(
            name='itemnumbers',
            options={'ordering': ['-created'], 'verbose_name': 'Просмотр записи', 'verbose_name_plural': 'Просмотры записи'},
        ),
        migrations.AlterModelOptions(
            name='musicnumbers',
            options={'ordering': ['-created'], 'verbose_name': 'Прослушивание трека', 'verbose_name_plural': 'Прослушивания трека'},
        ),
        migrations.AlterModelOptions(
            name='usernumbers',
            options={'ordering': ['-created'], 'verbose_name': 'Кто к кому заходил', 'verbose_name_plural': 'Кто к кому заходил'},
        ),
        migrations.AlterModelOptions(
            name='videonumbers',
            options={'ordering': ['-created'], 'verbose_name': 'Просмотр ролика', 'verbose_name_plural': 'Просмотры ролика'},
        ),
        migrations.AlterUniqueTogether(
            name='goodnumbers',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='musicnumbers',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='videonumbers',
            unique_together=set(),
        ),
    ]
