# Generated by Django 2.2.5 on 2020-03-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0016_auto_20200323_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitynumbers',
            options={'verbose_name': 'Посещение сообщества', 'verbose_name_plural': 'Посещения сообщества'},
        ),
        migrations.AlterModelOptions(
            name='goodnumbers',
            options={'verbose_name': 'Посещение товара', 'verbose_name_plural': 'Посещения товара'},
        ),
        migrations.AlterModelOptions(
            name='itemnumbers',
            options={'verbose_name': 'Просмотр записи', 'verbose_name_plural': 'Просмотры записи'},
        ),
        migrations.AlterModelOptions(
            name='musicnumbers',
            options={'verbose_name': 'Прослушивание трека', 'verbose_name_plural': 'Прослушивания трека'},
        ),
        migrations.AlterModelOptions(
            name='usernumbers',
            options={'verbose_name': 'Кто к кому заходил', 'verbose_name_plural': 'Кто к кому заходил'},
        ),
        migrations.AlterModelOptions(
            name='videonumbers',
            options={'verbose_name': 'Просмотр ролика', 'verbose_name_plural': 'Просмотры ролика'},
        ),
    ]
