# Generated by Django 2.2.5 on 2019-09-13 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('follows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создан')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('follows', models.ManyToManyField(db_index=True, related_name='lists', to='follows.Follow', verbose_name='Подписчики')),
            ],
        ),
    ]
