# Generated by Django 2.2.16 on 2020-10-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Список депутатов')),
                ('slug', models.CharField(max_length=100, verbose_name='Англ. название для списка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
                ('is_reginal', models.BooleanField(default=True, verbose_name='Региональный список')),
            ],
            options={
                'verbose_name_plural': 'Списки депутатов',
                'ordering': ['order', 'name'],
                'verbose_name': 'Список депутатов',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории блога')),
                ('slug', models.CharField(max_length=100, verbose_name='Англ. название для ссылки')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name_plural': 'категории блога',
                'ordering': ['order', 'name'],
                'verbose_name': 'категория блога',
            },
        ),
        migrations.CreateModel(
            name='ElectNewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории новостей о депутате')),
                ('slug', models.CharField(max_length=100, verbose_name='Англ. название для категории')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name_plural': 'Списки депутатов',
                'ordering': ['order', 'name'],
                'verbose_name': 'Список депутатов',
            },
        ),
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фракции')),
                ('slug', models.CharField(blank=True, max_length=100, verbose_name='Для ссылки английское название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name_plural': 'Фракции',
                'ordering': ['order', 'name'],
                'verbose_name': 'Фракция',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название региона')),
                ('slug', models.CharField(blank=True, max_length=100, verbose_name='Для ссылки английское название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
                ('svg', models.CharField(blank=True, max_length=1000, verbose_name='SVG')),
            ],
            options={
                'verbose_name_plural': 'Регионы',
                'ordering': ['order', 'name'],
                'verbose_name': 'Регион',
            },
        ),
    ]
