# Generated by Django 2.2.5 on 2019-09-03 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('created', models.DateTimeField(editable=False, verbose_name='Создан')),
                ('emoji', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lists', to='common.Emoji', verbose_name='Смайл')),
            ],
        ),
    ]
