# Generated by Django 3.2 on 2021-04-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elect', '0008_alter_elect_region'),
        ('lists', '0002_auto_20201026_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
