# Generated by Django 2.2.5 on 2019-09-05 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvite',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Приглашение создано'),
        ),
    ]
