# Generated by Django 2.2.5 on 2019-10-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvite',
            name='badge',
        ),
    ]
