# Generated by Django 3.2 on 2021-09-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodCommentManageLog',
        ),
        migrations.DeleteModel(
            name='PhotoCommentManageLog',
        ),
        migrations.DeleteModel(
            name='PostCommentManageLog',
        ),
        migrations.DeleteModel(
            name='VideoCommentManageLog',
        ),
        migrations.RemoveField(
            model_name='audiomanagelog',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='goodmanagelog',
            name='post',
        ),
        migrations.RemoveField(
            model_name='photomanagelog',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='postmanagelog',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userworkermanagelog',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='videomanagelog',
            name='video',
        ),
        migrations.AddField(
            model_name='audiomanagelog',
            name='item',
            field=models.PositiveIntegerField(default=0, verbose_name='Элемент аудио'),
        ),
        migrations.AddField(
            model_name='goodmanagelog',
            name='item',
            field=models.PositiveIntegerField(default=0, verbose_name='Элемент товаров'),
        ),
        migrations.AddField(
            model_name='photomanagelog',
            name='item',
            field=models.PositiveIntegerField(default=0, verbose_name='Элемент фото'),
        ),
        migrations.AddField(
            model_name='postmanagelog',
            name='item',
            field=models.PositiveIntegerField(default=0, verbose_name='Элемент записей'),
        ),
        migrations.AddField(
            model_name='userworkermanagelog',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('CA', 'Добавлен админ пользователей'), ('DA', 'Удален админ пользователей'), ('CE', 'Добавлен редактор пользователей'), ('DE', 'Удален редактор пользователей'), ('CM', 'Добавлен модератор пользователей'), ('DM', 'Удален модератор пользователей'), ('CR', 'Добавлен менеджер рекламодателей пользователей'), ('DR', 'Удален менеджер рекламодателей пользователей')], default=0, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='videomanagelog',
            name='item',
            field=models.PositiveIntegerField(default=0, verbose_name='Элемент видео'),
        ),
        migrations.AlterField(
            model_name='audiomanagelog',
            name='action_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Список закрыт'), (2, 'Элемент закрыт'), (3, 'Комментарий закрыт'), (7, 'Список восстановлен'), (8, 'Элемент восстановлен'), (9, 'Комментарий восстановлен'), (14, 'Жалоба на список отклонена'), (15, 'Жалоба на элемент отклонена'), (16, 'Жалоба на комментарий отклонена'), (20, 'Проверка на список убрана'), (21, 'Проверка на элемент убрана'), (22, 'Проверка на комментарий убрана')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='communitymanagelog',
            name='action_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Удалено'), (2, 'Восстановлено'), (3, 'Заблокировано'), (4, 'Разблокировано'), (5, 'Вечная заморозка'), (6, 'Долгая заморозка'), (7, 'Средняя заморозка'), (8, 'Краткая заморозка'), (9, 'Разморожено'), (10, 'Выставлен предупреждающий баннер'), (11, 'Убран предупреждающий баннер'), (12, 'Жалоба отклонена'), (13, 'Проверка убрана')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='goodmanagelog',
            name='action_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Список закрыт'), (2, 'Элемент закрыт'), (3, 'Комментарий закрыт'), (7, 'Список восстановлен'), (8, 'Элемент восстановлен'), (9, 'Комментарий восстановлен'), (14, 'Жалоба на список отклонена'), (15, 'Жалоба на элемент отклонена'), (16, 'Жалоба на комментарий отклонена'), (20, 'Проверка на список убрана'), (21, 'Проверка на элемент убрана'), (22, 'Проверка на комментарий убрана')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='photomanagelog',
            name='action_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Список закрыт'), (2, 'Элемент закрыт'), (3, 'Комментарий закрыт'), (7, 'Список восстановлен'), (8, 'Элемент восстановлен'), (9, 'Комментарий восстановлен'), (14, 'Жалоба на список отклонена'), (15, 'Жалоба на элемент отклонена'), (16, 'Жалоба на комментарий отклонена'), (20, 'Проверка на список убрана'), (21, 'Проверка на элемент убрана'), (22, 'Проверка на комментарий убрана')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='postmanagelog',
            name='action_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Список закрыт'), (2, 'Элемент закрыт'), (3, 'Комментарий закрыт'), (7, 'Список восстановлен'), (8, 'Элемент восстановлен'), (9, 'Комментарий восстановлен'), (14, 'Жалоба на список отклонена'), (15, 'Жалоба на элемент отклонена'), (16, 'Жалоба на комментарий отклонена'), (20, 'Проверка на список убрана'), (21, 'Проверка на элемент убрана'), (22, 'Проверка на комментарий убрана')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='usermanagelog',
            name='action_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Удален'), (2, 'Восстановлен'), (3, 'Заблокирован'), (4, 'Разблокирован'), (5, 'Вечная заморозка'), (6, 'Долгая заморозка'), (7, 'Средняя заморозка'), (8, 'Краткая заморозка'), (9, 'Разморожен'), (10, 'Выставлен предупреждающий баннер'), (11, 'Убран предупреждающий баннер'), (12, 'Жалоба отклонена'), (13, 'Проверка убрана')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='videomanagelog',
            name='action_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Список закрыт'), (2, 'Элемент закрыт'), (3, 'Комментарий закрыт'), (7, 'Список восстановлен'), (8, 'Элемент восстановлен'), (9, 'Комментарий восстановлен'), (14, 'Жалоба на список отклонена'), (15, 'Жалоба на элемент отклонена'), (16, 'Жалоба на комментарий отклонена'), (20, 'Проверка на список убрана'), (21, 'Проверка на элемент убрана'), (22, 'Проверка на комментарий убрана')], default=0, verbose_name='Статус'),
        ),
    ]
