# Generated by Django 5.2.1 on 2025-05-17 10:55

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import users.helpers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимный')),
                ('is_multiple', models.BooleanField(default=False, verbose_name='Несколько вариантов')),
                ('is_no_edited', models.BooleanField(default=False, verbose_name='Запрет отмены голоса')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=users.helpers.upload_to_user_directory, verbose_name='Главное изображение')),
                ('type', models.CharField(choices=[('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('_CLO', 'Закрыто модератором')], default='PUB', max_length=5)),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('vote', models.PositiveIntegerField(default=0, verbose_name='Кол-во голосов')),
                ('repost', models.PositiveIntegerField(default=0, verbose_name='Кол-во репостов')),
                ('copy', models.PositiveIntegerField(default=0, verbose_name='Кол-во копий')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_community', to='communities.community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='Вариант ответа')),
                ('vote', models.PositiveIntegerField(default=0, verbose_name='Кол-во голосов')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Градация по порядку')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('_DEL', 'Удалённый'), ('_CLO', 'Закрытый менеджером'), ('_CLOMA', 'Закрытый основной'), ('_SUSMA', 'Замороженный основной'), ('_SUS', 'Замороженный')], max_length=6, verbose_name='Тип списка')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('count', models.PositiveIntegerField(default=0)),
                ('repost', models.PositiveIntegerField(default=0, verbose_name='Кол-во репостов')),
                ('copy', models.PositiveIntegerField(default=0, verbose_name='Кол-во копий')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('can_see_el', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=1, verbose_name='Кто видит записи')),
                ('create_el', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=7, verbose_name='Кто создает записи и потом с этими документами работает')),
                ('copy_el', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=1, verbose_name='Кто может копировать')),
                ('communities', models.ManyToManyField(blank=True, related_name='+', to='communities.community')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_surveylist', to='communities.community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_surveylist', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('users', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'список опросов',
                'verbose_name_plural': 'списки опросов',
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_list', to='survey.surveylist', verbose_name='Список'),
        ),
        migrations.CreateModel(
            name='SurveyVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='survey.answer', verbose_name='Опрос')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_voter', to=settings.AUTH_USER_MODEL, verbose_name='Участник опроса')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
            },
        ),
        migrations.AddIndex(
            model_name='surveylist',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='survey_surv_created_7ded41_brin'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='survey_surv_created_7a1fda_brin'),
        ),
        migrations.AddIndex(
            model_name='surveyvote',
            index=models.Index(fields=['answer', 'user'], name='survey_surv_answer__c02d10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyvote',
            unique_together={('user', 'answer')},
        ),
    ]
