# Generated by Django 3.2 on 2021-04-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='survey_list', to='survey.surveylist', verbose_name='Список'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.survey', verbose_name='Опрос'),
        ),
    ]
