# Generated by Django 3.2 on 2021-04-30 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20210430_1519'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_auto_20210430_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveylist',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='_survey_surveylist_communities_+', to='communities.Community'),
        ),
        migrations.AddField(
            model_name='surveylist',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_surveylist', to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='surveylist',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_survey_surveylist_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
