# Generated by Django 3.2 on 2021-04-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210430_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('_PRO', 'Обработка'), ('PUB', 'Созданный персоналом'), ('MAN', 'Опубликовано'), ('_DEL', 'Удалено'), ('_DELM', 'Удален менеджерский'), ('_CLO', 'Закрыто модератором'), ('_CLOM', 'Закрыт менеджерский')], default='_PRO', max_length=5),
        ),
        migrations.AlterField(
            model_name='surveylist',
            name='type',
            field=models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('MAN', 'Созданный персоналом'), ('_PRO', 'Обработка'), ('_DEL', 'Удалённый'), ('_DELM', 'Удалённый менеджерский'), ('_CLO', 'Закрытый менеджером'), ('_CLOP', 'Закрытый приватный'), ('_CLOM', 'Закрытый основной'), ('_CLOMA', 'Закрытый менеджерский')], default='_PRO', max_length=6, verbose_name='Тип списка'),
        ),
    ]
