# Generated by Django 3.2 on 2021-05-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20210430_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='reposts',
            new_name='repost',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='votes',
            new_name='vote',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='voters',
            new_name='voter',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
    ]
