# Generated by Django 3.2 on 2021-05-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_survey_community'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='status',
            new_name='type',
        ),
    ]
