# Generated by Django 3.2 on 2021-06-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_rename_status_survey_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveylist',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='survey',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
