# Generated by Django 3.2 on 2021-06-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20210613_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='survey',
            new_name='list',
        ),
    ]
