# Generated by Django 3.2 on 2021-06-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_alter_survey_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveylist',
            options={'verbose_name': 'список опросов', 'verbose_name_plural': 'списки опросов'},
        ),
        migrations.RemoveField(
            model_name='surveylist',
            name='order',
        ),
    ]
