# Generated by Django 3.2 on 2021-06-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20210614_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-order'], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
    ]
