# Generated by Django 3.2 on 2021-10-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20211007_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='type',
            field=models.CharField(choices=[('PUB', 'Созданный персоналом'), ('MAN', 'Опубликовано'), ('_DEL', 'Удалено'), ('_DELM', 'Удален менеджерский'), ('_CLO', 'Закрыто модератором'), ('_CLOM', 'Закрыт менеджерский')], max_length=5),
        ),
        migrations.AlterField(
            model_name='surveylist',
            name='type',
            field=models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('MAN', 'Созданный персоналом'), ('_DEL', 'Удалённый'), ('_DELM', 'Удалённый менеджерский'), ('_CLO', 'Закрытый менеджером'), ('_CLOM', 'Закрытый основной'), ('_CLOMA', 'Закрытый менеджерский')], max_length=6, verbose_name='Тип списка'),
        ),
    ]
