# Generated by Django 3.2 on 2021-10-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20211014_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_survey',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='surveylist',
            name='is_survey_list',
            field=models.BooleanField(default=True),
        ),
    ]
