# Generated by Django 3.1 on 2020-08-24 19:25

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid
import video.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=video.helpers.upload_to_video_directory, verbose_name='Обложка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('uri', models.CharField(max_length=255, verbose_name='Ссылка на видео')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('is_public', models.BooleanField(default=True, verbose_name='Виден другим')),
                ('is_child', models.BooleanField(default=True, verbose_name='Доступен детям')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('comments_enabled', models.BooleanField(default=True, verbose_name='Разрешить комментарии')),
                ('votes_on', models.BooleanField(default=True, verbose_name='Реакции разрешены')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Видео-ролики',
                'verbose_name_plural': 'Видео-ролики',
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Категория ролика',
                'verbose_name_plural': 'Категории ролика',
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('is_edited', models.BooleanField(default=False, verbose_name='Изменено')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удаено')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_comment_replies', to='video.videocomment', verbose_name='Родительский комментарий')),
                ('video_comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
            options={
                'verbose_name': 'комментарий к ролику',
                'verbose_name_plural': 'комментарии к ролику',
            },
        ),
        migrations.CreateModel(
            name='VideoAlbum',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('is_public', models.BooleanField(default=True, verbose_name='Виден другим')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MA', 'Основной видеоальбом'), ('AL', 'Пользовательский видеоальбом')], default='AL', max_length=5, verbose_name='Тип альбома')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_user_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Видеоальбом',
                'verbose_name_plural': 'Видеоальбомы',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='video_album', to='video.VideoAlbum', verbose_name='Альбом'),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_category', to='video.videocategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='video',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddIndex(
            model_name='videocomment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='video_video_created_af66d0_brin'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='video_video_created_babb90_brin'),
        ),
    ]
