# Generated by Django 5.2.1 on 2025-05-17 10:55

import django.contrib.postgres.indexes
import django.db.models.deletion
import imagekit.models.fields
import uuid
import video.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '__first__'),
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Категория ролика',
                'verbose_name_plural': 'Категории ролика',
            },
        ),
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('type', models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('_DEL', 'Удалённый'), ('_CLO', 'Закрытый менеджером'), ('_CLOMA', 'Закрытый основной'), ('_SUSMA', 'Замороженный основной'), ('_SUS', 'Замороженный')], max_length=6, verbose_name='Тип альбома')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('count', models.PositiveIntegerField(default=0)),
                ('repost', models.PositiveIntegerField(default=0, verbose_name='Кол-во репостов')),
                ('copy', models.PositiveIntegerField(default=0, verbose_name='Кол-во копий')),
                ('can_see_el', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=1, verbose_name='Кто видит записи')),
                ('can_see_comment', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=1, verbose_name='Кто видит комментарии')),
                ('create_el', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=7, verbose_name='Кто создает записи и потом с этими документами работает')),
                ('create_comment', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=1, verbose_name='Кто пишет комментарии')),
                ('copy_el', models.PositiveSmallIntegerField(choices=[(1, 'Все пользователи'), (2, 'Друзья'), (3, 'Друзья,друзья друзей'), (7, 'Только я'), (4, 'Друзья, кроме'), (5, 'Некоторые друзья'), (6, 'Подписчики'), (8, 'Администраторы'), (9, 'Подписчики, кроме'), (10, 'Некоторые подписчики')], default=1, verbose_name='Кто может копировать')),
                ('communities', models.ManyToManyField(blank=True, related_name='+', to='communities.community')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_lists_community', to='communities.community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_user_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('users', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Видеоальбом',
                'verbose_name_plural': 'Видеоальбомы',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=video.helpers.upload_to_video_directory, verbose_name='Обложка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('uri', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('comments_enabled', models.BooleanField(default=True, verbose_name='Разрешить комментарии')),
                ('votes_on', models.BooleanField(default=True, verbose_name='Реакции разрешены')),
                ('type', models.CharField(choices=[('_UPL', 'Загружен'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('_CLO', 'Закрыто модератором')], default='_UPL', max_length=5)),
                ('file', models.FileField(blank=True, upload_to=video.helpers.upload_to_video_directory, validators=[video.helpers.validate_file_extension], verbose_name='Видеозапись')),
                ('comment', models.PositiveIntegerField(default=0, verbose_name='Кол-во комментов')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков')),
                ('dislike', models.PositiveIntegerField(default=0, verbose_name='Кол-во дизлайков')),
                ('repost', models.PositiveIntegerField(default=0, verbose_name='Кол-во репостов')),
                ('copy', models.PositiveIntegerField(default=0, verbose_name='Кол-во копий')),
                ('order', models.PositiveIntegerField(default=0)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_community', to='communities.community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_list', to='video.videolist')),
            ],
            options={
                'verbose_name': 'Видео-ролики',
                'verbose_name_plural': 'Видео-ролики',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='VideoListPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_see_item', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто видит список/видеозаписи')),
                ('can_see_comment', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто видит комментарии')),
                ('create_item', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто создает видеозаписи')),
                ('create_comment', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто создает комментарии')),
                ('can_copy', models.PositiveSmallIntegerField(choices=[(1, 'Может иметь действия с элементом'), (2, 'Не может иметь действия с элементом'), (0, 'Нет значения')], default=0, verbose_name='Кто может добавлять список/видеозаписи себе')),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='video.videolist', verbose_name='Список записей')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Исключения/Включения друга',
                'verbose_name_plural': 'Исключения/Включения друзей',
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('text', models.TextField(blank=True)),
                ('attach', models.CharField(blank=True, max_length=200, verbose_name='Прикрепленные элементы')),
                ('type', models.CharField(choices=[('PUB', 'Опубликовано'), ('EDI', 'Изменённый'), ('_DRA', 'Черновик'), ('_DEL', 'Удалённый'), ('_DELE', 'Удалённый изменённый'), ('_CLO', 'Закрытый менеджером'), ('_CLOE', 'Закрытый изменённый')], max_length=5, verbose_name='Тип коммента')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков')),
                ('dislike', models.PositiveIntegerField(default=0, verbose_name='Кол-во дизлайков')),
                ('repost', models.PositiveIntegerField(default=0, verbose_name='Кол-во репостов')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='video.video')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_comment_replies', to='video.videocomment', verbose_name='Родительский комментарий')),
                ('sticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.stickers')),
            ],
            options={
                'verbose_name': 'комментарий к ролику',
                'verbose_name_plural': 'комментарии к ролику',
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='video_video_created_af66d0_brin')],
            },
        ),
        migrations.AddIndex(
            model_name='videolist',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='video_video_created_b04285_brin'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='video_video_created_babb90_brin'),
        ),
    ]
