# Generated by Django 3.2 on 2021-04-29 19:13

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid
import video.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=video.helpers.upload_to_video_directory, verbose_name='Обложка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('uri', models.CharField(max_length=255, verbose_name='Ссылка на видео')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('comments_enabled', models.BooleanField(default=True, verbose_name='Разрешить комментарии')),
                ('votes_on', models.BooleanField(default=True, verbose_name='Реакции разрешены')),
                ('status', models.CharField(choices=[('PRO', 'Обработка'), ('PUB', 'Опубликовано'), ('TDEL', 'Удалено'), ('PRI', 'Приватно'), ('TCLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('TDELP', 'Удалённый приватный'), ('TDELM', 'Удалённый менеджерский'), ('TCLOP', 'Закрытый приватный'), ('TCLOM', 'Закрытый менеджерский')], default='PRO', max_length=5)),
                ('file', models.FileField(blank=True, upload_to=video.helpers.upload_to_video_directory, validators=[video.helpers.validate_file_extension], verbose_name='Видеозапись')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='Кол-во комментов')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('reposts', models.PositiveIntegerField(default=0, verbose_name='Кол-во репостов')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Видео-ролики',
                'verbose_name_plural': 'Видео-ролики',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Категория ролика',
                'verbose_name_plural': 'Категории ролика',
            },
        ),
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('MAI', 'Основной'), ('LIS', 'Пользовательский'), ('PRI', 'Приватный'), ('MAN', 'Созданный персоналом'), ('TPRO', 'Обработка'), ('TDEL', 'Удалённый'), ('TDELP', 'Удалённый приватный'), ('TDELM', 'Удалённый менеджерский'), ('TCLO', 'Закрытый менеджером'), ('TCLOP', 'Закрытый приватный'), ('TCLOM', 'Закрытый основной'), ('TCLOMA', 'Закрытый менеджерский')], default='TPRO', max_length=6, verbose_name='Тип альбома')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_user_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Видеоальбом',
                'verbose_name_plural': 'Видеоальбомы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('text', models.TextField(blank=True)),
                ('attach', models.CharField(blank=True, max_length=200, verbose_name='Прикрепленные элементы')),
                ('status', models.CharField(choices=[('PUB', 'Опубликовано'), ('EDI', 'Изменённый'), ('PRO', 'Обработка'), ('TDEL', 'Удалённый'), ('TDELE', 'Удалённый изменённый'), ('TCLO', 'Закрытый менеджером'), ('TCLOE', 'Закрытый изменённый')], default='PRO', max_length=5, verbose_name='Тип альбома')),
                ('reposts', models.PositiveIntegerField(default=0, verbose_name='Кол-во репостов')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_comment_replies', to='video.videocomment', verbose_name='Родительский комментарий')),
                ('video', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
            options={
                'verbose_name': 'комментарий к ролику',
                'verbose_name_plural': 'комментарии к ролику',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='list',
            field=models.ManyToManyField(blank=True, related_name='video_list', to='video.VideoList', verbose_name='Альбом'),
        ),
        migrations.AddIndex(
            model_name='videocomment',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='video_video_created_af66d0_brin'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='video_video_created_babb90_brin'),
        ),
    ]
