# Generated by Django 3.1 on 2020-08-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200825_1051'),
        ('communities', '0001_initial'),
        ('goods', '0002_auto_20200825_1051'),
        ('posts', '0002_post_community'),
        ('chat', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='good_comment',
            field=models.ManyToManyField(blank=True, related_name='good_comment_video', to='goods.GoodComment'),
        ),
        migrations.AddField(
            model_name='video',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='item_video', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='video',
            name='item_comment',
            field=models.ManyToManyField(blank=True, related_name='comment_video', to='posts.PostComment'),
        ),
        migrations.AddField(
            model_name='video',
            name='message',
            field=models.ManyToManyField(blank=True, related_name='message_video', to='chat.Message'),
        ),
        migrations.AddField(
            model_name='video',
            name='photo_comment',
            field=models.ManyToManyField(blank=True, related_name='gallery_comment_video', to='gallery.PhotoComment'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_comment',
            field=models.ManyToManyField(blank=True, related_name='video_comment_video', to='video.VideoComment'),
        ),
        migrations.AddField(
            model_name='videoalbum',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='videoalbum',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='post_video_album', to='posts.Post'),
        ),
    ]
