# Generated by Django 3.2 on 2021-04-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20210430_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('_PRO', 'Обработка'), ('PUB', 'Опубликовано'), ('_DEL', 'Удалено'), ('PRI', 'Приватно'), ('_CLO', 'Закрыто модератором'), ('MAN', 'Созданный персоналом'), ('_DELP', 'Удалённый приватный'), ('_DELM', 'Удалённый менеджерский'), ('_CLOP', 'Закрытый приватный'), ('_CLOM', 'Закрытый менеджерский')], default='_PRO', max_length=5),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='status',
            field=models.CharField(choices=[('PUB', 'Опубликовано'), ('EDI', 'Изменённый'), ('_PRO', 'Обработка'), ('_DEL', 'Удалённый'), ('_DELE', 'Удалённый изменённый'), ('_CLO', 'Закрытый менеджером'), ('_CLOE', 'Закрытый изменённый')], default='_PRO', max_length=5, verbose_name='Тип альбома'),
        ),
    ]
