# Generated by Django 2.2.16 on 2020-09-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20200906_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoalbum',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_album_community', to='communities.Community', verbose_name='Сообщество'),
        ),
    ]
