# Generated by Django 2.2.16 on 2020-09-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20200920_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created'], 'verbose_name': 'Видео-ролики', 'verbose_name_plural': 'Видео-ролики'},
        ),
    ]
