# Generated by Django 3.2 on 2021-05-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_videolist_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='reposts',
            new_name='repost',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='views',
            new_name='view',
        ),
        migrations.RenameField(
            model_name='videocomment',
            old_name='reposts',
            new_name='repost',
        ),
        migrations.AddField(
            model_name='video',
            name='dislike',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во дизлайков'),
        ),
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='dislike',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во дизлайков'),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
    ]
