# Generated by Django 3.2 on 2021-05-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_video_community'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='status',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='videocomment',
            old_name='status',
            new_name='type',
        ),
    ]
