# Generated by Django 3.2 on 2021-06-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20210613_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videolist',
            options={'verbose_name': 'Видеоальбом', 'verbose_name_plural': 'Видеоальбомы'},
        ),
        migrations.RemoveField(
            model_name='videolist',
            name='order',
        ),
    ]
