# Generated by Django 3.2 on 2021-06-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20210614_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-order'], 'verbose_name': 'Видео-ролики', 'verbose_name_plural': 'Видео-ролики'},
        ),
    ]
