# Generated by Django 2.2.5 on 2020-05-29 09:48

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=100, unique=True, verbose_name='Вопрос')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
                'verbose_name': 'Вопрос',
            },
        ),
        migrations.CreateModel(
            name='QuestionsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, unique=True, verbose_name='Русское название')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='Английское название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
                ('icon', models.CharField(max_length=200, verbose_name='svg icon')),
            ],
            options={
                'verbose_name_plural': 'Категории вопросов',
                'ordering': ['order'],
                'verbose_name': 'Категория вопросов',
            },
        ),
        migrations.CreateModel(
            name='QuestionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DL', 'Мне не нравится, как всё устроено'), ('AU', 'Ответ неясный'), ('HQ', 'У меня остались вопросы'), ('PS', 'Вопрос решен')], max_length=2)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_vois', to='quan.Question', verbose_name='Впрос')),
            ],
            options={
                'verbose_name_plural': 'Голоса',
                'verbose_name': 'Голос',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(related_name='questions_categories', to='quan.QuestionsCategory', verbose_name='Категории вопроса'),
        ),
    ]
