# Generated by Django 5.2.1 on 2025-05-17 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, unique=True, verbose_name='Русское название')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='Английское название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
                ('icon', models.CharField(max_length=400, verbose_name='svg icon')),
            ],
            options={
                'verbose_name': 'Категория вопросов',
                'verbose_name_plural': 'Категории вопросов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=100, unique=True, verbose_name='Вопрос')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
                ('category', models.ManyToManyField(related_name='questions_categories', to='quan.questionscategory', verbose_name='Категории вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DL', 'Мне не нравится, как всё устроено'), ('AU', 'Ответ неясный'), ('HQ', 'У меня остались вопросы'), ('PS', 'Вопрос решен')], max_length=2)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_vois', to='quan.question', verbose_name='Впрос')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
            },
        ),
    ]
