# Generated by Django 2.2.5 on 2019-09-16 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityInviteNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionConfirmedNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionRequestNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FollowNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostCommentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostCommentReplyNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostCommentUserMentionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostUserMentionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('unread', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('verb', models.CharField(choices=[('PC', 'Комментарий к посту'), ('PCR', 'Ответ на комментарий к посту'), ('CR', 'Заявка в друзья'), ('CC', 'Одобренная заявка в друзья'), ('F', 'Подписка'), ('CI', 'Приглашение в сообщество'), ('PUM', 'Упоминание пользователя в посте'), ('PCUM', 'Упоминание пользователя в комментарии к посту'), ('L', 'Упоминание пользователя в лайке к посту'), ('LC', 'Упоминание пользователя в лайке на комментарий к посту'), ('DL', 'Упоминание пользователя в дизлайке к посту'), ('DC', 'Упоминание пользователя в дизлайке на комментарий к посту'), ('U', 'Упоминание пользователя о созданном аккаунте'), ('R', 'Упоминание пользователя о ответе на пост')], max_length=5, verbose_name='Тип уведомления')),
                ('slug', models.SlugField(blank=True, max_length=210, null=True)),
                ('action_object_object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_object_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-timestamp'],
                'verbose_name': 'Уведомление',
            },
        ),
    ]
