# Generated by Django 2.2.5 on 2019-09-04 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUserMentionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_user_mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.PostUserMention', verbose_name='На упоминание в посте')),
            ],
        ),
        migrations.CreateModel(
            name='PostReactionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.PostReaction', verbose_name='Реакция на пост')),
            ],
        ),
        migrations.CreateModel(
            name='PostCommentUserMentionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_comment_user_mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.PostCommentUserMention', verbose_name='На упоминание в комментарии к посту')),
            ],
        ),
        migrations.CreateModel(
            name='PostCommentReplyNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.PostComment', verbose_name='На ответ к комментарию к посту')),
            ],
        ),
        migrations.CreateModel(
            name='PostCommentReactionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_comment_reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.PostCommentReaction', verbose_name='Рекция на комментарий к посту')),
            ],
        ),
        migrations.CreateModel(
            name='PostCommentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.PostComment', verbose_name='О комментарии к посту')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, editable=False, verbose_name='Создано')),
                ('read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('notification_type', models.CharField(choices=[('PR', 'Рекция на пост'), ('PC', 'Комментарий к посту'), ('PCR', 'Ответ на комментарий к посту'), ('PCRA', 'Рефкция на комментарий к посту'), ('CR', 'Заявка в друзья'), ('CC', 'Одобренная заявка в друзья'), ('F', 'Подписка'), ('CI', 'Приглашение в сообщество'), ('PUM', 'Упоминание пользователя в посте'), ('PCUM', 'Упоминание пользователя в комментарии к посту')], max_length=5, verbose_name='Тип уведомления')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='FollowNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подписка')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionRequestNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Запрос в друзья')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionConfirmedNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_confirmator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Подтверждение заявки в друзья')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityInviteNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.CommunityInvite', verbose_name='Приглашение в сообщество')),
            ],
        ),
    ]
