# Generated by Django 2.2.5 on 2019-10-25 17:31

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('unread', models.BooleanField(db_index=True, default=True)),
                ('verb', models.CharField(choices=[('PC', 'оставил комментарий'), ('PCR', 'ответил на Ваш комментарий к посту'), ('CR', 'подал заявку в друзья'), ('CC', 'подтвердил что он Ваш друг'), ('CI', 'Приглашение в сообщество'), ('PUM', 'упомянул Вас в посте'), ('PCUM', 'упомянул Вас в комментарии к посту'), ('L', 'понравился Ваш пост'), ('LC', 'понравился Ваш комментарий к посту'), ('DL', 'не понравился Ваш пост'), ('DC', 'не понравился Ваш комментарий к посту'), ('U', 'создал аккаунт'), ('R', 'поделился Вашим постом')], max_length=5, verbose_name='Тип уведомления')),
                ('slug', models.SlugField(blank=True, max_length=210, null=True)),
                ('action_object_object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_object_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_actor', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name_plural': 'Уведомления',
                'verbose_name': 'Уведомление',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='notificatio_timesta_a92586_brin'),
        ),
    ]
