# Generated by Django 2.2.5 on 2019-10-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('PC', 'оставил комментарий'), ('PCR', 'ответил на Ваш комментарий к записи'), ('CR', 'подал заявку в друзья'), ('CC', 'подтвердил, что он Ваш друг'), ('CI', 'пригласил Вас в сообщество'), ('PUM', 'упомянул Вас в записи'), ('PCUM', 'упомянул Вас в комментарии к записи'), ('RE', 'отреагировал на Ваш пост'), ('RC', 'отреагировал на Ваш комментарий'), ('U', 'создал аккаунт'), ('R', 'поделился Вашей записью')], max_length=5, verbose_name='Тип уведомления'),
        ),
    ]
