# Generated by Django 2.2.5 on 2019-09-16 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_auto_20190916_1625'),
        ('posts', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityinvitenotification',
            name='community_invite',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='communities.CommunityInvite', verbose_name='Приглашение в сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectionconfirmednotification',
            name='connection_confirmator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Подтверждение заявки в друзья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectionrequestnotification',
            name='connection_requester',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Запрос в друзья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follownotification',
            name='follower',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подписка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notify_actor', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcommentnotification',
            name='post_comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.PostComment', verbose_name='О комментарии к посту'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcommentreplynotification',
            name='post_comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.PostComment', verbose_name='На ответ к комментарию к посту'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcommentusermentionnotification',
            name='post_comment_user_mention',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.PostCommentUserMention', verbose_name='На упоминание в комментарии к посту'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postusermentionnotification',
            name='post_user_mention',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.PostUserMention', verbose_name='На упоминание в посте'),
            preserve_default=False,
        ),
    ]
