# Generated by Django 2.2.5 on 2019-09-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityinvitenotification',
            name='community_invite',
        ),
        migrations.RemoveField(
            model_name='postcommentnotification',
            name='post_comment',
        ),
        migrations.RemoveField(
            model_name='postcommentreplynotification',
            name='post_comment',
        ),
        migrations.RemoveField(
            model_name='postcommentusermentionnotification',
            name='post_comment_user_mention',
        ),
        migrations.RemoveField(
            model_name='postusermentionnotification',
            name='post_user_mention',
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('PC', 'Комментарий к посту'), ('PCR', 'Ответ на комментарий к посту'), ('CR', 'Заявка в друзья'), ('CC', 'Одобренная заявка в друзья'), ('F', 'Подписка'), ('CI', 'Приглашение в сообщество'), ('PUM', 'Упоминание пользователя в посте'), ('PCUM', 'Упоминание пользователя в комментарии к посту'), ('L', 'Упоминание пользователя в лайке к посту'), ('LC', 'Упоминание пользователя в лайке на комментарий к посту'), ('DL', 'Упоминание пользователя в дизлайке к посту'), ('DC', 'Упоминание пользователя в дизлайке на комментарий к посту'), ('U', 'Упоминание пользователя о созданном аккаунте'), ('R', 'Упоминание пользователя о ответе на пост')], max_length=5, verbose_name='Тип уведомления'),
        ),
    ]
