# Generated by Django 2.2.5 on 2019-09-14 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20190913_1935'),
        ('posts', '0003_auto_20190913_2357'),
        ('notifications', '0002_auto_20190913_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityinvitenotification',
            name='community_invite',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='communities.CommunityInvite', verbose_name='Приглашение в сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcommentnotification',
            name='post_comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.PostComment', verbose_name='О комментарии к посту'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcommentreplynotification',
            name='post_comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.PostComment', verbose_name='На ответ к комментарию к посту'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcommentusermentionnotification',
            name='post_comment_user_mention',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.PostCommentUserMention', verbose_name='На упоминание в комментарии к посту'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postusermentionnotification',
            name='post_user_mention',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='posts.PostUserMention', verbose_name='На упоминание в посте'),
            preserve_default=False,
        ),
    ]
