# Generated by Django 2.2.5 on 2019-11-07 11:54

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('communities', '0003_auto_20191107_1154'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_auto_20191106_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityNotification',
            fields=[
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('unread', models.BooleanField(db_index=True, default=True)),
                ('verb', models.CharField(choices=[('PC', 'оставил комментарий к записи сообщества'), ('PCR', 'ответил на комментарий к записи сообщества'), ('CR', 'подал заявку в падписчики'), ('CC', 'заявка в сообщество одобрено'), ('CI', 'пригласил сообщество в сообщество'), ('PUM', 'упомянул сообщество в записи'), ('PCUM', 'упомянул сообщество в комментарии к записи'), ('RE', 'отреагировал на запись сообщества'), ('RC', 'отреагировал на комментарий сообщества'), ('RRC', 'отреагировал на ответ к комментарию сообщества'), ('R', 'поделился записью сообщества')], max_length=5, verbose_name='Тип уведомления')),
                ('slug', models.SlugField(blank=True, max_length=210, null=True)),
                ('action_object_object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_object_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_actor', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_notifications', to='communities.Community', verbose_name='Сообщество')),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name_plural': 'Уведомления сообщества',
                'verbose_name': 'Уведомление сообщества',
            },
        ),
        migrations.AddIndex(
            model_name='communitynotification',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='notificatio_timesta_ae248b_brin'),
        ),
    ]
