# Generated by Django 2.2.5 on 2019-12-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191204_1040'),
        ('gallery', '0002_auto_20191130_1403'),
        ('goods', '0002_good_community'),
        ('notifications', '0002_auto_20191203_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodcommunitynotification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Уведомление - товары сообщества', 'verbose_name_plural': 'Уведомления - товары сообщества'},
        ),
        migrations.AlterModelOptions(
            name='goodnotification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Уведомление - товары пользователя', 'verbose_name_plural': 'Уведомления - товары пользователя'},
        ),
        migrations.AlterModelOptions(
            name='itemcommunitynotification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Уведомление - записи сообщества', 'verbose_name_plural': 'Уведомления - записи сообщества'},
        ),
        migrations.AlterModelOptions(
            name='itemnotification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Уведомление - записи пользователя', 'verbose_name_plural': 'Уведомления - записи пользователя'},
        ),
        migrations.AlterModelOptions(
            name='photocommunitynotification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Уведомление - фотографии сообщества', 'verbose_name_plural': 'Уведомления - фотографии сообщества'},
        ),
        migrations.AlterModelOptions(
            name='photonotification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Уведомление - фотографии пользователя', 'verbose_name_plural': 'Уведомления - фотографии пользователя'},
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Уведомление пользователя', 'verbose_name_plural': 'Уведомления пользователя'},
        ),
        migrations.AddField(
            model_name='goodcommunitynotification',
            name='good',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.Good'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodnotification',
            name='good',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.Good'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcommunitynotification',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemnotification',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photocommunitynotification',
            name='photo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gallery.Photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photonotification',
            name='photo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gallery.Photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercommunitynotification',
            name='verb',
            field=models.CharField(choices=[('CR', 'подал заявку в сообщество'), ('CC', 'принят в сообщество'), ('J', 'вступил в сообщество')], max_length=5, verbose_name='Тип уведомления'),
        ),
    ]
