# Generated by Django 2.2.5 on 2019-10-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20191003_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionconfirmednotification',
            name='connection_confirmator',
        ),
        migrations.RemoveField(
            model_name='connectionrequestnotification',
            name='connection_requester',
        ),
        migrations.RemoveField(
            model_name='follownotification',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='postcommentnotification',
            name='post_comment',
        ),
        migrations.RemoveField(
            model_name='postcommentreplynotification',
            name='post_comment',
        ),
        migrations.RemoveField(
            model_name='postcommentusermentionnotification',
            name='post_comment_user_mention',
        ),
        migrations.RemoveField(
            model_name='postusermentionnotification',
            name='post_user_mention',
        ),
        migrations.DeleteModel(
            name='CommunityInviteNotification',
        ),
        migrations.DeleteModel(
            name='ConnectionConfirmedNotification',
        ),
        migrations.DeleteModel(
            name='ConnectionRequestNotification',
        ),
        migrations.DeleteModel(
            name='FollowNotification',
        ),
        migrations.DeleteModel(
            name='PostCommentNotification',
        ),
        migrations.DeleteModel(
            name='PostCommentReplyNotification',
        ),
        migrations.DeleteModel(
            name='PostCommentUserMentionNotification',
        ),
        migrations.DeleteModel(
            name='PostUserMentionNotification',
        ),
    ]
