# Generated by Django 2.2.5 on 2019-09-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190905_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreactionnotification',
            name='post_reaction',
        ),
        migrations.DeleteModel(
            name='PostCommentReactionNotification',
        ),
        migrations.DeleteModel(
            name='PostReactionNotification',
        ),
    ]
