# Generated by Django 2.2.5 on 2019-10-10 19:49

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20191010_1050'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='notificatio_timesta_a92586_brin'),
        ),
    ]
