# Generated by Django 2.2.5 on 2019-11-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20191107_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitynotification',
            name='verb',
            field=models.CharField(choices=[('PC', 'оставил комментарий к записи сообщества'), ('PCR', 'ответил на комментарий к записи сообщества'), ('CR', 'подал заявку в сообщество'), ('CC', 'заявка в сообщество одобрено'), ('CI', 'пригласил сообщество в сообщество'), ('PUM', 'упомянул сообщество в записи'), ('PCUM', 'упомянул сообщество в комментарии к записи'), ('RE', 'отреагировал на запись сообщества'), ('RC', 'отреагировал на комментарий сообщества'), ('RRC', 'отреагировал на ответ к комментарию сообщества'), ('R', 'поделился записью сообщества'), ('J', 'вступил в сообщество')], max_length=5, verbose_name='Тип уведомления'),
        ),
    ]
