# Generated by Django 2.2.5 on 2019-09-07 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_auto_20190906_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='content_type',
            new_name='action_object_content_type',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='owner',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='unread',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='object_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_object_object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notify_actor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='slug',
            field=models.SlugField(blank=True, max_length=210, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('PR', 'Рекция на пост'), ('PC', 'Комментарий к посту'), ('PCR', 'Ответ на комментарий к посту'), ('PCRA', 'Рефкция на комментарий к посту'), ('CR', 'Заявка в друзья'), ('CC', 'Одобренная заявка в друзья'), ('F', 'Подписка'), ('CI', 'Приглашение в сообщество'), ('PUM', 'Упоминание пользователя в посте'), ('PCUM', 'Упоминание пользователя в комментарии к посту'), ('L', 'Упоминание пользователя в лайке к посту'), ('LC', 'Упоминание пользователя в лайке на комментарий к посту'), ('DL', 'Упоминание пользователя в дизлайке к посту'), ('DC', 'Упоминание пользователя в дизлайке на комментарий к посту'), ('U', 'Упоминание пользователя о созданном аккаунте')], default='', max_length=5, verbose_name='Тип уведомления'),
            preserve_default=False,
        ),
    ]
