# Generated by Django 2.2.5 on 2019-09-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20190923_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('PC', 'оставил комментарий'), ('PCR', 'ответил на Ваш комментарий к посту'), ('CR', 'подал заявку в друзья'), ('CC', 'подтвердил что он Ваш друг'), ('CI', 'Приглашение в сообщество'), ('PUM', 'упомянул Вас в посте'), ('PCUM', 'упомянул Вас в комментарии к посту'), ('L', 'понравился Ваш пост'), ('LC', 'понравился Ваш комментарий к посту'), ('DL', 'не понравился Ваш пост'), ('DC', 'не понравился Ваш комментарий к посту'), ('U', 'создал аккаунт'), ('R', 'поделился Вашим постом')], max_length=5, verbose_name='Тип уведомления'),
        ),
    ]
