# Generated by Django 2.2.5 on 2019-12-05 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20191130_1403'),
        ('notifications', '0004_auto_20191205_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommunitynotification',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='community_for_notifications', to='communities.Community', verbose_name='Сообщество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercommunitynotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
    ]
