# Generated by Django 2.2.5 on 2019-12-07 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191204_1705'),
        ('notifications', '0005_auto_20191205_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcommunitynotification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ItemComment'),
        ),
        migrations.AddField(
            model_name='itemnotification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ItemComment'),
        ),
        migrations.AlterField(
            model_name='itemcommunitynotification',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
        migrations.AlterField(
            model_name='itemnotification',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
    ]
