# Generated by Django 2.2.5 on 2019-12-27 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20191223_1222'),
        ('notifications', '0006_auto_20191207_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcommunitynotification',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='item_community_notifications', to='communities.Community', verbose_name='Сообщество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemcommunitynotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_manager', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
    ]
