# Generated by Django 2.2.5 on 2019-12-29 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20191223_1222'),
        ('notifications', '0007_auto_20191227_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodcommunitynotification',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='community_good_notify', to='communities.Community', verbose_name='Сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photocommunitynotification',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='community_photo_notify', to='communities.Community', verbose_name='Сообщество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodcommunitynotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_good_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Сообщество'),
        ),
        migrations.AlterField(
            model_name='itemcommunitynotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_item_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='photocommunitynotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_photo_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Сообщество'),
        ),
        migrations.AlterField(
            model_name='usercommunitynotification',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_users_notify', to='communities.Community', verbose_name='Сообщество'),
        ),
        migrations.AlterField(
            model_name='usercommunitynotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_user_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
    ]
