# Generated by Django 5.2.1 on 2025-05-17 10:54

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('verb', models.CharField(choices=[('ITE', ' разместил'), ('SIT', ' предложил'), ('ITS', ' разместили'), ('COM', ' оставил'), ('WCOM', ' оставила'), ('GCOM', ' оставили'), ('REP', ' ответил на'), ('WREP', ' ответила на'), ('GREP', ' ответили на'), ('PUM', ' упомянул Вас в записи'), ('WPUM', ' упомянула Вас в записи'), ('GPUM', ' упомянули Вас в записи'), ('PCUM', ' упомянул Вас в комментарии к записи'), ('WPCUM', ' упомянула Вас в комментарии к записи'), ('GPCUM', ' упомянули Вас в комментарии к записи'), ('LIK', ' оценил'), ('WLIK', ' оценила'), ('GLIK', ' оценили'), ('DIS', ' не оценил'), ('WDIS', ' не оценила'), ('GDIS', ' не оценили'), ('LCO', ' оценил'), ('WLCO', ' оценила '), ('GLCO', ' оценили'), ('DCO', ' не оценил'), ('WDCO', ' не оценила'), ('GDCO', ' не оценили'), ('LRE', ' оценил'), ('WLRE', ' оценила'), ('GLRE', ' оценили'), ('DRE', ' не оценил'), ('WDRE', ' не оценила'), ('GDRE', ' не оценили'), ('SVO', ' участвовал в опросе'), ('WSVO', ' участвовала в опросе'), ('GSVO', ' участвовали в опросе'), ('RE', ' поделился'), ('WRE', ' поделилась'), ('GRE', ' поделились'), ('CR', ' поделилось'), ('GCLR', ' поделились'), ('LRE', ' поделился'), ('WRE', ' поделилась'), ('GRE', ' поделились'), ('CLR', ' поделилось'), ('GCLR', ' поделились'), ('CRE', ' подал заявку в'), ('WCRE', ' подала заявку в'), ('GCRE', ' подали заявку в'), ('CCO', ' принят в'), ('WCCO', ' принята'), ('GCCO', ' приняты'), ('INV', ' рекомендует'), ('WINV', ' рекомендует'), ('GINV', ' рекомендуют'), ('CJO', ' принят'), ('WCJO', ' принята'), ('GCJO', ' приняты'), ('REG', ' зарегистрировался'), ('WREG', ' зарегистрировалась'), ('GREG', ' зарегистрировались')], max_length=5, verbose_name='Тип уведомления')),
                ('status', models.CharField(choices=[('U', 'Не прочитано'), ('R', 'Прочитано'), ('D', 'Удалено'), ('C', 'Закрыто')], default='U', max_length=1, verbose_name='Статус')),
                ('type', models.CharField(choices=[('USE', 'Пользователь'), ('COM', 'Сообщество'), ('MUL', 'Плейлист'), ('MUS', 'Трек'), ('DOL', 'Список документов'), ('DOC', 'документ'), ('SUL', 'Список опросов'), ('SUR', 'опрос'), ('PHL', 'Список фотографий'), ('PHO', 'Фото'), ('PHWAL', 'Фото со стены'), ('PHAVA', 'Фото со страницы'), ('PHLIS', 'Фото альбома'), ('PHOC', 'Коммент к фотографии'), ('POL', 'Список записей'), ('POS', 'запись'), ('POSC', 'Коммент к записи'), ('GOL', 'Список товаров'), ('GOO', 'товар'), ('GOOC', 'Коммент к товару'), ('VIL', 'Список роликов'), ('VID', 'Ролик'), ('VIDC', 'Коммент к ролику')], max_length=5, verbose_name='Класс объекта')),
                ('object_id', models.PositiveIntegerField(default=0, verbose_name='id объекта')),
                ('action_community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='communities.community', verbose_name='Сообщество')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('object_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notify.notify', verbose_name='Например, несколько человек лайкает пост. Нужно для группировки')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('user_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notify.notify', verbose_name='Например, человек лайкает несколько постов. Нужно для группировки')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created'],
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='notify_noti_created_9feff9_brin')],
            },
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('verb', models.CharField(choices=[('ITE', ' разместил'), ('SIT', ' предложил'), ('ITS', ' разместили'), ('COM', ' оставил'), ('WCOM', ' оставила'), ('GCOM', ' оставили'), ('REP', ' ответил на'), ('WREP', ' ответила на'), ('GREP', ' ответили на'), ('PUM', ' упомянул Вас в записи'), ('WPUM', ' упомянула Вас в записи'), ('GPUM', ' упомянули Вас в записи'), ('PCUM', ' упомянул Вас в комментарии к записи'), ('WPCUM', ' упомянула Вас в комментарии к записи'), ('GPCUM', ' упомянули Вас в комментарии к записи'), ('LIK', ' оценил'), ('WLIK', ' оценила'), ('GLIK', ' оценили'), ('DIS', ' не оценил'), ('WDIS', ' не оценила'), ('GDIS', ' не оценили'), ('LCO', ' оценил'), ('WLCO', ' оценила '), ('GLCO', ' оценили'), ('DCO', ' не оценил'), ('WDCO', ' не оценила'), ('GDCO', ' не оценили'), ('LRE', ' оценил'), ('WLRE', ' оценила'), ('GLRE', ' оценили'), ('DRE', ' не оценил'), ('WDRE', ' не оценила'), ('GDRE', ' не оценили'), ('SVO', ' участвовал в опросе'), ('WSVO', ' участвовала в опросе'), ('GSVO', ' участвовали в опросе'), ('RE', ' поделился'), ('WRE', ' поделилась'), ('GRE', ' поделились'), ('CR', ' поделилось'), ('GCLR', ' поделились'), ('LRE', ' поделился'), ('WRE', ' поделилась'), ('GRE', ' поделились'), ('CLR', ' поделилось'), ('GCLR', ' поделились'), ('CRE', ' подал заявку в'), ('WCRE', ' подала заявку в'), ('GCRE', ' подали заявку в'), ('CCO', ' принят в'), ('WCCO', ' принята'), ('GCCO', ' приняты'), ('INV', ' рекомендует'), ('WINV', ' рекомендует'), ('GINV', ' рекомендуют'), ('CJO', ' принят'), ('WCJO', ' принята'), ('GCJO', ' приняты'), ('REG', ' зарегистрировался'), ('WREG', ' зарегистрировалась'), ('GREG', ' зарегистрировались')], max_length=5, verbose_name='Тип уведомления')),
                ('status', models.CharField(choices=[('U', 'Не прочитано'), ('R', 'Прочитано'), ('D', 'Удалено'), ('C', 'Закрыто')], default='U', max_length=1, verbose_name='Статус')),
                ('type', models.CharField(choices=[('USE', 'Пользователь'), ('COM', 'Сообщество'), ('MUL', 'Плейлист'), ('MUS', 'Трек'), ('DOL', 'Список документов'), ('DOC', 'документ'), ('SUL', 'Список опросов'), ('SUR', 'опрос'), ('PHL', 'Список фотографий'), ('PHO', 'Фото'), ('PHWAL', 'Фото со стены'), ('PHAVA', 'Фото со страницы'), ('PHLIS', 'Фото альбома'), ('PHOC', 'Коммент к фотографии'), ('POL', 'Список записей'), ('POS', 'запись'), ('POSC', 'Коммент к записи'), ('GOL', 'Список товаров'), ('GOO', 'товар'), ('GOOC', 'Коммент к товару'), ('VIL', 'Список роликов'), ('VID', 'Ролик'), ('VIDC', 'Коммент к ролику')], max_length=5, verbose_name='Класс объекта')),
                ('object_id', models.PositiveIntegerField(default=0, verbose_name='id объекта')),
                ('action_community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='communities.community', verbose_name='Сообщество')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community', verbose_name='Сообщество')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_wall', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('object_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notify.wall', verbose_name='Например, несколько человек лайкает пост. Нужно для группировки')),
                ('user_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notify.wall', verbose_name='Например, человек лайкает несколько постов. Нужно для группировки')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created'],
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='notify_wall_created_656667_brin')],
            },
        ),
    ]
