# Generated by Django 3.2 on 2021-04-30 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='action_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='notify',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='notify',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Инициатор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notify',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='wall',
            name='action_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='wall',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community', verbose_name='Сообщество'),
        ),
        migrations.AddField(
            model_name='wall',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='creator_wall', to='users.user', verbose_name='Инициатор'),
            preserve_default=False,
        ),
    ]
