# Generated by Django 3.1 on 2020-08-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200826_1709'),
        ('gallery', '0002_auto_20200826_1709'),
        ('communities', '0001_initial'),
        ('posts', '0001_initial'),
        ('video', '0001_initial'),
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodcommunitynotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.goodcomment'),
        ),
        migrations.AddField(
            model_name='goodcommunitynotify',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.good'),
        ),
        migrations.AddField(
            model_name='goodnotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.goodcomment'),
        ),
        migrations.AddField(
            model_name='goodnotify',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.good'),
        ),
        migrations.AddField(
            model_name='itemcommunitynotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.postcomment'),
        ),
        migrations.AddField(
            model_name='itemcommunitynotify',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='item_community_notifications', to='communities.community', verbose_name='Сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcommunitynotify',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='itemnotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.postcomment'),
        ),
        migrations.AddField(
            model_name='itemnotify',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='photocommunitynotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.photocomment'),
        ),
        migrations.AddField(
            model_name='photocommunitynotify',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='community_photo_notify', to='communities.community', verbose_name='Сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photocommunitynotify',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.photo'),
        ),
        migrations.AddField(
            model_name='photonotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.photocomment'),
        ),
        migrations.AddField(
            model_name='photonotify',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.photo'),
        ),
        migrations.AddField(
            model_name='usercommunitynotify',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='community_users_notify', to='communities.community', verbose_name='Сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocommunitynotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.videocomment'),
        ),
        migrations.AddField(
            model_name='videocommunitynotify',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='video_community_notifications', to='communities.community', verbose_name='Сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocommunitynotify',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.video'),
        ),
        migrations.AddField(
            model_name='videonotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.videocomment'),
        ),
        migrations.AddField(
            model_name='videonotify',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.video'),
        ),
    ]
