# Generated by Django 2.2.16 on 2020-09-27 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('video', '0001_initial'),
        ('goods', '0002_auto_20200927_2234'),
        ('gallery', '0002_auto_20200927_2234'),
        ('communities', '0002_community_post'),
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodcommunitynotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodComment'),
        ),
        migrations.AddField(
            model_name='goodcommunitynotify',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='community_good_notify', to='communities.Community', verbose_name='Сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodcommunitynotify',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Good'),
        ),
        migrations.AddField(
            model_name='goodnotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodComment'),
        ),
        migrations.AddField(
            model_name='goodnotify',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Good'),
        ),
        migrations.AddField(
            model_name='photocommunitynotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.PhotoComment'),
        ),
        migrations.AddField(
            model_name='photocommunitynotify',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='community_photo_notify', to='communities.Community', verbose_name='Сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photocommunitynotify',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Photo'),
        ),
        migrations.AddField(
            model_name='photonotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.PhotoComment'),
        ),
        migrations.AddField(
            model_name='photonotify',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Photo'),
        ),
        migrations.AddField(
            model_name='postcommunitynotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.PostComment'),
        ),
        migrations.AddField(
            model_name='postcommunitynotify',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_community_notifications', to='communities.Community', verbose_name='Сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcommunitynotify',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AddField(
            model_name='postnotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.PostComment'),
        ),
        migrations.AddField(
            model_name='postnotify',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AddField(
            model_name='usercommunitynotify',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='community_users_notify', to='communities.Community', verbose_name='Сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocommunitynotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.VideoComment'),
        ),
        migrations.AddField(
            model_name='videocommunitynotify',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='video_community_notifications', to='communities.Community', verbose_name='Сообщество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocommunitynotify',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
        migrations.AddField(
            model_name='videonotify',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.VideoComment'),
        ),
        migrations.AddField(
            model_name='videonotify',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
    ]
