# Generated by Django 2.2.16 on 2020-11-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20200927_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodcommunitynotify',
            old_name='actor',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='goodnotify',
            old_name='actor',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='photocommunitynotify',
            old_name='actor',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='photonotify',
            old_name='actor',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='postcommunitynotify',
            old_name='actor',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='postnotify',
            old_name='actor',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='usercommunitynotify',
            old_name='actor',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='usernotify',
            old_name='actor',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='videocommunitynotify',
            old_name='actor',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='videonotify',
            old_name='actor',
            new_name='creator',
        ),
    ]
