# Generated by Django 3.1 on 2020-08-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20200825_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodcommunitynotify',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='goodcommunitynotify',
            name='community',
        ),
        migrations.RemoveField(
            model_name='goodcommunitynotify',
            name='good',
        ),
        migrations.RemoveField(
            model_name='goodnotify',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='goodnotify',
            name='good',
        ),
        migrations.RemoveField(
            model_name='itemcommunitynotify',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='itemcommunitynotify',
            name='community',
        ),
        migrations.RemoveField(
            model_name='itemcommunitynotify',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemnotify',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='itemnotify',
            name='item',
        ),
        migrations.RemoveField(
            model_name='photocommunitynotify',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='photocommunitynotify',
            name='community',
        ),
        migrations.RemoveField(
            model_name='photocommunitynotify',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photonotify',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='photonotify',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='usercommunitynotify',
            name='community',
        ),
        migrations.RemoveField(
            model_name='videocommunitynotify',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='videocommunitynotify',
            name='community',
        ),
        migrations.RemoveField(
            model_name='videocommunitynotify',
            name='video',
        ),
        migrations.RemoveField(
            model_name='videonotify',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='videonotify',
            name='video',
        ),
    ]
