# Generated by Django 3.1 on 2020-09-05 16:27

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_auto_20200903_1301'),
        ('notify', '0002_auto_20200826_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommunityNotify',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('unread', models.BooleanField(default=True)),
                ('verb', models.CharField(choices=[('PC', 'оставил комментарий к записи сообщества'), ('PCR', 'ответил на комментарий к записи сообщества'), ('PUM', 'упомянул сообщество в записи'), ('PCUM', 'упомянул сообщество в комментарии к записи'), ('L', 'понравилась запись сообщества'), ('D', 'не понравилась запись сообщества'), ('LC', 'понравился комментарий в сообществе'), ('DC', 'не понравился комментарий в сообществе'), ('R', 'поделился записью сообщества')], max_length=5, verbose_name='Тип уведомления')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.postcomment')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_community_notifications', to='communities.community', verbose_name='Сообщество')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_post_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление - записи сообщества',
                'verbose_name_plural': 'Уведомления - записи сообщества',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PostNotify',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('unread', models.BooleanField(default=True)),
                ('verb', models.CharField(choices=[('PC', 'оставил комментарий к записи'), ('PCR', 'ответил на Ваш комментарий к записи'), ('PUM', 'упомянул Вас в записи'), ('PCUM', 'упомянул Вас в комментарии к записи'), ('L', 'понравилась Ваша запись'), ('D', 'не понравилась Ваша запись'), ('LC', 'понравился Ваш комментарий к записи'), ('DC', 'не понравился Ваш комментарий к записи'), ('LRC', 'понравился Ваш ответ на комментарий  к записи'), ('DRC', 'не понравился Ваш ответ к комментарий к записи'), ('R', 'поделился Вашей записью')], max_length=5, verbose_name='Тип уведомления')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.postcomment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление - записи пользователя',
                'verbose_name_plural': 'Уведомления - записи пользователя',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='itemnotify',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='itemnotify',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='itemnotify',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemnotify',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='ItemCommunityNotify',
        ),
        migrations.DeleteModel(
            name='ItemNotify',
        ),
        migrations.AddIndex(
            model_name='postnotify',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='notify_post_created_e59d59_brin'),
        ),
        migrations.AddIndex(
            model_name='postcommunitynotify',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='notify_post_created_4bb373_brin'),
        ),
    ]
