# Generated by Django 3.2 on 2021-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_auto_20210502_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='type',
            field=models.CharField(choices=[('USE', 'Пользователь'), ('COM', 'Сообщество'), ('MUL', 'Плейлист'), ('MUS', 'Трек'), ('DOL', 'Список документов'), ('DOC', 'документ'), ('SUL', 'Список опросов'), ('SUR', 'опрос'), ('PHL', 'Список фотографий'), ('PHO', 'Фото'), ('PHWAL', 'Фото со стены'), ('PHAVA', 'Фото со страницы'), ('PHLIS', 'Фото альбома'), ('PHOC', 'Коммент к фотографии'), ('POL', 'Список записей'), ('POS', 'запись'), ('POSC', 'Коммент к записи'), ('GOL', 'Список товаров'), ('GOO', 'товар'), ('GOOC', 'Коммент к товару'), ('VIL', 'Список роликов'), ('VID', 'Ролик'), ('VIDC', 'Коммент к ролику')], max_length=5, verbose_name='Класс объекта'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='type',
            field=models.CharField(choices=[('USE', 'Пользователь'), ('COM', 'Сообщество'), ('MUL', 'Плейлист'), ('MUS', 'Трек'), ('DOL', 'Список документов'), ('DOC', 'документ'), ('SUL', 'Список опросов'), ('SUR', 'опрос'), ('PHL', 'Список фотографий'), ('PHO', 'Фото'), ('PHWAL', 'Фото со стены'), ('PHAVA', 'Фото со страницы'), ('PHLIS', 'Фото альбома'), ('PHOC', 'Коммент к фотографии'), ('POL', 'Список записей'), ('POS', 'запись'), ('POSC', 'Коммент к записи'), ('GOL', 'Список товаров'), ('GOO', 'товар'), ('GOOC', 'Коммент к товару'), ('VIL', 'Список роликов'), ('VID', 'Ролик'), ('VIDC', 'Коммент к ролику')], max_length=5, verbose_name='Класс объекта'),
        ),
    ]
