# Generated by Django 3.2 on 2021-12-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_auto_20210502_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityFeaturedPk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Кто подписывается')),
                ('community', models.PositiveIntegerField(default=0, verbose_name='На какое сообщество подписывается')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Отключено'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=9, verbose_name='Уровень отображения')),
            ],
            options={
                'verbose_name': 'Новости рекомендованного сообщества',
                'verbose_name_plural': 'Новости рекомендованных сообществ',
            },
        ),
        migrations.CreateModel(
            name='CommunityNewsPk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Кто подписывается')),
                ('community', models.PositiveIntegerField(default=0, verbose_name='На какое сообщество подписывается')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Отключено'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=9, verbose_name='Уровень отображения')),
            ],
            options={
                'verbose_name': 'Новости по по факту подписки на сообщество',
                'verbose_name_plural': 'Новости по по факту подписки на сообщество',
            },
        ),
        migrations.CreateModel(
            name='UserFeaturedPk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Кто подписывается')),
                ('target', models.PositiveIntegerField(default=0, verbose_name='На кого подписывается')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Отключено'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=9, verbose_name='Уровень отображения')),
            ],
            options={
                'verbose_name': 'Новости рекомендованного пользователя',
                'verbose_name_plural': 'Новости рекомендованных пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserNewsPk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Кто подписывается')),
                ('target', models.PositiveIntegerField(default=0, verbose_name='На кого подписывается')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Отключено'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=9, verbose_name='Уровень отображения')),
            ],
            options={
                'verbose_name': 'Новости по по факту дружбы или подписки в друзья',
                'verbose_name_plural': 'Новости по по факту дружбы или подписки в друзья',
            },
        ),
        migrations.DeleteModel(
            name='CommunityNewsNotify',
        ),
        migrations.DeleteModel(
            name='UserNewsNotify',
        ),
    ]
