# Generated by Django 3.2 on 2021-12-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_auto_20211209_1941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityFeaturedPk',
        ),
        migrations.DeleteModel(
            name='CommunityNewsPk',
        ),
        migrations.DeleteModel(
            name='UserFeaturedPk',
        ),
        migrations.DeleteModel(
            name='UserNewsPk',
        ),
    ]
