# Generated by Django 3.2 on 2021-12-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0006_auto_20211210_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityProfileNotify',
        ),
        migrations.DeleteModel(
            name='UserProfileNotify',
        ),
    ]
